import { expect, test, type Page, type APIRequestContext } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
const backend='http://127.0.0.1:8793', candidateUrl='http://127.0.0.1:6373', hrUrl='http://127.0.0.1:6386';
const token='API3-UI-SYNTHETIC-test-reset-token';
const people=['alex-chen','maya-patel','leo-zhang','sam-taylor'];
async function read(request:APIRequestContext,id='alex-chen') {const r=await request.get(`${backend}/api/demo?candidateId=${id}`);expect(r.ok()).toBeTruthy();return (await r.json()).data;}
async function reset(request:APIRequestContext) {const {data}=await(await request.get(`${backend}/api/demo/comparison`)).json();const r=await request.post(`${backend}/api/demo/reset`,{headers:{'Idempotency-Key':crypto.randomUUID(),'X-Demo-Admin-Token':token},data:{schemaVersion:'3.0',sessionId:data.sessionId}});expect(r.ok()).toBeTruthy();return (await r.json()).data;}
const base=(d:any)=>({schemaVersion:'3.0',sessionId:d.sessionId,candidateId:d.candidate.id,jobId:d.job.id,datasetVersion:d.datasetVersion});
const binding=(d:any)=>({...base(d),taskId:d.task.taskId,targetRequirementId:d.task.targetRequirementId});
async function post(request:APIRequestContext,path:string,data:unknown) {const r=await request.post(`${backend}/api/demo${path}`,{headers:{'Idempotency-Key':crypto.randomUUID()},data});expect(r.ok(),await r.text()).toBeTruthy();return (await r.json()).data;}
async function seedTask(request:APIRequestContext,id='alex-chen',target='business-problem-solving') {const d=await read(request,id);return post(request,'/task/send',{...binding(d),targetRequirementId:target,templateId:({'sql':'harbourcart-sql-v1','data-analysis':'harbourcart-data-analysis-v1','business-problem-solving':'harbourcart-bps-v1'} as Record<string,string>)[target],instructions:`Synthetic ${target} test task; show bounded original evidence.`,gapReason:'A specific evidence gap needs a bounded check.'});}
async function seedSubmission(request:APIRequestContext,id='alex-chen',summary='Synthetic current work') {const d=await read(request,id);return post(request,'/submission',{...binding(d),submissionVersion:d.workflow.nextSubmissionVersion,previousSubmissionId:d.workflow.nextSubmissionVersion===2?d.submission.submissionId:null,previousContentFingerprint:d.workflow.nextSubmissionVersion===2?d.submission.contentFingerprint:null,summary,findings:[],processEvidence:[]});}
async function nav(page:Page,name:string) {await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name,exact:true}).click();}
async function refresh(page:Page) {await page.getByRole('button',{name:'Refresh shared case',exact:true}).click();await expect(page.getByRole('button',{name:'Refresh shared case',exact:true})).toBeEnabled();await expect(page.getByText('Connected · four-person shared case',{exact:true})).toBeVisible();}
async function open(page:Page,role:'hr'|'candidate',id='alex-chen',section='') {await page.goto(`${role==='hr'?hrUrl:candidateUrl}/?candidateId=${id}${section?`#${section}`:''}`);await expect(page.getByText('Connected · four-person shared case',{exact:true})).toBeVisible();await expect(page.getByLabel('Current candidate',{exact:true})).toHaveValue(id);}
async function sendTask(page:Page,id:string,target:string) {await open(page,'hr',id,'tasks');await page.getByLabel('Target skill',{exact:true}).selectOption(target);await page.getByLabel('Evidence gap / task reason',{exact:true}).fill('A bounded evidence gap needs verification.');await page.getByRole('button',{name:'Send task',exact:true}).click();await expect(page.getByRole('button',{name:'Send task',exact:true})).toHaveCount(0);}
async function start(page:Page,id='alex-chen') {await open(page,'candidate',id,'tasks');await page.getByRole('button',{name:'Start V1 draft',exact:true}).click();await expect(page.getByLabel('Executive summary',{exact:true})).toBeVisible();}
async function submit(page:Page,request:APIRequestContext,id:string,version:number,summary:string) {await page.getByLabel('Executive summary',{exact:true}).fill(summary);await page.getByRole('button',{name:`Submit V${version}`,exact:true}).click();await page.getByRole('button',{name:`Confirm V${version} submission`,exact:true}).click();await expect.poll(async()=>(await read(request,id)).currentSubmissionVersion).toBe(version);await expect(page.getByRole('dialog')).toHaveCount(0);}
async function review(page:Page,decision:string,comment:string) {await page.getByRole('button',{name:decision,exact:true}).click();await page.getByLabel('Public review comment',{exact:true}).fill(comment);await page.getByRole('button',{name:'Save evidence review',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
async function restart() {const control=new URL('../../../.ci-results/api3-test-control.json',import.meta.url);const old=JSON.parse(await readFile(control,'utf8'));process.kill(old.pid,'SIGUSR2');await expect.poll(async()=>JSON.parse(await readFile(control,'utf8')).generation).toBe(old.generation+1);}
let runtimeErrors:string[]=[];
test.beforeEach(async({request,context})=>{runtimeErrors=[];const watch=(page:Page)=>page.on('pageerror',error=>runtimeErrors.push(error.message));context.pages().forEach(watch);context.on('page',watch);await reset(request);});
test.afterEach(()=>{expect(runtimeErrors).toEqual([]);});

test('T01 four explicit service identities, actual company/resources and no preview state',async({page,request})=>{
  await open(page,'hr');await expect(page.locator('tbody tr')).toHaveCount(4);
  for(const id of people) {await open(page,'candidate',id);const d=await read(request,id);await expect(page.getByRole('heading',{name:d.candidate.name,exact:true})).toBeVisible();expect(d.application.candidateId).toBe(id);await expect(page.getByText('Frontend mock · synthetic materials and illustrative marks',{exact:true})).toHaveCount(0);}
  const writes=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('evidencebridge.revision5.ui-preview')));expect(writes).toEqual([]);
});

test('T02 comparison uses server numbers and owned UTF-16 source quotations',async({page,request})=>{
  await open(page,'hr');const d=await read(request);expect(d.assessment.application_review.score.overallPercentage).toBeNull();await expect(page.locator('tr[data-candidate="alex-chen"]')).toContainText('Needs evidence');
  await page.getByRole('button',{name:'Open Alex Chen',exact:true}).click();await page.locator('.r5-criterion-body .eb-citation').first().click();const ref=d.assessment.application_review.items.find((x:any)=>x.criterionId==='B3').sourceRefs[0];await expect(page.locator('.r5-inline-source mark')).toHaveText(ref.quote);
  await page.getByLabel('Current candidate').selectOption('maya-patel');await expect(page.getByLabel('Current candidate')).toHaveValue('maya-patel');await expect(page.locator('.r5-inline-source mark')).toHaveCount(0);
});

test('T03 Alex BPS real V1 → More → V2 → Confirm, private draft exclusion and immutable version history',async({page:candidate,context,request},info)=>{
  const hr=await context.newPage(), writes:string[]=[];candidate.on('request',r=>{if(r.method()==='POST')writes.push(r.postData()??'');});
  await sendTask(hr,'alex-chen','business-problem-solving');await start(candidate);
  await candidate.getByRole('tab',{name:'Private notebook',exact:true}).click();await candidate.getByLabel('Private notes',{exact:true}).fill('PRIVATE-API3-ALEX-DO-NOT-SHARE');
  const first='😀中文 API3 Alex V1: Paid Search is a signal, not a proven cause.';await submit(candidate,request,'alex-chen',1,first);
  await nav(candidate,'Work & feedback');const download=candidate.waitForEvent('download');await candidate.getByRole('button',{name:'Export V1 public work',exact:true}).click();expect(await readFile((await(await download).path())!,'utf8')).not.toContain('PRIVATE');
  await refresh(hr);await expect(hr.getByText(first,{exact:true}).first()).toBeVisible();await hr.getByRole('button',{name:'Run evidence analysis',exact:true}).click();await expect.poll(async()=>(await read(request)).analysis.status).toBe('succeeded');await hr.locator('.eb-review-grid .eb-citation:visible').first().click();await expect(hr.locator('[data-source-version] mark')).toContainText('😀中文 API3 Alex V1');await hr.getByRole('button',{name:'Clear quotation',exact:true}).click();
  await review(hr,'Needs More Evidence','Compare matched cohorts and retain uncertainty.');const frozen=(await read(request)).versions[0];
  await refresh(candidate);await nav(candidate,'My task');await candidate.getByRole('button',{name:'Copy V1 public work into V2',exact:true}).click();await candidate.getByRole('tab',{name:'Private notebook',exact:true}).click();await expect(candidate.getByLabel('Private notes')).toHaveValue('');
  await submit(candidate,request,'alex-chen',2,'😀中文 API3 Alex V2: use a matched cohort before changing spend.');await refresh(hr);await expect(hr.getByRole('button',{name:'Needs More Evidence',exact:true})).toHaveCount(0);await review(hr,'Confirm evidence','V2 supports a bounded confirmation.');
  const final=await read(request);expect(final.versions[0]).toEqual(frozen);expect(final.workflow.isTerminal).toBe(true);expect(final.assessment.task_v2).toBeNull();expect(final.shortlist.status).toBe('not_retained');expect(JSON.stringify(final)).not.toContain('PRIVATE');expect(writes.join('')).not.toContain('PRIVATE');
  await refresh(candidate);await nav(candidate,'Work & feedback');await candidate.getByLabel('Submission version').selectOption('1');await expect(candidate.getByText(first,{exact:true}).first()).toBeVisible();await candidate.getByLabel('Submission version').selectOption('2');await expect(candidate.getByText('V2 supports a bounded confirmation.',{exact:true})).toBeVisible();await expect(candidate.getByRole('button',{name:/Start V3|Copy V1|Start V2/})).toHaveCount(0);
  await hr.screenshot({path:info.outputPath('alex-bps-v2-confirmed.png'),fullPage:true});
});

for(const [n,id,target,decision] of [[4,'maya-patel','sql','Evidence Still Insufficient'],[5,'leo-zhang','data-analysis','Confirm evidence'],[6,'sam-taylor','sql','Confirm evidence']]) {
  test(`T0${n} ${id} has the same real targeted submission/review controls`,async({page:candidate,context,request})=>{
    const hr=await context.newPage();await sendTask(hr,String(id),String(target));await start(candidate,String(id));await submit(candidate,request,String(id),1,`Synthetic ${id} original ${target} work, bounded uncertainty.`);await refresh(hr);await hr.getByRole('button',{name:'Run evidence analysis',exact:true}).click();await expect.poll(async()=>(await read(request,String(id))).analysis.status).toBe('succeeded');
    const analyzed=await read(request,String(id));expect(analyzed.analysis.result.observations.map((x:any)=>x.dimension)).toEqual(target==='sql'?['S1','S2','S3']:['D1','D2','D3']);await review(hr,String(decision),'This first-version evidence decision is final.');await refresh(candidate);await nav(candidate,'My task');await expect(candidate.getByRole('button',{name:/Start V2|Copy V1|Start V3/})).toHaveCount(0);expect((await read(request,String(id))).workflow.isTerminal).toBe(true);
    for(const other of people.filter(p=>p!==id))expect((await read(request,other)).submission).toBeNull();
  });
}

test('T07 human assessment appends a service revision without changing immutable baseline or auto-retaining',async({page,request})=>{
  await open(page,'hr','alex-chen','evidence');const before=await read(request);await page.getByRole('button',{name:'Edit human assessment',exact:true}).click();await page.getByLabel('Judgment reason',{exact:true}).fill('A human-reviewed bounded revision from the original source.');await page.getByLabel('Assessment operator label',{exact:true}).fill('Synthetic QA reviewer');await page.getByRole('button',{name:'Save assessment revision',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  const after=await read(request);expect(after.assessment.application_review.assessmentRevision).toBe(2);expect(after.application.baseline).toEqual(before.application.baseline);expect(after.assessment.history).toHaveLength(before.assessment.history.length+1);expect(after.shortlist.status).toBe('not_retained');await page.reload();await expect(page.getByText('Human assessment · revision 2',{exact:true})).toBeVisible();
});

test('T09 lost submission response reuses the exact persisted idempotency receipt after reload',async({page:candidate,request})=>{
  await seedTask(request);await start(candidate);await candidate.getByLabel('Executive summary').fill('Lost-response receipt test.');const posts:{key:string;body:string|null}[]=[];let lost=false;
  await candidate.route('**/api/demo/submission',async route=>{posts.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});if(!lost){lost=true;await route.fetch();await route.abort();}else await route.continue();});
  await candidate.getByRole('button',{name:'Submit V1',exact:true}).click();await candidate.getByRole('button',{name:'Confirm V1 submission',exact:true}).click();await expect(candidate.getByRole('dialog').getByRole('button',{name:'Retry original action',exact:true})).toBeVisible();await candidate.reload();await candidate.getByRole('button',{name:'Retry original action',exact:true}).click();await expect(candidate.getByRole('button',{name:'Retry original action',exact:true})).toHaveCount(0);expect(posts).toHaveLength(2);expect(posts[0]).toEqual(posts[1]);expect((await read(request)).versions).toHaveLength(1);
});

test('T10 server reset makes an old-session submission stale and leaves new case empty',async({page:candidate,request})=>{
  await seedTask(request);await start(candidate);await candidate.getByLabel('Executive summary').fill('OLD-SESSION-DRAFT');await reset(request);await candidate.getByRole('button',{name:'Submit V1',exact:true}).click();await candidate.getByRole('button',{name:'Confirm V1 submission',exact:true}).click();await expect(candidate.getByRole('alert').first()).toContainText('STALE_SESSION');expect((await read(request)).submission).toBeNull();await nav(candidate,'My task');await expect(candidate.getByRole('heading',{name:'No supplementary task requested',exact:true})).toBeVisible();await expect(candidate.getByText('OLD-SESSION-DRAFT',{exact:true})).toHaveCount(0);
});

test('T11 stale assessment revision is rejected and preserves the second reviewer form',async({page,context,request})=>{
  const other=await context.newPage();for(const p of [page,other]) {await open(p,'hr','alex-chen','evidence');await p.getByRole('button',{name:'Edit human assessment',exact:true}).click();await p.getByLabel('Assessment operator label').fill('Synthetic reviewer');}
  await page.getByLabel('Judgment reason').fill('First reviewer saved decision.');await page.getByRole('button',{name:'Save assessment revision',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  await other.getByLabel('Judgment reason').fill('KEEP SECOND REVIEWER INPUT');await other.getByRole('button',{name:'Save assessment revision',exact:true}).click();await expect(other.getByRole('dialog')).toBeVisible();await expect(other.getByLabel('Judgment reason')).toHaveValue('KEEP SECOND REVIEWER INPUT');await expect(other.getByRole('alert').first()).toContainText('ASSESSMENT_CONFLICT');expect((await read(request)).assessment.application_review.assessmentRevision).toBe(2);
});

test('T12 unavailable service keeps local draft and never substitutes preview data',async({page:candidate,request})=>{
  await seedTask(request);await start(candidate);await candidate.getByLabel('Executive summary').fill('KEEP-API3-DRAFT');await candidate.route('**/api/demo?**',route=>route.abort());await candidate.getByRole('button',{name:'Refresh shared case',exact:true}).click();await expect(candidate.getByRole('alert').first()).toContainText('CONNECTION_UNCERTAIN');await expect(candidate.getByLabel('Executive summary')).toHaveValue('KEEP-API3-DRAFT');await expect(candidate.getByText('Frontend mock · synthetic materials and illustrative marks',{exact:true})).toHaveCount(0);await candidate.unroute('**/api/demo?**');await refresh(candidate);await submit(candidate,request,'alex-chen',1,'Recovered real API draft.');
});

test('T13 a slow previous candidate response never becomes the newly selected identity',async({page})=>{
  await open(page,'candidate');await page.route('**/api/demo?candidateId=maya-patel',async route=>{const r=await route.fetch();await new Promise(r=>setTimeout(r,800));await route.fulfill({response:r});});
  await page.getByLabel('Current candidate').selectOption('maya-patel');await page.getByLabel('Current candidate').selectOption('sam-taylor');await expect(page.getByRole('heading',{name:'Sam Taylor',exact:true})).toBeVisible();await page.waitForTimeout(1000);await expect(page.getByRole('heading',{name:'Sam Taylor',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Maya Patel',exact:true})).toHaveCount(0);
});

test('T14 administrator reset CLI clears four test cases without placing its token in either browser',async({page,request})=>{
  for(const id of people)await seedTask(request,id,'sql');await open(page,'candidate');const before=await read(request);const cli=fileURLToPath(new URL('../../backend/scripts/reset.mjs',import.meta.url));const {stdout}=await promisify(execFile)(process.execPath,[cli],{env:{PATH:process.env.PATH,BASE_URL:backend,DEMO_ADMIN_TOKEN:token}});expect(JSON.parse(stdout).candidatesReset).toBe(4);await refresh(page);expect((await read(request)).sessionId).not.toBe(before.sessionId);expect(await page.evaluate(()=>JSON.stringify(localStorage)+document.body.innerText)).not.toContain(token);
});

test('T15 temporary SQLite survives service close/reopen and both windows read the saved snapshot',async({page:candidate,context,request})=>{
  await seedTask(request);const before=await seedSubmission(request,'alex-chen','PERSISTED-API3-SNAPSHOT');await restart();const after=await read(request);expect(after).toEqual(before);const hr=await context.newPage();await open(candidate,'candidate','alex-chen','history');await open(hr,'hr','alex-chen','tasks');await expect(candidate.getByText('PERSISTED-API3-SNAPSHOT',{exact:true}).first()).toBeVisible();await expect(hr.getByText('PERSISTED-API3-SNAPSHOT',{exact:true}).first()).toBeVisible();
});

test('T16 candidate drafts survive reload but are isolated by identity and task session',async({page,request})=>{
  await seedTask(request);await seedTask(request,'maya-patel','sql');await start(page);await page.getByLabel('Executive summary').fill('ALEX-ONLY-DRAFT');await page.getByLabel('Current candidate').selectOption('maya-patel');await nav(page,'My task');await page.getByRole('button',{name:'Start V1 draft',exact:true}).click();await expect(page.getByLabel('Executive summary')).toHaveValue('');await page.getByLabel('Executive summary').fill('MAYA-ONLY-DRAFT');await page.reload();await expect(page.getByLabel('Executive summary')).toHaveValue('MAYA-ONLY-DRAFT');await page.getByLabel('Current candidate').selectOption('alex-chen');await expect(page.getByLabel('Executive summary')).toHaveValue('ALEX-ONLY-DRAFT');expect((await read(request)).submission).toBeNull();
});

test('T08 shortlist persists independently, turns stale on new work, and preserves all human actions',async({page,request})=>{
  await open(page,'hr','alex-chen','shortlist');
  async function decide(button:string,reason:string) {await page.getByRole('button',{name:button,exact:true}).click();await page.getByLabel('Human shortlist reason').fill(reason);await page.getByLabel('Shortlist operator label').fill('Synthetic QA reviewer');await page.getByRole('button',{name:'Save shortlist decision',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
  await decide('Retain candidate','Retain original application for discussion.');expect((await read(request)).shortlist.status).toBe('retained');
  await seedTask(request);await seedSubmission(request);await refresh(page);await expect(page.locator('section[data-candidate="alex-chen"]')).toContainText('Reconfirmation needed');
  await decide('Reconfirm with current basis','Explicitly review the new work basis.');const reconfirmed=await read(request);expect(reconfirmed.shortlist.status).toBe('retained');expect(reconfirmed.shortlist.basis.stage).toBe('task_v1');expect(reconfirmed.review).toBeNull();expect(reconfirmed.assessment.task_v1).toBeNull();
  await page.reload();await decide('Remove from retained','Continue evidence discussion before retaining.');const removed=await read(request);expect(removed.shortlist.status).toBe('not_retained');expect(removed.shortlist.history.map((h:any)=>h.action)).toEqual(['retain','reconfirm','remove']);expect(removed.submission).toEqual(reconfirmed.submission);await nav(page,'Compare candidates');await expect(page.locator('tbody tr')).toHaveCount(4);
});

test('T17 real resources, row-to-card, dark mode and mobile navigation retain the existing UI',async({page,request},info)=>{
  await seedTask(request);await start(page);await expect(page.locator('.eb-metrics').getByText('1,180,000',{exact:true})).toBeVisible();await expect(page.locator('.eb-metrics').getByText('30,680',{exact:true})).toBeVisible();await expect(page.getByText('31,200',{exact:true})).toHaveCount(0);
  await page.getByLabel('Find a resource',{exact:true}).fill('website');await page.getByRole('button',{name:'website_traffic.csv',exact:true}).click();await page.getByLabel('Filter resource rows').fill('Paid Search');await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(2);await page.getByRole('dialog').getByRole('button',{name:/Create card from row/}).first().click();await expect(page.getByLabel('Evidence source',{exact:true})).toHaveValue('website_traffic.csv');await page.getByLabel('Observation or idea').fill('A bounded data observation');await page.getByRole('button',{name:'Save card',exact:true}).click();await expect(page.locator('.eb-board')).toContainText('A bounded data observation');
  await page.getByRole('switch',{name:'Night mode'}).click();await page.reload();await expect(page.getByRole('switch',{name:'Night mode'})).toBeChecked();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('dialog').getByRole('button',{name:'My task',exact:true}).click();await expect(page.getByRole('button',{name:'Open navigation'})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('api3-candidate-mobile-dark.png'),fullPage:true});
});

test('T18 in-flight analysis does not block human review and its late result never reopens the closed version',async({page:hr,request})=>{
  await seedTask(request);await seedSubmission(request,'alex-chen','TEST_DELAY: bounded evidence, awaiting human review.');await open(hr,'hr','alex-chen','tasks');const late=hr.waitForResponse(r=>r.url().endsWith('/api/demo/analysis')&&r.request().method()==='POST');await hr.getByRole('button',{name:'Run evidence analysis',exact:true}).click();await expect.poll(async()=>(await read(request)).analysis.status).toBe('running');await review(hr,'Confirm evidence','Human review may finish while extraction is pending.');expect((await(await late).json()).error.code).toBe('STALE_ANALYSIS');const final=await read(request);expect(final.workflow.isTerminal).toBe(true);expect(final.analysis.status).toBe('failed');expect(final.analysis.errorCode).toBe('AI_REVIEW_CLOSED');expect(final.analysis.result).toBeNull();await refresh(hr);await expect(hr.getByRole('button',{name:'Needs More Evidence',exact:true})).toHaveCount(0);await expect(hr.getByText('Human review may finish while extraction is pending.',{exact:true})).toBeVisible();
});

test('T19 SQL task marks are server-calculated, application reuse is explicit, and V2 starts unassessed',async({page,request})=>{
  await seedTask(request,'maya-patel','sql');const before=await seedSubmission(request,'maya-patel','😀 SQL checks: unique order IDs, period boundaries and denominator reconciliation.');await open(page,'hr','maya-patel','evidence');await page.getByLabel('Assessment stage').selectOption('task_v1');await page.getByRole('button',{name:'Edit human assessment',exact:true}).click();
  for(const criterion of ['S1','S2','S3']) {await page.getByLabel('Edit criterion').selectOption(criterion);await page.getByLabel('Human mark').selectOption('2');for(const label of ['Judgment reason','Support / checked scope','Missing evidence / counter-evidence','Uncertainty','Next step'])await page.getByLabel(label,{exact:true}).fill(`${criterion}: bounded synthetic review of visible original SQL text.`);await page.getByLabel('Exact source quotation').fill(before.submission.summary);await page.getByRole('button',{name:'Add source quotation',exact:true}).click();}
  await page.getByLabel('Explicitly reuse application assessment').check();await page.getByLabel('Assessment operator label').fill('Synthetic task reviewer');await page.getByRole('button',{name:'Save assessment revision',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  const assessed=await read(request,'maya-patel');expect(assessed.assessment.task_v1.score.skills.find((s:any)=>s.requirementId==='sql').percentage).toBe(50);expect(assessed.assessment.task_v1.reusedItems).toHaveLength(7);expect(assessed.assessment.application_review).toEqual(before.assessment.application_review);expect(assessed.review).toBeNull();expect(assessed.shortlist.status).toBe('not_retained');
  await post(request,'/review',{...binding(assessed),submissionId:assessed.submission.submissionId,contentFingerprint:assessed.submission.contentFingerprint,decision:'needs_more_evidence',comment:'Clarify the join boundary.'});await seedSubmission(request,'maya-patel','V2 adds a bounded join check.');await refresh(page);await page.getByLabel('Assessment stage').selectOption('task_v2');expect((await read(request,'maya-patel')).assessment.task_v2).toBeNull();await expect(page.locator('.r5-criterion .r5-mark').filter({hasText:'Not assessed'})).toHaveCount(10);await page.getByLabel('Assessment stage').selectOption('task_v1');await expect(page.getByRole('button',{name:'Edit human assessment',exact:true})).toBeDisabled();
});

test('T20 failed analysis exposes its status and leaves original work and manual review usable',async({page,request})=>{
  await seedTask(request);const submitted=await seedSubmission(request,'alex-chen','TEST_DISABLED: limited work still open for human review.');await open(page,'hr','alex-chen','tasks');await page.getByRole('button',{name:'Run evidence analysis',exact:true}).click();await expect(page.getByRole('alert').first()).toContainText('AI_DISABLED');await review(page,'Evidence Still Insufficient','The visible work still leaves an evidence gap.');const final=await read(request);expect(final.submission).toEqual(submitted.submission);expect(final.analysis.status).toBe('failed');expect(final.workflow.isTerminal).toBe(true);expect(final.assessment.task_v1).toBeNull();
});

test('T21 a stale V1 review form keeps its comment after another client advances to V2',async({page,request})=>{
  await seedTask(request);const one=await seedSubmission(request);await open(page,'hr','alex-chen','tasks');await page.getByRole('button',{name:'Confirm evidence',exact:true}).click();await page.getByLabel('Public review comment').fill('KEEP THIS V1 REVIEW COMMENT');
  await post(request,'/review',{...binding(one),submissionId:one.submission.submissionId,contentFingerprint:one.submission.contentFingerprint,decision:'needs_more_evidence',comment:'Another reviewer opened the bounded V2.'});await seedSubmission(request,'alex-chen','A new V2 from another window.');
  const conflict=page.waitForResponse(r=>r.url().endsWith('/api/demo/review')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save evidence review',exact:true}).click();expect((await conflict).status()).toBe(409);await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByLabel('Public review comment')).toHaveValue('KEEP THIS V1 REVIEW COMMENT');const current=await read(request);expect(current.currentSubmissionVersion).toBe(2);expect(current.review).toBeNull();expect(current.versions[0].review.decision).toBe('needs_more_evidence');
});

test('T22 confirmed save followed by GET failure is not reported as a fresh view or duplicated',async({page,request})=>{
  await open(page,'hr','alex-chen','evidence');await page.getByRole('button',{name:'Edit human assessment',exact:true}).click();await page.getByLabel('Judgment reason').fill('SAVED BUT VIEW REFRESH FAILED');await page.getByLabel('Assessment operator label').fill('Synthetic reviewer');await page.route('**/api/demo?**',route=>route.abort());await page.getByRole('button',{name:'Save assessment revision',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByLabel('Judgment reason')).toHaveValue('SAVED BUT VIEW REFRESH FAILED');await expect(page.getByRole('alert').first()).toContainText('CONNECTION_UNCERTAIN');await expect(page.getByText(/Saved on the shared service.*Refresh is still needed/)).toBeVisible();expect((await read(request)).assessment.application_review.assessmentRevision).toBe(2);await page.unroute('**/api/demo?**');await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await refresh(page);await expect(page.getByText('Human assessment · revision 2',{exact:true})).toBeVisible();expect((await read(request)).assessment.application_review.assessmentRevision).toBe(2);
});
