import React, { useState } from 'react';
import initial from '../../../docs/backend/examples/initial.response.json';
import type { Demo, Finding } from '../api-types';
import { emptyDraft, event, sections } from '../api';
import { Dialog, Heading, ProcessTimeline, ResourceList } from '../api-ui';
import { CardEditor } from '../card-editor';
import { templates } from './fixtures';
import { previewSubmissionIssues } from './work-validation';
import { draftKey, nextVersion, skillName, type Profile, type Source, type Task, type WorkDraft } from './model';
import { submitWork, type PreviewController } from './preview-store';
import { SourceDialog } from './assessment-ui';
import { ReviewNote, WorkSnapshot } from './hr-preview';

const canonical=initial.data as Demo;
const {current, previous, change}=canonical.dataset.metrics;
type Props={profile:Profile;page:string;go:(page:string)=>void;controller:PreviewController};
export function CandidatePreview({profile,page,go,controller}:Props) {
  const [source,setSource]=useState<Source|null>(null),[confirm,setConfirm]=useState(false),[submitError,setSubmitError]=useState('');
  const task=controller.state.tasks[profile.id], version=nextVersion(task);
  const key=task&&version?draftKey(controller.state,profile.id,task,version):'';
  const draft=controller.state.workDrafts[key]??emptyDraft(), latest=task?.versions.at(-1);
  const update=(fn:(d:WorkDraft)=>WorkDraft)=>controller.draft(profile.id,d=>({...fn(d),savedAt:new Date().toISOString()}));
  const record=(title:string)=>{if(draft.started&&version)update(d=>({...d,events:[...d.events,event(title)].slice(-100)}));};
  const start=(copy=false)=>{update(d=>({...d,started:true,summary:copy&&latest?latest.summary:d.summary,findings:copy&&latest?latest.findings.map(f=>({...f})):d.findings,events:[event(`Started V${version} draft`,copy?'Public prior work explicitly copied. Private notes and the old snapshot were not copied.':'Started a blank version.')]}));go('workspace');};
  const submit=async()=>{
    if(!task||!version)return;
    const publicDraft={...draft,events:[...draft.events,event(`Submitted V${version} work sample`)].slice(-100)};
    const issues=previewSubmissionIssues(profile,task,publicDraft);
    if(issues.length){setSubmitError(issues.join(' '));return;}
    if(await controller.run(s=>submitWork(s,profile,publicDraft),`${profile.name}: V${version} snapshot saved in this local mock. No backend submission was sent.`)){setConfirm(false);go('history');}
  };
  return <>
    {page==='application'&&<><Heading eyebrow="HarbourCart · Junior Data Analyst" title="Your application materials"/><div className="r5-two"><section className="eb-panel"><h2>{profile.name}</h2><p>{profile.subtitle}</p><p>Preset synthetic samples. No file upload, parsing or actual account login has taken place.</p>{profile.sources.map(s=><button className="r5-source-card" key={s.id} onClick={()=>setSource(s)}><strong>{s.name}</strong><small>View this person’s preset material ↗</small></button>)}</section><section className="eb-panel"><h2>Only supplement what is needed</h2><p>{task?`A ${skillName[task.skill]} task has been requested.`:'No supplementary task has been requested. Your application can be compared using the available evidence.'}</p><p>Receiving a task is not rejection. Having no task is not an offer.</p><button className="eb-action primary" onClick={()=>go('tasks')}>View task status</button></section></div></>}
    {page==='tasks'&&<><Heading title="Your targeted task"/>{!task?<section className="eb-panel"><h2>No supplementary task requested</h2><p>Wait for a specific request from the hiring team. A candidate with sufficient material can be compared directly.</p></section>:<><section className="eb-panel"><span className="r5-state">{task.status.replaceAll('_',' ')}</span><h2>{templates[task.skill].title}</h2><p><strong>Target:</strong> {skillName[task.skill]}</p><p><strong>Why this task:</strong> {task.reason}</p><p className="eb-preserve">{task.instructions}</p><p>20 minutes suggested · No enforced deadline · Shared synthetic resources</p>{version?<div className="eb-actions">{draft.started?<button className="eb-action primary" onClick={()=>go('workspace')}>Continue V{version} draft</button>:<><button className="eb-action primary" disabled={controller.busy} onClick={()=>start()}>Start V{version} draft</button>{version===2&&<button className="eb-action" disabled={controller.busy} onClick={()=>start(true)}>Copy V1 public work into V2</button>}</>}</div>:<p>{task.status==='closed'?'Evidence review is complete. No further submission is available.':'Your public snapshot is awaiting human review. V2 is not yet available.'}</p>}</section>{latest&&<ReviewNote work={latest}/>}<section className="eb-panel"><h2>Task-provided resources</h2><p>Shared business data, not evidence authored by the candidate.</p><ResourceList resources={canonical.dataset.resources}/></section></>}</>}
    {page==='workspace'&&<><Heading eyebrow={task?`${skillName[task.skill]} · V${version??latest?.version} draft`:undefined} title="Investigation workspace"/>{!task||!version||!draft.started?<section className="eb-panel"><p>{task?.status==='closed'?'This task is closed. Your previous versions remain available.':'Open the task and start an authorised draft to edit.'}</p><button className="eb-action" onClick={()=>go(task?.versions.length?'history':'tasks')}>View task and work</button></section>:<>
      <section className="eb-panel"><h2>{templates[task.skill].title}</h2><p className="eb-preserve">{task.instructions}</p><p className="r5-notice">{templates[task.skill].hint}</p><small>{draft.savedAt?`Local draft updated ${new Date(draft.savedAt).toLocaleString()}`:'Local draft'} · {profile.name} · V{version}</small>{version===2&&<p>V1 stays unchanged. This draft answers the specific feedback below.</p>}</section>
      {version===2&&latest&&<ReviewNote work={latest}/>}<Investigation profile={profile} task={task} draft={draft} update={update} record={record} disabled={controller.busy}/>
      <section className="eb-panel"><h2>Public work sample</h2><label className="eb-field">Executive summary<textarea aria-label="Executive summary" maxLength={8000} disabled={controller.busy} value={draft.summary} onChange={e=>update(d=>({...d,summary:e.target.value}))}/></label><small>{draft.summary.length}/8,000 characters · {draft.findings.length}/40 cards · {draft.events.length}/100 reported events</small><p>Weak or incomplete work may still be submitted. Private notes are excluded. Only saved public snapshots can be exported.</p><button className="eb-action primary" disabled={controller.busy} onClick={()=>{setSubmitError('');setConfirm(true);}}>Submit V{version} in preview</button></section>
    </>}</>}
    {page==='history'&&<><Heading title="Work and public feedback"/>{task?.versions.length?<History key={task.versions.at(-1)!.id} profile={profile} task={task}/>:<section className="eb-panel"><h2>No formal work snapshot yet</h2><p>Your drafts are separate from submitted work.</p><button className="eb-action" onClick={()=>go('tasks')}>View task status</button></section>}{version===2&&<button className="eb-action primary" onClick={()=>go('tasks')}>Read feedback and prepare V2</button>}{task?.status==='closed'&&<p className="r5-notice">Task closed · no V3. Evidence confirmation is not a hiring decision.</p>}</>}
    {source&&<SourceDialog profile={profile} source={source} close={()=>setSource(null)}/>}
    {confirm&&task&&version&&<Dialog title={`Submit V${version} for ${profile.name}?`} close={()=>setConfirm(false)}><p>This creates an immutable public snapshot in the local preview. Private notes stay in the draft store and are excluded from the snapshot and exports.</p>{previewSubmissionIssues(profile,task,draft).map(issue=><p className="eb-feedback" key={issue}>{issue}</p>)}{submitError&&<p role="alert">{submitError}</p>}{controller.error&&<p role="alert">{controller.error}</p>}<button className="eb-action primary" disabled={controller.busy||previewSubmissionIssues(profile,task,draft).length>0} onClick={()=>void submit()}>{controller.busy?'Saving locally…':`Confirm V${version} preview submission`}</button></Dialog>}
  </>;
}
function Investigation({profile,task,draft,update,record,disabled}:{profile:Profile;task:Task;draft:WorkDraft;update:(fn:(d:WorkDraft)=>WorkDraft)=>void;record:(title:string)=>void;disabled:boolean}) {
  const [tab,setTab]=useState(task.skill==='BPS'?'Explore':task.skill==='SQL'?'SQL':'Data analysis'),[editing,setEditing]=useState<Finding|null>(null);
  const tabs=['Explore','SQL','Data analysis','Private notebook'];
  return <div className="eb-workbench r5-workbench"><section className="eb-panel"><h2>Data & resources</h2><small>Task-provided · {canonical.dataset.version}</small><ResourceList resources={canonical.dataset.resources} onEvent={record}/></section><section className="eb-panel"><div className="eb-tabs" role="tablist" aria-label="Investigation tools">{tabs.map(t=><button className="eb-action" role="tab" key={t} aria-selected={tab===t} onClick={()=>{setTab(t);record(`Opened ${t}`);}}>{t}</button>)}</div>
    {tab==='Explore'&&<><h2>Conversion comparison</h2><p>Previous four weeks → Last four weeks</p><div className="r5-three"><div><strong>{current.sessions.toLocaleString()}</strong><small>current sessions · {change.trafficPct > 0 ? '+' : ''}{change.trafficPct.toFixed(1)}%</small></div><div><strong>{current.orders.toLocaleString()}</strong><small>current orders</small></div><div><strong>{current.conversionPct}%</strong><small>conversion · previously {previous.conversionPct}%</small></div></div><div className="eb-table-scroll"><table><thead><tr><th>Channel</th><th>Sessions</th><th>Orders</th><th>Conversion</th></tr></thead><tbody>{canonical.dataset.channels.map(c=><tr key={c.id}><td>{c.channel}</td><td>{c.traffic.toLocaleString()}</td><td>{c.orders.toLocaleString()}</td><td>{c.conversion.toFixed(2)}%</td></tr>)}</tbody></table></div><p className="eb-muted">Aggregates describe patterns; they do not establish campaign-level causes.</p></>}
    {tab==='SQL'&&<><h2>SQL · static review</h2><p>Put your query or code snippet in a card’s reasoning field, then explain the grain, time boundaries, joins and checks.</p><pre className="eb-code">{`-- Describe the intended grain first.\n-- Use the resource columns and explicit period bounds.\n-- Explain a validation check and a remaining limitation.`}</pre><p>No query is run here. Do not claim execution passed without execution evidence.</p></>}
    {tab==='Data analysis'&&<><h2>Show the calculation</h2><p>Define the metric, denominator and unit. Make your comparison reviewable, then state the limitation.</p><div className="r5-formula">Conversion = orders ÷ sessions × 100<br/>Current: {current.orders.toLocaleString()} ÷ {current.sessions.toLocaleString()} × 100 = {current.conversionPct}%<br/>Previous: {previous.orders.toLocaleString()} ÷ {previous.sessions.toLocaleString()} × 100 = {previous.conversionPct}%</div><p className="eb-muted">This task-provided worked example is not personal evidence. Explain your own checks and interpretation in the investigation cards.</p></>}
    {tab==='Private notebook'&&<><h2>{profile.name} · private working notes</h2><p>Local draft only; excluded from HR views, public snapshots and exports.</p><label className="eb-field">Private notes<textarea aria-label="Private notes" disabled={disabled} value={draft.notes} onChange={e=>update(d=>({...d,notes:e.target.value}))}/></label></>}
    </section><section className="eb-panel eb-board"><h2>Investigation board</h2><p>{templates[task.skill].hint}</p>{sections.map(section=><section key={section}><div className="eb-board-heading"><h3>{section}</h3><button className="eb-action" aria-label={`Add ${section}`} disabled={disabled||draft.findings.length>=40} onClick={()=>setEditing({id:crypto.randomUUID(),section,title:'',detail:'',source:'',confidence:'Medium'})}>+</button></div>{draft.findings.filter(f=>f.section===section).map(f=><article key={f.id} className="eb-finding"><h4>{f.title}</h4><p className="eb-preserve">{f.detail}</p><small>{f.source||'No source'} · Self-confidence {f.confidence}</small><button className="eb-action" aria-label={`Edit ${f.title}`} disabled={disabled} onClick={()=>setEditing(f)}>Edit</button></article>)}{!draft.findings.some(f=>f.section===section)&&<p className="eb-muted">No cards yet. This section is optional for submission.</p>}</section>)}</section>
    {editing&&<CardEditor key={editing.id} finding={editing} resources={canonical.dataset.resources} editable={!disabled} close={()=>setEditing(null)} save={finding=>{update(d=>({...d,findings:d.findings.some(f=>f.id===finding.id)?d.findings.map(f=>f.id===finding.id?finding:f):[...d.findings,finding],events:[...d.events,event(`Saved ${finding.section}`,finding.title)].slice(-100)}));setEditing(null);}} remove={()=>{update(d=>({...d,findings:d.findings.filter(f=>f.id!==editing.id)}));setEditing(null);}}/>}
  </div>;
}
function History({profile,task}:{profile:Profile;task:Task}) {
  const [selected,setSelected]=useState(task.versions.at(-1)!.version), work=task.versions.find(v=>v.version===selected)!;
  return <><label className="eb-field">Submission version<select aria-label="Submission version" value={selected} onChange={e=>setSelected(Number(e.target.value) as 1|2)}>{task.versions.map(v=><option value={v.version} key={v.id}>V{v.version}{v.id===task.versions.at(-1)?.id?' · current':' · history'}</option>)}</select></label><ReviewNote work={work}/><WorkSnapshot profile={profile} work={work}/><ProcessTimeline events={work.processEvidence}/></>;
}
