import React, { useState } from 'react';
import { Dialog, Heading, ProcessTimeline } from '../api-ui';
import { download, workMarkdown } from '../api';
import { criteria, profiles, templates } from './fixtures';
import { AssessmentPanel, Rubric } from './assessment-ui';
import { currentBasis, formatPercent, needsReconfirmation, skillName, skills, sortedProfiles, stageName, type Profile, type Review, type Skill, type Task, type WorkVersion } from './model';
import { retainCandidate, reviewWork, sendTask, type PreviewController } from './preview-store';

type Props={profile:Profile;page:string;go:(page:string)=>void;select:(id:string,page?:string)=>void;controller:PreviewController};
export function HRPreview({profile,page,go,select,controller}:Props) {
  const [rubric,setRubric]=useState(false), [retention,setRetention]=useState<{profile:Profile;keep:boolean}|null>(null);
  const shortlist=(p:Profile,keep=true)=>setRetention({profile:p,keep});
  return <>
    {page==='company'&&<><Heading eyebrow="A concrete SME · Synthetic company" title="Hire for the work ahead"><button className="eb-action" onClick={()=>setRubric(true)}>View ten assessment standards</button></Heading><section className="eb-panel r5-company"><div><span className="r5-avatar">HC</span><h2>HarbourCart Pty Ltd</h2><p>Sydney ecommerce accessories & stationery · Approximately 25 people · Partly outsourced fulfilment.</p><div className="r5-meta"><span>No dedicated hiring team</span><span>Company is the customer</span><span>Synthetic SME context</span></div></div><aside><small>OPEN ROLE</small><h2>Junior Data Analyst</h2><p>The operations lead reviews evidence. The founder approves the budget. Hiring remains a human decision.</p></aside></section><div className="r5-three">{[['01','Reconcile the numbers','Check metrics and reporting before the team makes a decision.'],['02','Investigate the change','Compare meaningful periods and segments, and identify what remains unknown.'],['03','Recommend a testable action','Propose a feasible next step and explain how to validate it.']].map(([n,title,text])=><section className="eb-panel" key={n}><span className="r5-step">{n}</span><h2>{title}</h2><p>{text}</p></section>)}</div><section className="eb-panel"><h2>One shared standard, ten reviewable judgments</h2><div className="r5-three">{skills.map(s=><div key={s}><h3>{skillName[s]} · {s==='BPS'?40:30}%</h3><p>{criteria.filter(c=>c.skill===s).map(c=>c.id).join(' · ')} · 10 points each</p></div>)}</div><p>Small team. Incomplete information. Evidence is needed before expanding ad spend. These constraints shape the role, rather than changing for each candidate.</p><button className="eb-action primary" onClick={()=>go('comparison')}>Compare four candidates</button></section></>}
    {page==='comparison'&&<Comparison controller={controller} select={select} shortlist={shortlist} rubric={()=>setRubric(true)}/>}
    {page==='evidence'&&<><Heading eyebrow="Job evidence match · Review the basis" title={`${profile.name} · evidence & marks`}><button className="eb-action" onClick={()=>setRubric(true)}>View ten assessment standards</button></Heading><AssessmentPanel profile={profile} controller={controller}/><div className="eb-actions"><button className="eb-action" onClick={()=>go('tasks')}>Explore a targeted task</button><button className="eb-action primary" onClick={()=>shortlist(profile)}>Human retain decision</button></div></>}
    {page==='tasks'&&<><Heading eyebrow="Only ask for the missing evidence" title="Targeted task"/>{controller.state.tasks[profile.id]?<TaskReview key={controller.state.tasks[profile.id]?.versions.at(-1)?.id??'sent'} profile={profile} task={controller.state.tasks[profile.id]!} controller={controller}/>:<TaskComposer profile={profile} controller={controller}/>}</>}
    {page==='shortlist'&&<><Heading eyebrow="Human selection · independent of marks" title="Retained for further comparison"><button className="eb-action" onClick={()=>go('comparison')}>View all four candidates</button></Heading><p>Retaining is not hiring. Removing is not rejecting an application. Any of the four candidates can be retained; there is no automatic top-three limit.</p><div className="r5-two">{profiles.map(p=>{
      const record=controller.state.shortlist[p.id],stale=needsReconfirmation(record,currentBasis(p,controller.state.tasks[p.id]));
      return <section className="eb-panel" key={p.id}><div className="eb-heading"><h2>{p.name}</h2><span className={`r5-state ${stale?'is-warning':''}`}>{stale?'Reconfirmation needed':record?.retained?'Retained':'Not retained'}</span></div><p>{record?.reason??'No human retain decision yet.'}</p>{record&&<details open={stale}><summary>Decision basis</summary><p>{stageName[record.basis.stage]} · {record.basis.assessmentRevision===null?'Not assessed':`Assessment revision ${record.basis.assessmentRevision}`} · {record.basis.rubricVersion}</p><small>{record.basis.snapshotId}</small><p>{new Date(record.at).toLocaleString()}</p></details>}{stale&&<p className="eb-feedback">New work is available. The original reason and basis stay visible until you explicitly reconfirm.</p>}<div className="eb-actions"><button className="eb-action" onClick={()=>select(p.id,'evidence')}>Inspect evidence</button><button className="eb-action primary" onClick={()=>shortlist(p)}>{stale?'Reconfirm with current basis':record?.retained?'Update retain reason':'Retain candidate'}</button>{record?.retained&&<button className="eb-action" onClick={()=>shortlist(p,false)}>Remove from retained</button>}</div></section>;
    })}</div></>}
    {rubric&&<Rubric close={()=>setRubric(false)}/>}
    {retention&&<RetentionDialog key={retention.profile.id} {...retention} controller={controller} close={()=>setRetention(null)}/>}
  </>;
}
function Comparison({controller,select,shortlist,rubric}:{controller:PreviewController;select:Props['select'];shortlist:(p:Profile)=>void;rubric:()=>void}) {
  const [sort,setSort]=useState<'default'|'overall'|Skill>('default'),[limit,setLimit]=useState(false);
  const sorted=sortedProfiles(profiles,sort),visible=limit?sorted.slice(0,3):sorted;
  const complete=profiles.filter(p=>p.assessment.results.overall!==null).length;
  const retained=profiles.filter(p=>controller.state.shortlist[p.id]?.retained).length;
  const selectedValue=(p:Profile)=>sort==='default'?null:sort==='overall'?p.assessment.results.overall:p.assessment.results.skills[sort];
  return <><Heading eyebrow="HarbourCart · Junior Data Analyst" title="Different evidence. One shared standard."><button className="eb-action" onClick={rubric}>View ten assessment standards</button></Heading><p className="r5-intro">Understand the support, the gaps and the exceptions before deciding who to discuss further.</p><div className="r5-three r5-summary"><div><strong>4</strong><span>synthetic candidate profiles</span></div><div><strong>{complete}/4</strong><span>complete application fixtures</span></div><div><strong>{retained}</strong><span>human retain choices in this preview</span></div></div>
    <section className="eb-panel r5-comparison"><div className="r5-table-toolbar"><div><h2>Application evidence comparison</h2><small>Same role · {profiles[0].assessment.rubricVersion} · Application materials only</small></div><label>Sort by<select aria-label="Compare sort" value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="default">Display order · not a recommendation</option><option value="overall">Overall · complete assessments only</option>{skills.map(s=><option key={s} value={s}>{skillName[s]} · complete skill only</option>)}</select></label></div><p className="eb-muted">Illustrative frontend assessment fixtures, not backend-reviewed scores. Different projects limit comparability. Task V1/V2 work is shown separately in each profile.</p>
      <div className="eb-table-scroll"><table className="r5-compare-table"><thead><tr><th>Candidate / evidence</th><th>SQL</th><th>DA</th><th>BPS</th><th>Overall</th><th>Coverage</th><th>Human shortlist</th><th>Actions</th></tr></thead><tbody>{visible.map(p=>{
        const scores=p.assessment.results,record=controller.state.shortlist[p.id],stale=needsReconfirmation(record,currentBasis(p,controller.state.tasks[p.id]));
        const val=selectedValue(p),tied=val!==null&&profiles.filter(other=>selectedValue(other)===val).length>1;
        return <tr key={p.id} data-candidate={p.id}><td><button className="r5-person-link" onClick={()=>select(p.id,'evidence')}><span className="r5-avatar">{p.initials}</span><strong>{p.name}</strong></button><small>{p.strength}</small><small className="r5-gap">Question: {p.question}</small>{tied&&<span className="r5-state">Tied on selected skill</span>}</td>{skills.map(s=><td key={s}><SkillCell value={scores.skills[s]}/></td>)}<td><strong>{formatPercent(scores.overall)}</strong>{scores.overall===null&&<small>NE present · no overall %</small>}</td><td><strong>{scores.coverage}/10</strong><small>{scores.coverage*10}% evidence coverage</small><details><summary>Assessed points</summary>{scores.reviewedPoints}/100 accumulated · not scaled up</details></td><td><span className={`r5-state ${stale?'is-warning':''}`}>{stale?'Reconfirm':record?.retained?'Retained':'Not retained'}</span><small>Application · fixture revision 1</small>{controller.state.tasks[p.id]&&<small>Task: {controller.state.tasks[p.id]!.status.replaceAll('_',' ')}</small>}</td><td><div className="r5-row-actions"><button className="eb-action" aria-label={`Open ${p.name}`} onClick={()=>select(p.id,'evidence')}>View evidence</button><button className="eb-action" aria-label={`Retain ${p.name}`} onClick={()=>shortlist(p)}>Retain</button></div></td></tr>;
      })}</tbody></table></div><div className="r5-table-footer"><span>Showing {visible.length} / 4 · everyone remains available</span><button className="eb-action" onClick={()=>setLimit(!limit)}>{limit?'View all four':'Preview three-row view'}</button></div>
    </section><p className="eb-muted">NE means insufficient material, not zero. Missing scores appear after comparable complete results and are not assigned a rank. Percentages describe evidence against these standards, not hiring probability.</p></>;
}
function SkillCell({value}:{value:number|null}) {
  return <div className="r5-skill-cell"><strong>{formatPercent(value)}</strong>{value!==null?<span className="r5-score-track" aria-hidden="true"><i style={{width:`${value}%`}}/></span>:<small>NE · incomplete skill</small>}</div>;
}
function RetentionDialog({profile,keep,controller,close}:{profile:Profile;keep:boolean;controller:PreviewController;close:()=>void}) {
  const [reason,setReason]=useState(controller.state.shortlist[profile.id]?.reason??'');
  const basis=currentBasis(profile,controller.state.tasks[profile.id]);
  return <Dialog title={`${keep?'Retain':'Remove'} ${profile.name}`} close={close}><p>This is a local mock shortlist action, separate from evidence review and assessment. No applicant is hired, rejected or deleted.</p><div className="r5-formula"><strong>Basis you are choosing</strong><p>{stageName[basis.stage]} · {basis.assessmentRevision===null?'Target skill not assessed':`Assessment revision ${basis.assessmentRevision}`} · {basis.rubricVersion}</p><small>{basis.snapshotId}</small></div><label className="eb-field">Human shortlist reason<textarea aria-label="Human shortlist reason" maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{controller.error&&<p role="alert">{controller.error}</p>}<div className="eb-actions"><button className="eb-action primary" disabled={controller.busy||!reason.trim()} onClick={async()=>{if(await controller.run(s=>retainCandidate(s,profile,keep,reason),`${profile.name}: local shortlist ${keep?'retained / reconfirmed':'removed'}.`))close();}}>{controller.busy?'Saving locally…':'Save local shortlist decision'}</button><button className="eb-action" onClick={close}>Cancel</button></div></Dialog>;
}
function TaskComposer({profile,controller}:{profile:Profile;controller:PreviewController}) {
  const [skill,setSkill]=useState(profile.suggestedSkill),[instructions,setInstructions]=useState(templates[skill].instructions),[reason,setReason]=useState(profile.question);
  return <section className="eb-panel"><h2>Choose the gap, then the task</h2><p>All candidates can receive one SQL, DA or BPS task. Material that already answers the question does not require a task.</p><label className="eb-field">Target skill<select aria-label="Target skill" value={skill} onChange={e=>{const value=e.target.value as Skill;setSkill(value);setInstructions(templates[value].instructions);}}>{skills.map(s=><option key={s} value={s}>{skillName[s]}</option>)}</select></label><h3>{templates[skill].title}</h3><label className="eb-field">Evidence gap / task reason<textarea aria-label="Evidence gap / task reason" maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="eb-field">Candidate instructions<textarea aria-label="Candidate instructions" maxLength={4000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></label><p className="eb-muted">Fixed template · 20 minutes suggested · No deadline-based rejection. Target stays fixed after sending. No generated task or email is claimed.</p><button className="eb-action primary" disabled={controller.busy||!instructions.trim()||!reason.trim()} onClick={()=>void controller.run(s=>sendTask(s,profile,skill,instructions,reason),`${profile.name}: task sent within this browser mock. Switch Preview role to Candidate to continue.`)}>{controller.busy?'Saving locally…':'Send task in preview'}</button></section>;
}
export function WorkSnapshot({profile,work}:{profile:Profile;work:WorkVersion}) {
  return <section className="eb-panel"><div className="eb-heading"><div><h2>V{work.version} · public work snapshot</h2><small>{new Date(work.submittedAt).toLocaleString()} · immutable local mock</small></div><button className="eb-action" onClick={()=>download(`${profile.id}-v${work.version}-work.md`,workMarkdown(work),'text/markdown')}>Export V{work.version} public work</button></div><h3>Executive summary</h3><p className="eb-preserve">{work.summary}</p>{work.findings.map(f=><article className="eb-finding" key={f.id}><small>{f.section}</small><h3>{f.title}</h3><p className="eb-preserve">{f.detail}</p><small>Task resource: {f.source||'Not supplied'} · Self-reported confidence: {f.confidence}</small></article>)}</section>;
}
export function ReviewNote({work}:{work:WorkVersion}) {
  return work.review?<section className="eb-panel eb-review-note"><h3>V{work.version} · {work.review.decision==='confirm'?'Evidence confirmed':work.review.decision==='needs_more_evidence'?'More evidence requested':'Evidence still insufficient'}</h3><p className="eb-preserve">{work.review.comment}</p><small>Public human review · only the target skill · no automatic mark or shortlist decision</small></section>:<p className="eb-muted">V{work.version} is awaiting evidence review. No earlier review has been substituted.</p>;
}
function TaskReview({profile,task,controller}:{profile:Profile;task:Task;controller:PreviewController}) {
  const [selected,setSelected]=useState(task.versions.at(-1)?.version??1),[decision,setDecision]=useState<Review['decision']|null>(null),[comment,setComment]=useState('');
  const work=task.versions.find(v=>v.version===selected), current=work?.id===task.versions.at(-1)?.id;
  return <><section className="eb-panel"><div className="eb-heading"><h2>{templates[task.skill].title}</h2><span className="r5-state">{task.status.replaceAll('_',' ')}</span></div><p><strong>Target:</strong> {skillName[task.skill]} · <strong>Gap:</strong> {task.reason}</p><p className="eb-preserve">{task.instructions}</p><small>Fixed target · 20 minutes suggested · One V1 and at most one authorised V2</small></section>
    {!work?<section className="eb-panel"><h2>Waiting for {profile.name}’s work</h2><p>Use Preview role → Candidate to write a mock submission for this person. No prefilled answer is submitted automatically.</p></section>:<><label className="eb-field">Submission version<select aria-label="Submission version" value={selected} onChange={e=>{setSelected(Number(e.target.value) as 1|2);setDecision(null);setComment('');}}>{task.versions.map(v=><option key={v.id} value={v.version}>V{v.version}{v.id===task.versions.at(-1)?.id?' · current':' · history, read only'}</option>)}</select></label><ReviewNote work={work}/><WorkSnapshot profile={profile} work={work}/><ProcessTimeline events={work.processEvidence}/><section className="eb-panel"><h2>{skillName[task.skill]} observations</h2><p>Analysis is unavailable in this frontend mock. No model or five-dimension BPS result is substituted for SQL or DA.</p><p>Human assessment is separate and starts unassessed for this version.</p></section>
      {current&&!work.review&&<section className="eb-panel"><h2>Human evidence review · V{work.version}</h2><p>Review the work against the task target. Confirmation neither awards full marks nor retains the candidate.</p><div className="eb-actions">{(['confirm',...(work.version===1?['needs_more_evidence']:[]),'evidence_still_insufficient'] as Review['decision'][]).map(d=><button className="eb-action" key={d} disabled={controller.busy} onClick={()=>{setDecision(d);setComment('');}}>{d==='confirm'?'Confirm evidence':d==='needs_more_evidence'?'Needs More Evidence':'Evidence Still Insufficient'}</button>)}</div></section>}
    </>}
    {decision&&work&&<Dialog title={`V${work.version} · human review`} close={()=>setDecision(null)}><p>Public feedback to {profile.name}. Explain the gap; avoid supplying a complete reference answer.</p><label className="eb-field">Public review comment<textarea aria-label="Public review comment" maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label>{controller.error&&<p role="alert">{controller.error}</p>}<button className="eb-action primary" disabled={controller.busy||!comment.trim()} onClick={async()=>{if(await controller.run(s=>reviewWork(s,profile,work.id,decision,comment),`${profile.name}: V${work.version} review saved in the local mock. Marks and shortlist are unchanged.`))setDecision(null);}}>{controller.busy?'Saving locally…':'Save local evidence review'}</button></Dialog>}
  </>;
}
