import { useEffect, useState, useSyncExternalStore } from 'react';
import { Home, ClipboardList, ChartNoAxesCombined, FolderOpen, ShieldCheck } from 'lucide-react';
import { Sidebar, useSidebar } from '../../shared/ui';
import { useApi, type ApiState } from '../../shared/use-api';
import { AnalysisView, ApplicationSources, ApiNotice, Dialog, Heading, ProcessTimeline, ResourceList, ReviewNote, Snapshot, VersionPicker } from '../../shared/api-ui';
import { copySnapshot, draftKey, download, event, publicWork, readDraft, submissionIssues, submissionPayload, workMarkdown, type Draft } from '../../shared/api';
import type { Demo } from '../../shared/api-types';
import { ApiWorkspace, type DraftChange } from './ApiWorkspace';

const nav = [{id:'home',label:'Home',Icon:Home},{id:'tasks',label:'My Tasks',Icon:ClipboardList},{id:'workspace',label:'Workspace',Icon:ChartNoAxesCombined},{id:'resources',label:'Resources',Icon:FolderOpen},{id:'status',label:'Application Status',Icon:ShieldCheck}];
const subscribe = (callback: () => void) => { addEventListener('hashchange', callback); return () => removeEventListener('hashchange', callback); };
const route = () => ['home','tasks','workspace','resources','sample','status'].includes(location.hash.slice(1)) ? location.hash.slice(1) : 'home';
export default function ApiApp() {
  const api = useApi('candidate'); const sidebar = useSidebar('candidate');
  const page = useSyncExternalStore(subscribe, route); const [help, setHelp] = useState(false);
  const navigate = (id: string) => { location.hash = id; sidebar.closeMobile(); window.scrollTo(0,0); };
  return <div className="eb-connected"><a href="#api-main" className="eb-skip eb-action">Skip to content</a><Sidebar role="candidate" controller={sidebar} activePage={page === 'sample' ? 'workspace' : page} items={nav.map(({id,label,Icon}) => ({id,label,icon:<Icon size={18}/>,href:`#${id}`}))} onNavigate={navigate} user={{initials:'AC',name:api.data?.candidate.name ?? 'Candidate',title:'Candidate'}} helpLabel="Help & support" onHelp={() => setHelp(true)}/><div className="eb-main" data-eb-content><header className="eb-api-topbar">{sidebar.menuButton}<span>Candidate / {page === 'sample' ? 'Work sample' : nav.find(n => n.id === page)?.label}</span><small>Shared local demo · synthetic application</small></header><main id="api-main" className="eb-content"><ApiNotice api={api}/>{api.data && <CandidateCase key={`${api.data.sessionId}.${api.data.task.taskId}.${api.data.workflow.nextSubmissionVersion ?? api.data.currentSubmissionVersion ?? 1}`} data={api.data} api={api} page={page} navigate={navigate}/>}<footer className="eb-footer">EvidenceBridge · Evidence first. People decide. · Shared local API; no real application upload or email.</footer></main></div>{help && <Dialog title="Your evidence workspace" close={() => setHelp(false)}><p>Read the task sent by HR, explore the synthetic resources and build an investigation. Your private notes stay in this browser.</p><p>Only V1 Needs More Evidence opens one V2 draft. Submitted versions are immutable. Refresh shared case to receive tasks and decisions from HR.</p><p>Application materials are preset. SQL and Python are guided examples. Appearance and local drafts are stored separately from shared decisions.</p></Dialog>}</div>;
}
function CandidateCase({ data, api, page, navigate }: { data: Demo; api: ApiState; page: string; navigate: (p: string) => void }) {
  const intendedVersion = data.workflow.nextSubmissionVersion ?? data.currentSubmissionVersion ?? 1;
  const key = draftKey(data, intendedVersion);
  const [draft, setDraft] = useState<Draft>(() => readDraft(key));
  const [storageOk, setStorageOk] = useState(true);
  const [selected, setSelected] = useState<number>(data.currentSubmissionVersion ?? 1);
  const [confirm, setConfirm] = useState(false);
  const [message, setMessage] = useState('');
  useEffect(() => { try { localStorage.setItem(key, JSON.stringify(draft)); setStorageOk(true); } catch { setStorageOk(false); } }, [key, draft]);
  const editable = api.fresh && data.workflow.canSubmit && !api.busy.includes('write') && !api.pending.some(p => p.path === '/submission');
  const update: DraftChange = fn => { if (editable) setDraft(d => ({ ...fn(d), savedAt: new Date().toISOString() })); };
  const chosen = data.versions.find(v => v.submission.submissionVersion === selected) ?? data.versions.at(-1);
  const currentVersion = data.versions.find(v => v.submission.submissionId === data.submission?.submissionId);
  const start = (copy = false) => {
    if (!editable) return;
    update(d => copy && data.versions[0] ? { ...copySnapshot(data.versions[0].submission), notes: d.notes } : { ...d, started:true, events:[...d.events,event(`Started V${intendedVersion} draft`)].slice(-100) });
    navigate('workspace');
  };
  const sharedState = data.task.status === 'draft' ? 'Waiting for HR to send a task' : data.task.status === 'awaiting_revision' ? 'V1 reviewed · one V2 revision available' : data.task.status === 'sent' ? 'Task received · V1 ready to start' : data.task.status === 'submitted' ? `V${data.currentSubmissionVersion} submitted · in review` : 'Review complete · this task is closed';
  const submit = async () => {
    if (!editable || submissionIssues(data,draft).length) return;
    const submittedDraft = { ...draft, events: [...draft.events, event(`Submitted V${intendedVersion} work sample`)].slice(-100) };
    const issues = submissionIssues(data, submittedDraft);
    if (issues.length) { setMessage(issues.join(' ')); setConfirm(false); return; }
    const payload = submissionPayload(data, submittedDraft);
    if (await api.write('/submission', payload)) { setConfirm(false); navigate('status'); }
  };
  const draftActions = <div className="eb-actions"><button className="eb-action" disabled={!editable} onClick={() => { update(d => ({ ...d, events:[...d.events,event('Saved draft')].slice(-100) })); setMessage(storageOk ? 'Draft saved locally for this version.' : 'Draft is kept in this tab only.'); }}>Save Draft</button><button className="eb-action" onClick={() => navigate(page === 'sample' ? 'workspace' : 'sample')}>{page === 'sample' ? 'Back to investigation' : 'Preview work sample'}</button></div>;
  return <>
    {!storageOk && <p className="eb-feedback" role="alert">Browser storage is unavailable. Keep this tab open or download your public work before leaving. Private notes are not exported.</p>}
    {message && <p role="status">{message}</p>}
    {page === 'home' && <><Heading eyebrow={`${data.job.company} · Careers`} title="Your application"/><div className="eb-two-column"><section className="eb-panel"><h2>{data.job.title}</h2><p>Preset synthetic application for {data.candidate.name}. The materials below were supplied with this demo; no upload or automated parsing has occurred.</p><ApplicationSources data={data}/><div className="eb-actions"><button className="eb-action primary" onClick={() => navigate('tasks')}>View task status</button></div></section><section className="eb-panel"><h2>Your next step</h2><p>{sharedState}</p><p>A human reviews the evidence. This is not a candidate score or hiring decision.</p></section></div></>}
    {page === 'tasks' && <><Heading title="My tasks"/><section className="eb-panel"><span className="eb-chip is-warning">{sharedState}</span>{data.task.status === 'draft' ? <><h2>Waiting for a targeted task</h2><p>HR has not sent the task. Refresh this case after HR sends it.</p></> : <><h2>{data.task.title}</h2><p className="eb-preserve">{data.task.instructions}</p><p>{data.task.timeboxMinutes} minutes suggested · No enforced deadline · {data.task.resourceIds.length} resources</p>{data.workflow.canSubmit && <div className="eb-actions">{draft.started ? <button className="eb-action primary" onClick={() => navigate('workspace')}>Continue V{intendedVersion} draft</button> : <><button className="eb-action primary" disabled={!editable} onClick={() => start()}>Start V{intendedVersion} draft</button>{data.workflow.canResubmit && <button className="eb-action" disabled={!editable} onClick={() => start(true)}>Copy V1 into a V2 draft</button>}</>}</div>}{data.submission && <button className="eb-action" onClick={() => navigate('sample')}>View submitted versions</button>}</> }</section>{data.review && currentVersion && <ReviewNote version={currentVersion}/>}</>}
    {page === 'resources' && <><Heading title="Resources"/>{data.task.status === 'draft' ? <section className="eb-panel">Resources become available when HR sends your task.</section> : <section className="eb-panel"><ResourceList resources={data.dataset.resources} onEvent={title => { if (draft.started) update(d => ({ ...d, events:[...d.events,event(title)].slice(-100) })); }}/></section>}</>}
    {page === 'workspace' && <><Heading eyebrow={`V${intendedVersion} draft · ${data.job.company}`} title={data.task.title}/>{data.workflow.canSubmit && draft.started ? <><section className="eb-panel"><p className="eb-preserve">{data.task.instructions}</p><small>{data.task.timeboxMinutes} minutes suggested · No enforced deadline · {draft.savedAt ? `Saved ${new Date(draft.savedAt).toLocaleString()}` : 'Local draft'}</small>{draftActions}</section>{data.workflow.canResubmit && data.versions[0] && <ReviewNote version={data.versions[0]}/>}<ApiWorkspace data={data} draft={draft} update={update} editable={editable}/></> : <section className="eb-panel"><p>{sharedState}</p><button className="eb-action primary" onClick={() => navigate(data.workflow.canSubmit ? 'tasks' : data.submission ? 'sample' : 'tasks')}>{data.workflow.canSubmit ? 'Open draft controls' : data.submission ? 'View saved work' : 'View task status'}</button></section>}</>}
    {page === 'sample' && <><Heading title="My investigation brief"/>{data.workflow.canSubmit && draft.started && <section className="eb-panel"><h2>V{intendedVersion} draft</h2>{data.workflow.canResubmit && <p className="eb-feedback">V1 remains unchanged. This draft becomes V2 only when you formally submit.</p>}<label className="eb-field" htmlFor="api-summary">Executive summary</label><textarea id="api-summary" className="eb-draft-summary" maxLength={8000} value={draft.summary} disabled={!editable} onChange={e => update(d => ({ ...d, summary:e.target.value }))}/><small>{draft.summary.length}/8,000 characters · {draft.findings.length}/40 cards</small>{sectionsPreview(draft)}{draftActions}<div className="eb-actions"><button className="eb-action primary" disabled={!editable} onClick={() => setConfirm(true)}>Submit V{intendedVersion} work sample</button><button className="eb-action" onClick={() => download(`draft-v${intendedVersion}.md`, workMarkdown(publicWork(draft)), 'text/markdown')}>Download draft brief</button><button className="eb-action" onClick={() => download(`draft-v${intendedVersion}.json`, JSON.stringify({ ...publicWork(draft), intendedSubmissionVersion:intendedVersion, kind:'local-public-draft' }, null, 2), 'application/json')}>Export public draft JSON</button></div><p className="eb-muted">Private notes are excluded from submission and both exports.</p></section>}{data.versions.length > 0 && chosen ? <><VersionPicker data={data} selected={chosen.submission.submissionVersion} onSelect={setSelected}/><ReviewNote version={chosen}/><Snapshot version={chosen}/><button className="eb-action" onClick={() => download(`submission-v${chosen.submission.submissionVersion}.json`, JSON.stringify(chosen.submission,null,2),'application/json')}>Export V{chosen.submission.submissionVersion} snapshot JSON</button><ProcessTimeline events={chosen.submission.processEvidence}/><AnalysisView key={chosen.submission.submissionId} version={chosen} refresh={() => void api.refresh()}/></> : !draft.started && <section className="eb-panel">No submitted work yet. Start the task when it is available.</section>}</>}
    {page === 'status' && <><Heading title="Application status"/><section className="eb-panel"><h2>{sharedState}</h2><p>{data.workflow.isTerminal ? 'No further submission is available for this task.' : 'Use Refresh shared case to receive the latest task or review.'}</p><p>Evidence review is not a hiring decision.</p><button className="eb-action primary" onClick={() => navigate(data.workflow.canSubmit ? 'tasks' : 'sample')}>{data.workflow.canSubmit ? 'View task and draft controls' : 'View submitted versions'}</button></section>{data.versions.map(v => <ReviewNote key={v.submission.submissionId} version={v}/>)}<section className="eb-panel"><h2>Current evidence report</h2>{data.report.requirements.map(r => <div key={r.requirementId}><h3>{r.title} · {r.displayLabel}</h3><p>{r.summary}</p><small>{r.uncertainty}</small></div>)}</section></>}
    {confirm && <Dialog title={`Submit V${intendedVersion} work sample?`} close={() => setConfirm(false)}>{submissionIssues(data,draft).length ? <><p>Resolve these issues before submitting:</p><ul>{submissionIssues(data,draft).map(i => <li key={i}>{i}</li>)}</ul></> : <><p>This saves an immutable public snapshot. Missing sections are allowed; private notes are excluded.</p><p>{draft.findings.length} cards · {draft.events.length} client-reported events</p><button className="eb-action primary" disabled={!editable} onClick={() => void submit()}>{api.busy.includes('write') ? 'Submitting…' : `Confirm V${intendedVersion} submission`}</button></>}</Dialog>}
  </>;
}
function sectionsPreview(draft: Draft) { return draft.findings.map(f => <article className="eb-finding" key={f.id}><small>{f.section}</small><h3>{f.title}</h3><p className="eb-preserve">{f.detail}</p><small>{f.source || 'No source supplied'}</small></article>); }
