import { useEffect, useReducer, useState, useSyncExternalStore } from 'react';
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, Building2, ChartNoAxesCombined, Check, ChevronRight, CircleHelp, ClipboardList, FileText, FolderOpen, Home, Layers3, MapPin, Menu, MonitorPlay, PanelLeftClose, RotateCcw, ShieldCheck, Sparkles, Upload, X } from 'lucide-react';
import { CandidateContext, useCandidate, type Page } from './context';
import { initialState, reducer, restore, stamp, storageKey } from './state';
import { company, role, taskTitle } from './data';
import { Badge, Empty, Modal, ResourceBrowser, Timeline } from './ui';
import { Workspace, WorkSample } from './Workspace';
const nav = [{ page:'home', label:'Home', icon:Home },{ page:'tasks', label:'My Tasks', icon:ClipboardList },{ page:'workspace', label:'Workspace', icon:ChartNoAxesCombined },{ page:'resources', label:'Resources', icon:FolderOpen },{ page:'status', label:'Application Status', icon:ShieldCheck }] as const;
const subscribe = (callback: () => void) => { window.addEventListener('hashchange',callback); return () => window.removeEventListener('hashchange',callback); };
function route(): Page { const page = location.hash.slice(1); return ['home','tasks','workspace','resources','sample','status'].includes(page) ? page as Page : 'home'; }
function load() { try { return restore(localStorage.getItem(storageKey)); } catch { return { ...initialState }; } }
export default function App() {
  const [state,dispatch] = useReducer(reducer,undefined,load);
  const [toast,setToast] = useState(''); const [storageError,setStorageError] = useState(false);
  const [demo,setDemo] = useState(false); const [help,setHelp] = useState(false); const [sidebar,setSidebar] = useState(false);
  const page = useSyncExternalStore(subscribe,route);
  useEffect(() => { try { localStorage.setItem(storageKey,JSON.stringify(state)); setStorageError(false); } catch { setStorageError(true); } },[state]);
  useEffect(() => { if (toast) { const timer=setTimeout(()=>setToast(''),4500); return ()=>clearTimeout(timer); } },[toast]);
  const navigate = (next: Page) => { location.hash=next; setSidebar(false); window.scrollTo({top:0,behavior:'instant'}); };
  const locked = state.stage === 'application' || state.stage === 'received';
  function populatedDemo() { dispatch({type:'RESET'}); dispatch({type:'LOAD_APPLICATION'}); dispatch({type:'APPLY',...stamp()}); dispatch({type:'START',...stamp()}); dispatch({type:'LOAD_FINDINGS',...stamp()}); navigate('workspace'); setDemo(false); setToast('Example investigation loaded. You can edit every card.'); }
  return <CandidateContext.Provider value={{state,dispatch,navigate,notify:setToast,storageAvailable:!storageError}}><div className="app-shell">
    {sidebar && <button className="sidebar-backdrop" aria-label="Close navigation" onClick={()=>setSidebar(false)}/>}
    <aside className={`sidebar ${sidebar?'open':''}`}><a className="brand" href="#home"><Layers3 size={24}/><span>EvidenceBridge</span></a><button className="mobile-close icon-button" aria-label="Close navigation" onClick={()=>setSidebar(false)}><PanelLeftClose size={20}/></button>
      <div className="role-label">CANDIDATE WORKSPACE</div><nav aria-label="Main navigation">{nav.map(({page:target,label,icon:Icon})=><a key={target} href={`#${target}`} onClick={()=>setSidebar(false)} aria-current={page===target || (page==='sample' && target==='workspace')?'page':undefined} className={page===target || (page==='sample' && target==='workspace')?'active':''}><Icon size={18}/><span>{label}</span>{target==='tasks' && state.stage!=='application' && <span className="nav-count">1</span>}</a>)}</nav>
      <div className="sidebar-footer"><div className="sidebar-message"><ShieldCheck size={22}/><p>Your work.<br/><strong>Your evidence.</strong></p><small>A clearer picture of what you can do.</small></div><button className="help-button" onClick={()=>setHelp(true)}><CircleHelp size={17}/>Help & support<ArrowUpRight size={14}/></button><div className="user-block"><span className="avatar">AC</span><span><strong>Alex Chen</strong><small>Candidate</small></span><Badge>Demo</Badge></div></div>
    </aside>
    <div className="app-main"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setSidebar(true)}><Menu size={20}/></button><span>Candidate</span><ChevronRight size={14}/><strong>{page==='sample'?'Work sample':nav.find(n=>n.page===page)?.label}</strong></div><div className="topbar-right"><span className="local-indicator"><span/>Local demo workspace</span><button className="demo-button" onClick={()=>setDemo(true)}><MonitorPlay size={15}/>Demo controls</button></div></header>
      {storageError && <div className="alert amber" role="alert">Browser storage is unavailable. Your work remains in this tab; download your work sample before leaving.</div>}
      <main id="main-content" className={`main-content ${page==='workspace'?'workspace-content':''}`}>
        {page==='home' && <Application/>}{page==='tasks' && <Tasks/>}
        {page==='workspace' && (locked ? <Empty title="Your workspace is almost ready" action={<button className="button primary" onClick={()=>navigate(state.stage==='received'?'tasks':'home')}>{state.stage==='received'?'View your task':'Complete application'}<ArrowRight size={16}/></button>}>Submit your application and open your targeted task to begin investigating.</Empty>:<Workspace/>)}
        {page==='resources' && <><PageHeading eyebrow="YOUR INVESTIGATION TOOLKIT" title="Data & resources" description="Everything you need to explore the business problem. Open a file to inspect it, or download a copy."/>{locked?<Empty title="Resources arrive with your task" action={<button className="button primary" onClick={()=>navigate('tasks')}>View tasks<ArrowRight size={16}/></button>}>Your analysis resources become available when you start the targeted task.</Empty>:<section className="card resource-library"><div className="section-heading"><h2>Conversion Drop Investigation</h2><Badge tone="blue">6 resources</Badge></div><ResourceBrowser/><div className="resource-note"><ShieldCheck size={17}/>These files contain synthetic demo data. No personal customer information is included.</div></section>}</>}
        {page==='sample' && (locked?<Empty title="No work sample yet" action={<button className="button primary" onClick={()=>navigate('tasks')}>View tasks</button>}>Start your task to build an investigation.</Empty>:<WorkSample/>)}
        {page==='status' && <Status/>}
      </main><footer className="app-footer"><span>EvidenceBridge</span><span>Evidence, with you at the centre.</span><span>Candidate experience · Demo</span></footer>
    </div>{toast && <div className="toast" role="status"><Check size={18}/><span>{toast}</span><button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
    {help && <Modal title="A small piece of real work" onClose={()=>setHelp(false)}><p>Explore the files, record what you find, and separate observations from hypotheses. Use the investigation board to connect your recommendations to evidence.</p><div className="help-steps"><p><strong>1. Investigate</strong> — inspect resources and compare channels.</p><p><strong>2. Build your case</strong> — add findings, hypotheses, evidence requests and next steps.</p><p><strong>3. Share your work</strong> — review your executive summary and submit the work sample.</p></div><p className="muted">In this local demo, files and HR responses are simulated. Work is saved in this browser when storage is available. SQL and Python tabs show guided examples, not live code execution.</p><button className="button primary" onClick={()=>setHelp(false)}>Got it</button></Modal>}
    {demo && <Modal title="Demo controls" onClose={()=>setDemo(false)}><p>Use these controls to explore the complete Candidate experience. They simulate task delivery and HR responses; they do not contact a hiring team.</p><div className="demo-options"><button className="button secondary" onClick={populatedDemo}><Sparkles size={17}/>Open populated workspace</button><small>Replaces the current local draft with an editable example investigation.</small>
      <button className="button secondary" disabled={state.stage!=='submitted'} onClick={()=>{dispatch({type:'REVIEW',review:'confirmed',...stamp()});setDemo(false);navigate('status');}}><ShieldCheck size={17}/>Simulate HR confirmation</button>
      <button className="button secondary" disabled={state.stage!=='submitted'} onClick={()=>{dispatch({type:'REVIEW',review:'more',...stamp()});setDemo(false);navigate('status');}}>Simulate request for more evidence</button>
      <button className="button secondary" disabled={state.stage!=='submitted'} onClick={()=>{dispatch({type:'REVIEW',review:'insufficient',...stamp()});setDemo(false);navigate('status');}}>Simulate insufficient evidence</button><small>Submit a work sample to enable the three review outcomes.</small>
      <button className="button danger" onClick={()=>{dispatch({type:'RESET'});navigate('home');setDemo(false);setToast('Demo reset. You can start a new application.');}}><RotateCcw size={16}/>Reset all demo work</button><small>Clears the application, draft, notes and timeline in this browser.</small></div></Modal>}
  </div></CandidateContext.Provider>;
}
export function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function Application() {
  const {state,dispatch,navigate,notify}=useCandidate(); const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const submitted=state.stage!=='application';
  function choose(kind:'resume'|'project',file:File|undefined) { if(!file)return; if(!file.name.toLowerCase().endsWith('.pdf') || file.size>10*1024*1024 || file.size===0) {setError('Choose a non-empty PDF smaller than 10 MB.');return;}setError('');dispatch({type:'MATERIAL',kind,material:{name:file.name,size:file.size}});notify('File selected locally. Its contents are not uploaded.'); }
  return <><PageHeading eyebrow="HARBOURCART · CAREERS" title={submitted?'Your application is in.':`Your application`} description={submitted?'Your evidence journey with HarbourCart is underway.':'A thoughtful application is just the beginning. Show the team how you approach real work.'}/>
    <div className="application-grid"><section className="card application-card"><div className="company-heading"><span className="company-mark"><Building2 size={27}/></span><div><small>{company}</small><h2>{role}</h2></div><Badge tone="green">Open role</Badge></div><div className="role-meta"><span><MapPin size={15}/>Sydney, Australia</span><span><BriefcaseBusiness size={15}/>Full-time</span><span><ChartNoAxesCombined size={15}/>Data & Analytics</span></div>
      <div className="about-role"><h3>About this role</h3><p>Join the team helping an Australian online retailer turn everyday data into better business decisions. We’re interested in how you investigate a problem, ask good questions and build a case with evidence.</p><div className="skill-chips"><span>SQL</span><span>Data Analysis</span><span>Business Problem Solving</span></div></div>
      <div className="section-heading"><h2>Your application materials</h2>{submitted&&<Badge tone="green"><Check size={12}/>Submitted</Badge>}</div><p className="muted">Start with your resume. A project that shows your thinking is a welcome addition.</p>
      {(['resume','project'] as const).map(kind=><div className="upload-section" key={kind}><label className="field-label" htmlFor={`${kind}-file`}>{kind==='resume'?'CV / Resume':'Project material'}<span>{kind==='resume'?'Required':'Optional'}</span></label><div className={`upload-box ${state[kind]?'has-file':''}`}><span className="file-icon"><FileText size={23}/></span><div><strong>{state[kind]?.name ?? (kind==='resume'?'Add your resume':'Share a piece of your work')}</strong><small>{state[kind]?`${(state[kind]!.size/1024).toFixed(0)} KB · PDF`:'PDF · up to 10 MB'}</small></div>{!submitted&&<label className="button secondary upload-label" htmlFor={`${kind}-file`}><Upload size={15}/>{state[kind]?'Replace':'Choose file'}<input id={`${kind}-file`} type="file" accept=".pdf,application/pdf" onChange={e=>{choose(kind,e.target.files?.[0]);e.target.value='';}}/></label>}</div></div>)}
      {error&&<p role="alert" className="error-text">{error}</p>}<div className="application-actions">{submitted?<button className="button primary" onClick={()=>navigate('tasks')}>View your targeted task<ArrowRight size={16}/></button>:<><button className="button secondary" onClick={()=>{dispatch({type:'LOAD_APPLICATION'});setError('');notify('Demo resume and project loaded.');}}><Sparkles size={16}/>Load Demo Application</button><button className="button primary" disabled={busy} onClick={()=>{if(!state.resume){setError('Add your resume or load the demo application first.');return;}setBusy(true);setTimeout(()=>{dispatch({type:'APPLY',...stamp()});setBusy(false);navigate('tasks');notify('Application submitted. A targeted task is ready in this demo.');},550);}}>{busy?'Submitting…':'Submit Application'}<ArrowRight size={16}/></button></>}</div><p className="privacy-note"><ShieldCheck size={14}/>Demo files stay in your browser. Nothing is sent to a real employer.</p>
    </section><aside className="application-aside"><section className="card journey-card"><div className="eyebrow">A MORE COMPLETE PICTURE</div><h2>What happens next</h2><p>Your experience matters. So does the way you think.</p><ol className="journey"><li><span>1</span><div><strong>Share your starting point</strong><p>Your resume and projects help the team understand your experience.</p></div></li><li><span>2</span><div><strong>Show your approach</strong><p>A focused, realistic task fills in what your application can’t show.</p></div></li><li><span>3</span><div><strong>Be seen through your work</strong><p>A person reviews your findings, your process and your recommendations.</p></div></li></ol></section><div className="trust-note"><ShieldCheck size={22}/><div><strong>Evidence first. People decide.</strong><p>Your work supports a human review. You’re more than a score.</p></div></div></aside></div></>;
}
function Tasks() {
  const {state,dispatch,navigate}=useCandidate();
  return <><PageHeading eyebrow="FOCUSED WORK. MEANINGFUL EVIDENCE." title="My tasks" description="A chance to show how you think, using a real-world business problem."/>{state.stage==='application'?<Empty title="Your next step starts with an application" action={<button className="button primary" onClick={()=>navigate('home')}>Complete application<ArrowRight size={16}/></button>}>Once your materials have been reviewed, targeted tasks will appear here.</Empty>:<section className="card task-card"><div className="task-card-top"><span className="task-icon"><ChartNoAxesCombined size={28}/></span><Badge tone={state.stage==='submitted'?'blue':state.stage==='reviewed'?'green':'amber'}>{state.stage==='received'?'Ready to start':state.stage==='working'?'Draft in progress':state.stage==='submitted'?'In review':'Review complete'}</Badge></div><div className="eyebrow">{company} · {role}</div><h2>{taskTitle}</h2><p className="task-intro">Traffic is up. Conversion is down. What would you investigate?</p><p>Website traffic increased by 18%, while conversion fell from 3.4% to 2.6% and ad spend rose 15%. Explore the data, identify likely causes and recommend what the business should do next.</p><div className="task-facts"><div><small>CAPABILITY TO EXPLORE</small><strong>Business Problem Solving</strong></div><div><small>SUGGESTED TIME</small><strong>35–45 minutes · No time limit</strong></div><div><small>YOUR DELIVERABLE</small><strong>Structured investigation brief</strong></div></div><div className="why-task"><CircleHelp size={20}/><div><strong>Why this task?</strong><p>Your application shows SQL and data analysis experience. This task gives you room to demonstrate how you frame a business problem, seek evidence and make a recommendation.</p></div></div><div className="task-bottom"><span><FolderOpen size={16}/>6 data & context files included</span><button className="button primary" onClick={()=>{if(state.stage==='received')dispatch({type:'START',...stamp()});navigate(state.stage==='submitted'||state.stage==='reviewed'?'sample':'workspace');}}>{state.stage==='received'?'Start investigation':state.stage==='working'?'Continue investigation':'View work sample'}<ArrowRight size={17}/></button></div></section>}</>;
}
function Status() {
  const {state,navigate}=useCandidate();const isMore=state.review==='more';
  const step=state.stage==='application'?0:state.stage==='received'||state.stage==='working'?1:state.stage==='submitted'?2:3;
  const title=state.stage==='application'?'Your application journey':isMore?'A little more evidence is needed':state.stage==='reviewed'?(state.review==='confirmed'?'Your evidence has been confirmed':'Your review is complete'):state.stage==='submitted'?'Your work is with the hiring team':'Your targeted task is ready';
  return <><PageHeading eyebrow="KEEPING YOU IN THE PICTURE" title="Application status" description={`${role} · ${company}`}/><section className="card status-card"><span className={`status-symbol ${isMore?'amber':''}`}><ShieldCheck size={36}/></span><Badge tone={state.stage==='reviewed'?(state.review==='confirmed'?'green':'red'):isMore?'amber':'blue'}>{state.stage==='reviewed'?(state.review==='confirmed'?'Verified through targeted task':'Evidence still insufficient'):isMore?'Needs more evidence':state.stage==='submitted'?'In review':state.stage==='application'?'Not submitted':'Task received'}</Badge><h2>{title}</h2><p>{state.stage==='submitted'?'Your work sample and investigation timeline are ready for human review. You can still view and download your submission.':state.stage==='reviewed'?(state.review==='confirmed'?'The targeted task has added supported evidence of your Business Problem Solving capability.':'The reviewed work does not yet provide enough evidence for this capability. This is an evidence review, not a hiring decision.'):isMore?'The demo reviewer has asked you to compare campaign performance by device. Your draft is open again so you can add evidence and resubmit.':'Follow the steps below to share your experience and show your approach.'}</p><ol className="progress-stepper">{['Application submitted','Task completed','In review','Review complete'].map((s,i)=><li key={s} className={i<step?'complete':i===step?'current':''}><span>{i<step?<Check size={17}/>:i+1}</span><strong>{s}</strong></li>)}</ol><div className="status-actions"><button className="button primary" onClick={()=>navigate(state.stage==='application'?'home':state.stage==='submitted'||state.stage==='reviewed'?'sample':'tasks')}>{state.stage==='application'?'Complete application':state.stage==='submitted'||state.stage==='reviewed'?'View submitted work':'Continue to your task'}<ArrowRight size={16}/></button></div>{state.review&&<p className="simulation-note">This review outcome was simulated with Demo controls.</p>}</section><section className="card activity-card"><div className="section-heading"><h2>Your activity</h2><Badge>{state.events.length} events</Badge></div><Timeline/></section></>;
}
