import React, { Suspense, lazy } from 'react';
import ReactDOM from 'react-dom/client';
import './styles.css';
import '../../shared/tokens.css';
import '../../shared/shell.css';
import '../../shared/connected.css';
import { initializeTheme } from '../../shared/preferences';
document.documentElement.dataset.role = 'candidate';
initializeTheme();
const mode = import.meta.env.VITE_APP_MODE || 'api4-connected';
const standalone = mode === 'standalone';
const App = standalone ? lazy(() => import('./App')) : mode === 'revision5-preview' ? lazy(() => import('./Revision5App')) : mode === 'connected' ? lazy(() => import('./ApiApp')) : mode === 'api3-connected' ? lazy(() => import('./Api3App')) : lazy(() => import('./Api4App'));
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><Suspense fallback={<p>Loading EvidenceBridge…</p>}>{standalone && <p className="eb-feedback">Standalone simulation · no shared API connection</p>}<App /></Suspense></React.StrictMode>);
