import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import '../../shared/tokens.css';
import '../../shared/shell.css';
import { initializeTheme } from '../../shared/preferences';
document.documentElement.dataset.role = 'candidate';
initializeTheme();
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
