import {expect,it} from 'vitest';
import type { Demo, Comparison } from '../../shared/api4-types';
import {retainedRows,decisionIsCurrent,decisionEvidence} from '../../shared/api4/retained-model';
const ids=['amy-chen','ann-li','david-liu','jamie-parker'];
const rows=ids.map((id,i)=>({candidate:{id,name:id},shortlist:{status:['retained','needs_reconfirmation','not_retained','not_retained'][i]}})) as Comparison['candidates'];
const data=()=>{
 const ref={candidateId:'amy-chen',evidenceSnapshotId:'snapshot',fingerprint:'fingerprint',sourceId:'work.sql',location:'/text',start:0,end:8,quote:'evidence'};
 const items=['S1','S2','D1','B1','B3'].map((id,i)=>({criterionId:id,mark:i<3?4:i===4?'NE':2,support:'support',gaps:'gap',uncertainty:'unknown',nextStep:'verify',sourceRefs:[ref],checkedSourceIds:['work.sql']}));
 return {candidate:{id:'amy-chen'},rubricVersion:'rubric',rubric:{criteria:items.map(i=>({id:i.criterionId,title:i.criterionId}))},application:{evidenceSnapshotId:'snapshot',fingerprint:'fingerprint',sources:[{sourceId:'work.sql',location:'/text',text:'evidence text'}]},assessment:{application_review:{candidateId:'amy-chen',stage:'application_review',rubricVersion:'rubric',evidenceSnapshotId:'snapshot',fingerprint:'fingerprint',assessmentRevision:1,items}},shortlist:{status:'retained',basis:{stage:'application_review',evidenceSnapshotId:'snapshot',fingerprint:'fingerprint',assessmentRevision:1,rubricVersion:'rubric'}},versions:[],gapSuggestions:[]} as unknown as Demo;
};
it('retained-first excludes reconfirmation; All preserves everyone and stable order',()=>{const before=structuredClone(rows);expect(retainedRows(rows,'retained')).toEqual([rows[0]]);expect(retainedRows(rows,'needs_reconfirmation')).toEqual([rows[1]]);expect(retainedRows(rows,'all')).toEqual(rows);expect(rows).toEqual(before);});
it('empty retained category stays empty rather than secretly selecting All',()=>expect(retainedRows(rows.slice(1),'retained')).toEqual([]));
it('currentness requires exact saved stage, snapshot, revision and rubric',()=>{const d=data();expect(decisionIsCurrent(d)).toBe(true);d.shortlist.basis!.assessmentRevision=0;expect(decisionIsCurrent(d)).toBe(false);d.shortlist.basis!.assessmentRevision=1;d.shortlist.status='needs_reconfirmation';expect(decisionIsCurrent(d)).toBe(false);});
it('excerpts span distinct skills, follow rubric order, and preserve source data',()=>{const d=data(),before=structuredClone(d);expect(decisionEvidence(d,'application_review').supports.map(i=>i.criterionId)).toEqual(['S1','D1']);expect(d).toEqual(before);});
it('NE remains a concern, not a fabricated numerical support',()=>{const e=decisionEvidence(data(),'application_review');expect(e.concerns.map(i=>i.criterionId)).toEqual(['B1','B3']);expect(e.concerns[1].mark).toBe('NE');});
it('mismatched candidate, stage, fingerprint and rubric never supply excerpts',()=>{for(const [key,value] of [['candidateId','ann-li'],['stage','task_v1'],['fingerprint','changed'],['rubricVersion','other']] as const){const d=data();Object.assign(d.assessment.application_review!,{[key]:value});expect(decisionEvidence(d,'application_review').supports).toEqual([]);}});
it('invalid quotations are not clickable support',()=>{const d=data();d.assessment.application_review!.items.forEach(i=>i.sourceRefs[0].quote='not in source');expect(decisionEvidence(d,'application_review').supports).toEqual([]);});
it('missing task stage is not replaced by application evidence',()=>{expect(decisionEvidence(data(),'task_v2')).toMatchObject({assessment:null,supports:[],concerns:[]});});
it('backend gap priority is preserved and stale gap revisions excluded',()=>{const d=data();d.gapSuggestions=[{stage:'application_review',assessmentRevision:0,evidenceSnapshotId:'snapshot',fingerprint:'fingerprint',priority:0,criterionId:'S1'},{stage:'application_review',assessmentRevision:1,evidenceSnapshotId:'snapshot',fingerprint:'fingerprint',priority:2,criterionId:'B1'},{stage:'application_review',assessmentRevision:1,evidenceSnapshotId:'snapshot',fingerprint:'fingerprint',priority:1,criterionId:'B3'}] as Demo['gapSuggestions'];expect(decisionEvidence(d,'application_review').concerns.map(i=>i.criterionId)).toEqual(['B3','B1']);});
