import { useState } from 'react';
import { ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, ChartColumn, Check, ChevronDown, Clock3, Code2, Download, Eye, FileText, Filter, FolderOpen, Lightbulb, Link2, ListChecks, NotebookPen, Pencil, Plus, Save, Send, Sparkles, Target, Trash2 } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useCandidate } from './context';
import { Badge, Modal, ResourceBrowser, Timeline } from './ui';
import { channels, download, resources, sections, taskTitle, trafficTrend, type Finding, type Section } from './data';
import { stamp, submissionIssues } from './state';
const icons = [ChartColumn, Lightbulb, FolderOpen, Target];
export function Workspace() {
  const {state,dispatch,navigate,notify,storageAvailable}=useCandidate();
  const [tab,setTab]=useState('Explore');const [sideTab,setSideTab]=useState('board');const [channel,setChannel]=useState('All channels');
  const [editing,setEditing]=useState<Finding|null>(null);const [confirmDemo,setConfirmDemo]=useState(false);const [showTimeline,setShowTimeline]=useState(false);
  const readOnly=state.stage!=='working';
  const filtered=channel==='All channels'?channels:channels.filter(c=>c.channel===channel);
  function add(section:Section) {setEditing({id:crypto.randomUUID(),section,title:'',detail:'',source:resources[0].name,confidence:'Medium'});}
  return <><button className="back-link" onClick={()=>navigate('tasks')}><ArrowLeft size={15}/>Back to My Tasks</button><div className="workspace-heading"><div><div className="title-line"><h1>{taskTitle}</h1><Badge tone="blue">Targeted task</Badge></div><p>HarbourCart · Junior Data Analyst</p></div><div className="workspace-actions">{!readOnly&&<button className="button secondary" onClick={()=>{dispatch({type:'SAVE',...stamp()});notify(storageAvailable?'Draft saved in this browser.':'Draft kept in this tab only. Download a copy before leaving.');}}><Save size={16}/>Save Draft</button>}<button className="button primary" onClick={()=>navigate('sample')}><FileText size={16}/>{readOnly?'View submitted work':'Preview work sample'}<ArrowRight size={15}/></button></div></div>
    <div className="task-brief"><div><span className="eyebrow">THE BUSINESS CHALLENGE</span><p>Website traffic increased by <strong>18%</strong>, but conversion fell from <strong>3.4% to 2.6%</strong>. Ad spend is up <strong>15%</strong>. Investigate the likely causes, identify what else you need to know, and recommend a next step.</p></div><div className="brief-aside"><Lightbulb size={19}/><p>There isn’t one right answer.<br/><strong>Show us how you think.</strong></p></div></div>
    <div className="workspace-meta"><span><Clock3 size={14}/>35–45 min suggested · No time limit</span><span>{readOnly?<Badge tone="blue">Submitted · read only</Badge>:<><span className="save-dot"/>{!storageAvailable?'Unsaved · browser storage unavailable':state.savedAt?`Draft saved ${new Date(state.savedAt).toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'})}`:'Changes saved in this browser'}</>}</span><button onClick={()=>setShowTimeline(true)}><ListChecks size={14}/>Process timeline<span className="count">{state.events.length}</span></button></div>
    <div className="workbench"><section className="card data-panel"><div className="panel-heading"><FolderOpen size={17}/><h2>Data & resources</h2></div><div className="resource-tab"><FileText size={14}/>Task files<span>6</span></div><ResourceBrowser compact/><div className="resource-tip"><Lightbulb size={17}/><p>Follow the evidence.<br/><span>Open a file to inspect the data, or download it for a closer look.</span></p></div><div className="resource-caption">Synthetic demo dataset<br/>Last 4 weeks · AUD</div></section>
    <section className="card analysis-panel"><div className="analysis-tabs" role="tablist" aria-label="Analysis tools">{[{name:'Explore',icon:Eye},{name:'SQL',icon:Code2},{name:'Python',icon:Code2},{name:'Notebook',icon:NotebookPen},{name:'Charts',icon:ChartColumn}].map(({name,icon:Icon})=><button role="tab" aria-selected={tab===name} key={name} onClick={()=>{setTab(name);dispatch({type:'EVENT',title:`Opened ${name} analysis`,...stamp()});}} className={tab===name?'selected':''}><Icon size={14}/>{name}{name==='Python'&&<small>Beta</small>}</button>)}</div>
      <div className="analysis-body" role="tabpanel" aria-label={`${tab} analysis`}>
      {(tab==='Explore'||tab==='Charts')&&<><div className="analysis-title"><h2>{tab==='Explore'?'Website performance overview':'Compare the evidence'}</h2><span>Last 4 weeks</span></div>{tab==='Explore'&&<><div className="metric-grid">{[{label:'Website traffic',value:'1.2M',change:'+18%',up:true},{label:'Conversion rate',value:'2.6%',change:'−0.8 pp',up:false},{label:'Total orders',value:'31,200',change:'−9.8%',up:false},{label:'Ad spend',value:'$48,000',change:'+15%',up:true}].map(m=><div className="metric-card" key={m.label}><span>{m.label}</span><strong>{m.value}</strong><small className={m.label==='Website traffic'?'positive':'negative'}>{m.up?<ArrowUpRight size={12}/>:<ArrowDownRight size={12}/>} {m.change}<em>vs. prior period</em></small></div>)}</div><div className="metrics-caption">Company snapshot · all channels</div></>}
        <div className={`chart-grid ${tab==='Charts'?'expanded':''}`}><div className="chart-card"><h3>Traffic vs. conversion</h3><p className="chart-subtitle">Weekly trend snapshots · sessions (000s)</p><div className="chart-frame"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={trafficTrend} margin={{top:10,right:4,left:-24,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)"/><XAxis dataKey="week" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis yAxisId="traffic" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis yAxisId="conversion" orientation="right" domain={[0,5]} tickFormatter={v=>`${v}%`} tick={{fontSize:10}} width={32} axisLine={false} tickLine={false}/><Tooltip/><Legend wrapperStyle={{fontSize:10}} iconType="circle"/><Bar isAnimationActive={false} name="Traffic (000s)" yAxisId="traffic" dataKey="traffic" fill="var(--chart-traffic)" radius={[3,3,0,0]} maxBarSize={28}/><Line isAnimationActive={false} name="Conversion %" yAxisId="conversion" dataKey="conversion" stroke="var(--chart-line)" strokeWidth={2.5} dot={{r:3}}/></ComposedChart></ResponsiveContainer></div></div>
        <div className="chart-card"><h3>Conversion by channel</h3><p className="chart-subtitle">Current vs. previous four-week period</p><div className="chart-frame"><ResponsiveContainer width="100%" height="100%"><BarChart data={filtered} margin={{top:10,right:0,left:-26,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)"/><XAxis dataKey="channel" tick={{fontSize:9}} tickFormatter={v=>v==='Paid Search'?'Paid':v} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>`${v}%`} tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip/><Legend wrapperStyle={{fontSize:10}} iconType="circle"/><Bar isAnimationActive={false} name="Previous %" dataKey="previous" fill="var(--chart-previous)" radius={[3,3,0,0]} maxBarSize={20}/><Bar isAnimationActive={false} name="Current %" dataKey="conversion" fill="var(--analysis-blue)" radius={[3,3,0,0]} maxBarSize={20}/></BarChart></ResponsiveContainer></div></div></div>
        <div className="table-heading"><h3>Channel performance</h3><label className="filter-select"><Filter size={13}/><select aria-label="Filter channel" value={channel} onChange={e=>{setChannel(e.target.value);dispatch({type:'EVENT',title:`Filtered ${e.target.value}`, ...stamp()});}}><option>All channels</option>{channels.map(c=><option key={c.channel}>{c.channel}</option>)}</select></label></div><div className="table-scroll"><table className="channel-table"><thead><tr><th>Channel</th><th>Traffic</th><th>Change</th><th>Orders</th><th>Conv.</th></tr></thead><tbody>{filtered.map(c=><tr key={c.channel} className={c.channel==='Paid Search'?'highlight-row':''}><td>{c.channel}{c.channel==='Paid Search'&&<span className="table-marker"/>}</td><td>{c.traffic.toLocaleString('en-AU')}</td><td className={c.growth>0?'positive':'negative'}>{c.growth>0?'+':''}{c.growth}%</td><td>{c.orders.toLocaleString('en-AU')}</td><td>{c.conversion.toFixed(1)}%</td></tr>)}</tbody></table></div><div className="analysis-footnote"><Lightbulb size={14}/>What changed most? Turn an observation into a finding on your board.</div>
      </>}
      {(tab==='SQL'||tab==='Python')&&<CodeExample language={tab}/>}
      {tab==='Notebook'&&<><h2>Investigation notebook</h2><p className="muted">A place for rough thinking. Only your investigation board and executive summary become the final work sample.</p><label className="field-label" htmlFor="notebook">Private working notes</label><textarea id="notebook" className="notebook" value={state.notes} disabled={readOnly} onChange={e=>dispatch({type:'NOTES',value:e.target.value})} placeholder="What stands out? What would you check next?"/><p className="privacy-note">Saved in this browser · {state.notes.length} characters</p></>}
      </div></section>
    <section className="card board-panel"><div className="board-tabs" role="tablist" aria-label="Investigation panel"><button role="tab" aria-selected={sideTab==='board'} className={sideTab==='board'?'selected':''} onClick={()=>setSideTab('board')}><ListChecks size={15}/>Investigation Board</button><button role="tab" aria-selected={sideTab==='notes'} className={sideTab==='notes'?'selected':''} onClick={()=>setSideTab('notes')}><NotebookPen size={15}/>Notes</button></div>
      {sideTab==='notes'?<div className="board-notes"><label className="field-label" htmlFor="quick-notes">Working notes</label><textarea id="quick-notes" value={state.notes} disabled={readOnly} onChange={e=>dispatch({type:'NOTES',value:e.target.value})} placeholder="Capture a thought…"/><small>Private notes are not included in your submitted work sample.</small></div>:<><div className="board-description">Build your case, one piece of evidence at a time.</div>{sections.map((section,i)=>{const Icon=icons[i]; const cards=state.findings.filter(f=>f.section===section);return <div className="board-section" key={section}><div className="board-section-heading"><span className="section-number">{i+1}</span><h3>{section}</h3><span className="count">{cards.length}</span>{!readOnly&&<button className="icon-button" aria-label={`Add ${section}`} onClick={()=>add(section)}><Plus size={15}/></button>}</div>{cards.length===0?<button className="add-placeholder" disabled={readOnly} onClick={()=>add(section)}><Icon size={18}/><span>{i===0?'What does the data tell you?':i===1?'What might explain the change?':i===2?'What else would you need to know?':'What should the business do next?'}</span><Plus size={13}/></button>:cards.map(f=><article className="finding-card" key={f.id}><div className="finding-top"><Icon size={17}/><h4>{f.title}</h4>{!readOnly&&<button className="icon-button" aria-label={`Edit ${f.title}`} onClick={()=>setEditing(f)}><Pencil size={13}/></button>}</div><p>{f.detail}</p><div className="finding-meta"><span className="source-tag"><Link2 size={10}/>{f.source}</span>{section==='Hypotheses'&&<Badge tone={f.confidence==='High'?'green':'amber'}>{f.confidence}</Badge>}</div></article>)}</div>;})}
      {!readOnly&&<div className="board-demo"><button onClick={()=>setConfirmDemo(true)}><Sparkles size={13}/>Load example investigation</button><small>Optional demo starting point</small></div>}</>}
    </section></div>
    {editing&&<FindingEditor finding={editing} onClose={()=>setEditing(null)}/>}
    {confirmDemo&&<Modal title="Load example investigation?" onClose={()=>setConfirmDemo(false)}><p>This replaces your board and executive summary with editable demonstration content. Your private notes stay as they are.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setConfirmDemo(false)}>Keep my work</button><button className="button primary" onClick={()=>{dispatch({type:'LOAD_FINDINGS',...stamp()});setConfirmDemo(false);notify('Example findings loaded. Review and make them your own.');}}>Load example</button></div></Modal>}
    {showTimeline&&<Modal title="Investigation timeline" onClose={()=>setShowTimeline(false)} wide><p className="muted">An observable record of the actions taken in this workspace. Explicitly loaded demo content is labelled.</p><Timeline/></Modal>}
  </>;
}
function FindingEditor({finding,onClose}:{finding:Finding;onClose:()=>void}) {
  const {state,dispatch,notify}=useCandidate();const [form,setForm]=useState({...finding});const [error,setError]=useState('');
  const exists=state.findings.some(f=>f.id===finding.id);
  return <Modal title={`${exists?'Edit':'Add'} · ${finding.section}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(!form.title.trim()){setError('Give this card a clear title.');return;}dispatch({type:'UPSERT',finding:{...form,title:form.title.trim()},...stamp()});notify('Investigation board updated.');onClose();}}><label className="field-label" htmlFor="finding-title">Your observation or idea</label><input id="finding-title" maxLength={180} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="A clear, evidence-led statement" autoFocus/><label className="field-label" htmlFor="finding-detail">Reasoning & supporting evidence</label><textarea id="finding-detail" maxLength={2000} rows={5} value={form.detail} onChange={e=>setForm({...form,detail:e.target.value})} placeholder="What supports this? Distinguish what you observed from what you infer."/><div className="form-columns"><div><label className="field-label" htmlFor="finding-source">Evidence source</label><select id="finding-source" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}>{resources.map(r=><option key={r.name}>{r.name}</option>)}</select></div><div><label className="field-label" htmlFor="finding-confidence">Confidence</label><select id="finding-confidence" value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value as Finding['confidence']})}><option>High</option><option>Medium</option><option>Low</option></select></div></div>{error&&<p className="error-text" role="alert">{error}</p>}<div className="modal-actions">{exists&&<button type="button" className="button danger" onClick={()=>{dispatch({type:'DELETE',findingId:finding.id,...stamp()});onClose();notify('Card removed.');}}><Trash2 size={15}/>Delete card</button>}<button type="button" className="button secondary" onClick={onClose}>Cancel</button><button type="submit" className="button primary"><Check size={16}/>Save card</button></div></form></Modal>;
}
function CodeExample({language}:{language:string}) {
  const {dispatch}=useCandidate();const [run,setRun]=useState(false);const [busy,setBusy]=useState(false);
  const code=language==='SQL'?"SELECT channel, sessions, orders,\n       ROUND(100.0 * orders / sessions, 2) AS conversion_pct\nFROM website_traffic\nORDER BY conversion_pct ASC;":"# Explore conversion across channels\nimport pandas as pd\n\ntraffic = pd.read_csv('website_traffic.csv')\ntraffic['Conversion'] = traffic['Conversion'].str.rstrip('%').astype(float)\ntraffic.sort_values('Conversion')";
  return <div className="code-example"><div className="section-heading"><h2>{language} exploration</h2><Badge tone="blue">Guided example</Badge></div><p className="muted">Inspect a predefined analysis of the task dataset. This preview does not execute arbitrary code.</p><pre><code>{code}</code></pre><button className="button analytical" disabled={busy} onClick={()=>{setBusy(true);setTimeout(()=>{setRun(true);setBusy(false);dispatch({type:'EVENT',title:`Viewed ${language} example results`,detail:'Predefined demonstration output; no live code execution.',...stamp()});},350);}}><Code2 size={15}/>{busy?'Preparing example…':'Show example results'}</button>{run&&<><div className="inline-success"><Check size={14}/>Example output · 5 rows</div><div className="table-scroll"><table><thead><tr><th>Channel</th><th>Sessions</th><th>Orders</th><th>Conversion</th></tr></thead><tbody>{[...channels].sort((a,b)=>a.conversion-b.conversion).map(c=><tr key={c.channel}><td>{c.channel}</td><td>{c.traffic.toLocaleString()}</td><td>{c.orders.toLocaleString()}</td><td>{c.conversion.toFixed(2)}%</td></tr>)}</tbody></table></div><p className="analysis-footnote">Paid Search has the lowest conversion. What would you investigate next?</p></>}</div>;
}
export function WorkSample() {
  const {state,dispatch,navigate,notify}=useCandidate();const [tab,setTab]=useState('report');const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);
  const readOnly=state.stage!=='working';const issues=submissionIssues(state);
  function exportReport() {
    const text=`# Conversion Drop Investigation\n\nAlex Chen · Junior Data Analyst · HarbourCart\n\n## Executive Summary\n\n${state.summary}\n\n${sections.map(section=>`## ${section}\n\n${state.findings.filter(f=>f.section===section).map(f=>`### ${f.title}\n\n${f.detail}\n\nSource: ${f.source} · Confidence: ${f.confidence}`).join('\n\n')}`).join('\n\n')}`;
    download('Alex_Chen_Investigation.md',text,'text/markdown');notify('Investigation brief downloaded.');
  }
  return <><button className="back-link" onClick={()=>navigate('workspace')}><ArrowLeft size={15}/>Back to workspace</button><div className="page-heading"><div><div className="eyebrow">YOUR THINKING, MADE VISIBLE</div><h1>My investigation brief</h1><p>{taskTitle} · HarbourCart</p></div><div className="workspace-actions"><button className="button secondary" onClick={exportReport}><Download size={16}/>Download brief</button>{!readOnly?<button className="button primary" onClick={()=>setConfirm(true)}><Send size={16}/>Submit Work Sample</button>:<button className="button primary" onClick={()=>navigate('status')}>View review status<ArrowRight size={16}/></button>}</div></div>
    <div className="sample-grid"><section className="card report-card"><div className="report-toolbar"><div className="analysis-tabs" role="tablist" aria-label="Work sample view">{['report','timeline'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t==='report'?<FileText size={16}/>:<ListChecks size={16}/>} {t==='report'?'Final work sample':'Process evidence'}</button>)}</div><Badge tone={readOnly?'blue':'amber'}>{readOnly?'Submitted':'Draft'}</Badge></div>
      <div className="report-content">{tab==='timeline'?<><h2>Investigation timeline</h2><p className="muted">A trace of your work, alongside the final result.</p><Timeline/></>:<><div className="report-author"><div className="avatar">AC</div><div><strong>Alex Chen</strong><small>Candidate · Junior Data Analyst</small></div><span>{state.submittedAt?new Date(state.submittedAt).toLocaleDateString('en-AU'):'Investigation draft'}</span></div><section className="summary-section"><span className="report-number">01</span><h2>Executive summary</h2>{readOnly?<p className="summary-text">{state.summary}</p>:<><label className="sr-only" htmlFor="executive-summary">Executive summary</label><textarea id="executive-summary" rows={5} maxLength={3000} value={state.summary} onChange={e=>dispatch({type:'SUMMARY',value:e.target.value})} placeholder="Bring your investigation together. What matters most, how strong is the evidence, and what should happen next?"/><small>Summarise your own reasoning. The sections below come directly from your board.</small></>}</section>{sections.map((section,i)=><section className="report-section" key={section}><span className="report-number">0{i+2}</span><h2>{section==='Additional Evidence Needed'?'Data needed':section}</h2>{section==='Key Findings'&&<EvidenceExhibits findings={state.findings.filter(f=>f.section==='Key Findings')}/>}{state.findings.filter(f=>f.section===section).length===0?<p className="muted">No cards yet. <button className="text-button" onClick={()=>navigate('workspace')}>Add to your investigation board</button></p>:state.findings.filter(f=>f.section===section).map(f=><article className="report-finding" key={f.id}><h3>{f.title}</h3><p>{f.detail}</p><span className="source-tag"><Link2 size={11}/>{f.source}</span></article>)}</section>)}</>}</div>
    </section><aside><section className="card submission-checklist"><div className="eyebrow">READY FOR REVIEW</div><h2>A complete picture</h2><p>HR will see your final work and the process behind it.</p>{[...sections,'Executive summary'].map(section=>{const done=section==='Executive summary'?Boolean(state.summary.trim()):state.findings.some(f=>f.section===section);return <div className={`checklist-item ${done?'done':''}`} key={section}><span>{done?<Check size={13}/>:<span/>}</span>{section}</div>;})}<div className="review-note"><Eye size={20}/><p><strong>A human makes the final judgement.</strong><br/>Your evidence supports the review. It does not generate a candidate score.</p></div>{!readOnly&&<button className="button secondary full-width" onClick={()=>navigate('workspace')}><Pencil size={15}/>Keep investigating</button>}</section><section className="export-note"><Download size={18}/><div><strong>Keep a copy of your evidence</strong><p>Download your brief, or export the work sample and process timeline for a separate HR demo.</p><button className="text-button" onClick={()=>{download('evidencebridge-work-sample.json',JSON.stringify({schemaVersion:1,kind:'candidate-demo-work-sample',candidate:'Alex Chen',company:'HarbourCart Pty Ltd',role:'Junior Data Analyst',task:taskTitle,status:state.stage,summary:state.summary,findings:state.findings,processEvidence:state.events,submittedAt:state.submittedAt},null,2),'application/json');notify('Work sample JSON exported. Private notes are excluded.');}}>Export evidence JSON<ArrowUpRight size={13}/></button></div></section></aside></div>
    {confirm&&<Modal title={issues.length?'Complete your work sample':'Submit your work sample?'} onClose={()=>setConfirm(false)}>{issues.length?<><p>Before sending your work for review:</p><ul className="issues-list">{issues.map(issue=><li key={issue}>{issue}</li>)}</ul><div className="modal-actions"><button className="button primary" onClick={()=>setConfirm(false)}>Continue editing</button></div></>:<><p>Your investigation brief, board and process timeline will be marked as submitted. Your private notes are excluded. You can download and view the submission afterwards.</p><div className="submission-summary"><FileText size={22}/><div><strong>{taskTitle}</strong><small>{state.findings.length} evidence cards · {state.events.length} process events</small></div></div><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setConfirm(false)}>Keep editing</button><button className="button primary" disabled={busy} onClick={()=>{setBusy(true);setTimeout(()=>{dispatch({type:'SUBMIT',...stamp()});setConfirm(false);navigate('status');notify('Work sample submitted for review.');},500);}}><Send size={16}/>{busy?'Submitting…':'Confirm submission'}</button></div></>}</Modal>}
  </>;
}


function EvidenceExhibits({findings}:{findings:Finding[]}) {
  const traffic=findings.some(f=>f.source==='website_traffic.csv');
  const landing=findings.some(f=>f.source==='landing_pages.csv');
  if(!traffic&&!landing)return null;
  return <div className="evidence-exhibits">
    {traffic&&<figure><figcaption>Channel conversion <span>website_traffic.csv · current period</span></figcaption>{channels.map(c=><div className="exhibit-row" key={c.channel}><span>{c.channel}</span><div><i style={{width:`${c.conversion/5*100}%`}}/></div><strong>{c.conversion.toFixed(1)}%</strong></div>)}</figure>}
    {landing&&<figure><figcaption>Spring Sale: mobile vs. desktop <span>landing_pages.csv · illustrative segment</span></figcaption>{[{name:'Mobile',value:1},{name:'Desktop',value:2.7}].map(c=><div className="exhibit-row" key={c.name}><span>{c.name}</span><div><i style={{width:`${c.value/5*100}%`}}/></div><strong>{c.value.toFixed(1)}%</strong></div>)}<p>Mobile page load: 4.8 s · Desktop: 1.6 s</p></figure>}
  </div>;
}
