import React, { useEffect, useState, useSyncExternalStore } from 'react';
import { Sidebar, useSidebar } from '../../shared/ui';
import { useApi, type ApiState } from '../../shared/use-api';
import { AnalysisView, ApplicationSources, ApiNotice, Dialog, Heading, ProcessTimeline, ResourceList, ReviewNote, Snapshot, VersionPicker } from '../../shared/api-ui';
import { binding, decisionLabel, download, submissionBinding, workMarkdown } from '../../shared/api';
import type { Decision, Demo, Version } from '../../shared/api-types';

const nav = [{ id:'jobs', label:'Job Requirements' },{ id:'candidates', label:'Candidates' },{ id:'report', label:'Evidence Report' },{ id:'tasks', label:'Tasks' },{ id:'review', label:'Review' }];
const subscribe = (cb: () => void) => { addEventListener('hashchange', cb); return () => removeEventListener('hashchange', cb); };
const route = () => nav.some(n => n.id === location.hash.slice(1)) ? location.hash.slice(1) : 'report';
function NavIcon() { return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>; }
export default function ApiApp() {
  const api = useApi('hr'); const sidebar = useSidebar('hr'); const page = useSyncExternalStore(subscribe, route);
  const [help, setHelp] = useState(false);
  const go = (id: string) => { location.hash = id; sidebar.closeMobile(); window.scrollTo(0,0); };
  return <div className="eb-connected"><a href="#api-main" className="eb-skip eb-action">Skip to content</a><Sidebar role="hr" controller={sidebar} activePage={page} items={nav.map(n => ({ ...n, icon:<NavIcon/>, count:n.id === 'review' && api.data?.workflow.allowedReviewDecisions.length ? 1 : undefined }))} onNavigate={go} user={{ initials:'HR', name:'Hiring workspace', title:'Demo reviewer' }} helpLabel="Demo guide" onHelp={() => setHelp(true)}/><div className="eb-main" data-eb-content><header className="eb-api-topbar">{sidebar.menuButton}<span>Workspace / {nav.find(n => n.id === page)?.label}</span><small>Shared local case · Human review</small></header><main className="eb-content" id="api-main"><ApiNotice api={api}/>{api.data && <HRCase key={`${api.data.sessionId}.${api.data.task.taskId}`} data={api.data} api={api} page={page} go={go}/>}<footer className="eb-footer">EvidenceBridge · Human judgement, supported by evidence. · Preset synthetic application; API-backed work samples.</footer></main></div>{help && <Dialog title="Shared case demo" close={() => setHelp(false)}><p>Send the task, then let Candidate submit V1 from the other app. Refresh here to receive the actual work. Analyze it or review the original work directly.</p><p>Only V1 Needs More Evidence opens one V2 submission. Each version has its own analysis and decision. History is read only; V2 has no further revision.</p><p>Reset is a separate local administrator script. No notification or real email is sent. Model availability is configured on the backend; failures never block reading the work.</p></Dialog>}</div>;
}
function HRCase({ data, api, page, go }: { data: Demo; api: ApiState; page: string; go: (p:string) => void }) {
  const draftStorage = `eb.api2.hr.task.${data.sessionId}.${data.task.taskId}`;
  const [instructions, setInstructions] = useState(() => { try { return localStorage.getItem(draftStorage) ?? data.task.instructions; } catch { return data.task.instructions; } });
  const [storageError, setStorageError] = useState(false);
  const [selected, setSelected] = useState<number>(data.currentSubmissionVersion ?? 1);
  const [tab, setTab] = useState('Work sample');
  const [before, setBefore] = useState(false);
  const [decision, setDecision] = useState<Decision | null>(null);
  const [comment, setComment] = useState('');
  const [source, setSource] = useState<{ title:string; text:string; quote?:string } | null>(null);
  useEffect(() => { if (data.task.status === 'draft') { try { localStorage.setItem(draftStorage,instructions); setStorageError(false); } catch { setStorageError(true); } } }, [instructions,draftStorage,data.task.status]);
  useEffect(() => { setSelected(data.currentSubmissionVersion ?? 1); setDecision(null); setComment(''); }, [data.currentSubmissionVersion]);
  const version = data.versions.find(v => v.submission.submissionVersion === selected) ?? data.versions.at(-1);
  const current = version?.submission.submissionId === data.submission?.submissionId;
  const canWrite = api.fresh && !api.busy.includes('write') && !api.pending.some(p => p.path !== '/analysis');
  const allowed = current ? data.workflow.allowedReviewDecisions : [];
  const review = async () => {
    if (!canWrite || !decision || !allowed.includes(decision) || !comment.trim() || comment.length > 2000) return;
    if (await api.write('/review', { ...submissionBinding(data), requirementId:data.task.requirementId, decision, comment })) { setDecision(null); setComment(''); go('report'); }
  };
  const openApplicationSource = (id: string, quote?: string) => { const s = data.application.sources.find(s => s.id === id); if (s) setSource({ title:s.name, text:s.content, quote }); };
  const exportReport = () => download('evidencebridge-current-report.md', `# Current evidence report\n\n${data.candidate.name} · ${data.job.title}\n\nDataset: ${data.datasetVersion}\n\n${data.report.requirements.map(r => `## ${r.title}: ${r.displayLabel}\n\n${r.summary}\n\nRemaining uncertainty: ${r.uncertainty}`).join('\n\n')}\n\n${data.submission ? `## Current submission V${data.submission.submissionVersion}\n\n${workMarkdown(data.submission)}` : 'No work sample submitted.'}\n\n## Human decision\n\n${data.review ? `${decisionLabel(data.review.decision)}\n\n${data.review.comment}` : 'Awaiting review'}\n\nPreset application; submitted work is client supplied. Not a hiring decision.`, 'text/markdown');
  return <>
    {storageError && <p className="eb-feedback" role="alert">Task draft is kept in this tab only; browser storage is unavailable.</p>}
    {page === 'jobs' && <><Heading eyebrow={data.job.company} title="Job requirements"/><section className="eb-panel"><h2>{data.job.title}</h2><p>Fixed demonstration role · evidence-led review</p>{data.job.requirements.map(r => <section key={r.id}><h3>{r.title}</h3><p>{r.statement}</p></section>)}<button className="eb-action primary" onClick={() => go('report')}>View evidence report</button></section></>}
    {page === 'candidates' && <><Heading title="Candidates"/><section className="eb-panel"><h2>{data.candidate.name}</h2><p>{data.job.title} · {data.application.sources.length} preset materials</p><span className="eb-chip is-warning">{data.task.status}</span><div className="eb-actions"><button className="eb-action primary" onClick={() => go('report')}>View evidence report</button></div></section><section className="eb-panel"><h2>Application sources</h2><ApplicationSources data={data}/></section></>}
    {page === 'report' && <><Heading eyebrow={data.job.title} title="Evidence report"><button className="eb-action" onClick={exportReport}>Export current report</button></Heading><section className="eb-panel"><div className="eb-heading"><div><h2>{data.candidate.name}</h2><small>{data.application.id} · {data.application.sources.length} preset materials</small></div><span className="eb-chip is-warning">{data.task.status}</span></div><div className="eb-tabs" role="tablist" aria-label="Report version"><button className="eb-action" role="tab" aria-selected={!before} onClick={() => setBefore(false)}>Current report</button><button className="eb-action" role="tab" aria-selected={before} onClick={() => setBefore(true)}>Initial report</button></div><p>Initial evidence is preset and synthetic. Only human confirmation of the current task can verify its target requirement.</p></section><div className="eb-two-column"><div>{(before ? data.application.initialReport : data.report.requirements).map(r => <section className="eb-panel" key={r.requirementId}><div className="eb-heading"><h2>{data.job.requirements.find(j => j.id === r.requirementId)?.title}</h2><span className={`eb-chip ${r.status === 'uncertain' ? 'is-warning' : ''}`}>{r.displayStatus}</span></div><p className="eb-preserve">{r.summary}</p><h3>Remaining uncertainty</h3><p>{r.uncertainty}</p><small>Source mode: {r.mode}</small><div className="eb-actions">{r.sourceRefs.map((s,i) => <button className="eb-action" key={i} onClick={() => openApplicationSource(s.sourceId,s.quote)}>{s.sourceId}</button>)}</div>{!before && r.requirementId === data.task.requirementId && data.submission && <button className="eb-action" onClick={() => { setSelected(data.currentSubmissionVersion!); go('review'); }}>View current V{data.currentSubmissionVersion} work</button>}</section>)}</div><aside><section className="eb-panel"><h2>{data.task.status === 'draft' ? 'Turn uncertainty into evidence' : data.task.status === 'sent' ? 'Waiting for Candidate' : data.task.status === 'awaiting_revision' ? 'Waiting for V2 evidence' : data.workflow.isTerminal ? 'Human review complete' : 'Review the submitted work'}</h2><p>{data.task.status === 'awaiting_revision' ? 'V1 and its review are preserved. Candidate may submit V2 once, using this same task.' : 'A bounded work sample supports your judgement. It does not establish a hiring decision.'}</p><button className="eb-action primary" onClick={() => go(data.task.status === 'draft' || data.task.status === 'sent' ? 'tasks' : 'review')}>{data.task.status === 'draft' ? 'Review targeted task' : 'View task evidence'}</button></section>{data.versions.at(-1) && <ReviewNote version={data.versions.at(-1)!}/>}</aside></div></>}
    {page === 'tasks' && <><Heading title="Targeted task"/><section className="eb-panel"><span className="eb-chip is-warning">{data.task.status === 'draft' ? 'Draft · editable before sending' : 'Sent version · read only'}</span><h2>{data.task.title}</h2><p>Target: {data.job.requirements.find(r => r.id === data.task.requirementId)?.title}</p><p>{data.task.timeboxMinutes} minutes suggested · No enforced deadline</p><label className="eb-field" htmlFor="api-task-instructions">Candidate instructions</label><textarea id="api-task-instructions" maxLength={4000} value={data.task.status === 'draft' ? instructions : data.task.instructions} onChange={e => setInstructions(e.target.value)} disabled={data.task.status !== 'draft' || !canWrite}/><small>Preset task. Edit the instructions before sending; no model task generation or email delivery is claimed.</small>{data.task.status === 'draft' ? <div className="eb-actions"><button className="eb-action primary" disabled={!canWrite || !instructions.trim()} onClick={() => void api.write('/task/send', { ...binding(data), instructions })}>{api.busy.includes('write') ? 'Sending…' : 'Confirm & Send to Candidate'}</button></div> : <p>Candidate can read the sent task by refreshing their shared case.</p>}</section><section className="eb-panel"><h2>Task resources</h2><ResourceList resources={data.dataset.resources}/></section></>}
    {page === 'review' && <><Heading title="Review candidate evidence"/>{!version ? <section className="eb-panel"><h2>Waiting for a formal submission</h2><p>No work sample has been submitted to this shared case. Refresh after Candidate submits.</p></section> : <>
      <VersionPicker data={data} selected={version.submission.submissionVersion} onSelect={v => { setSelected(v); setDecision(null); setComment(''); }}/>
      {!current && <p className="eb-feedback">V{version.submission.submissionVersion} history · read only. Its analysis, citations and review belong only to this version.</p>}
      <ReviewNote version={version}/><div className="eb-tabs" role="tablist" aria-label="Evidence layers">{['Work sample','Process evidence','AI observations'].map(t => <button className="eb-action" role="tab" aria-selected={tab === t} key={t} onClick={() => setTab(t)}>{t}</button>)}</div>
      {tab === 'Work sample' && <Snapshot version={version}/>} {tab === 'Process evidence' && <ProcessTimeline events={version.submission.processEvidence}/>} {tab === 'AI observations' && <AnalysisView key={version.submission.submissionId} version={version} refresh={() => void api.refresh()}/>}
      {current && allowed.length > 0 && <section className="eb-panel"><h2>Review V{version.submission.submissionVersion}</h2><p>Analysis is optional. Its failure does not prevent a human review of the original work.</p><div className="eb-actions"><button className="eb-action" disabled={!api.fresh || api.busy.includes('analysis') || api.pending.some(p => p.path === '/analysis') || version.analysis.status === 'running' || version.analysis.status === 'succeeded'} onClick={() => { setTab('AI observations'); void api.write('/analysis', submissionBinding(data)); }}>{version.analysis.status === 'running' || api.busy.includes('analysis') ? 'Analyzing…' : version.analysis.status === 'failed' ? 'Start new analysis attempt' : 'Analyze current submission'}</button>{allowed.map(d => <button key={d} className={`eb-action ${d === 'confirm' ? 'primary' : ''}`} disabled={!canWrite} onClick={() => setDecision(d)}>{d === 'confirm' ? 'Confirm evidence' : d === 'needs_more_evidence' ? 'Needs More Evidence' : 'Evidence Still Insufficient'}</button>)}</div><p className="eb-muted">{version.submission.submissionVersion === 2 ? 'V2 is the final submission. Only confirmation or insufficient evidence can end this task.' : 'Needs More Evidence opens one V2 revision. Other decisions end this task.'}</p></section>}
    </>}</>}
    {decision && current && allowed.includes(decision) && <Dialog title={`${decisionLabel(decision)} · V${version?.submission.submissionVersion}`} close={() => setDecision(null)}><p>This decision concerns only the current Business Problem Solving work-sample evidence. Your reason is shared with Candidate.</p><label className="eb-field" htmlFor="api-review-comment">Public review reason (required)</label><textarea id="api-review-comment" maxLength={2000} value={comment} onChange={e => setComment(e.target.value)}/><small>{comment.length}/2,000 characters</small><div className="eb-actions"><button className="eb-action primary" disabled={!canWrite || !comment.trim()} onClick={() => void review()}>{api.busy.includes('write') ? 'Saving…' : 'Save review decision'}</button><button className="eb-action" onClick={() => setDecision(null)}>Cancel</button></div></Dialog>}
    {source && <Dialog title={source.title} close={() => setSource(null)}><p>Preset synthetic application source</p><SourceText source={source}/></Dialog>}
  </>;
}
function SourceText({ source }: { source: {text:string;quote?:string} }) {
  const start = source.quote ? source.text.indexOf(source.quote) : -1;
  return <pre>{start >= 0 ? <>{source.text.slice(0,start)}<mark>{source.quote}</mark>{source.text.slice(start + source.quote!.length)}</> : source.text}</pre>;
}
