import React, { Suspense, lazy } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import '../../shared/tokens.css';
import '../../shared/shell.css';
import '../../shared/connected.css';
import { initializeTheme } from '../../shared/preferences';
import { initializeRoleArrival } from '../../shared/role-navigation';
import { WorkspaceBoot } from '../../shared/workspace-boot';
document.documentElement.dataset.role = 'hr';
initializeRoleArrival('hr');
initializeTheme();
const mode = import.meta.env.VITE_APP_MODE || 'api4-connected';
const standalone = mode === 'standalone';
const App = standalone ? lazy(() => import('./LocalDemo')) : mode === 'revision5-preview' ? lazy(() => import('./Revision5App')) : mode === 'connected' ? lazy(() => import('./ApiApp')) : mode === 'api3-connected' ? lazy(() => import('./Api3App')) : lazy(() => import('./Api4App'));
createRoot(document.getElementById('root')).render(<Suspense fallback={<WorkspaceBoot role="hr"/>}>{standalone && <p className="eb-feedback">Standalone simulation · no shared API connection</p>}<App/></Suspense>);
