import React, { useRef, useEffect, useState } from 'react';
import { Dialog, Heading, ResourceList } from '../api-ui';
import { WorkflowStrip, VersionComparison } from '../workspace-ui';
import type { CandidateId, Citation, Comparison, Decision, Demo, RequirementId, SourceRef, Stage, Version } from '../api3-types';
import { baseBinding, stageContext, submissionBinding } from './client';
import type { Api3Controller } from './controller';
import { AssessmentPanel, Rubric } from './assessment';
import { GlideSelect } from '../glide-select';
import { StandardsOverview, ReviewDashboard } from './overview';
import { annotationLabel, analysisSource, compareValue, latestStage, percent, requirementNames, requirements, resolveSourceRef, sortComparison, stageNames, type CompareSort } from './hr-model';
import { ReviewNote, WorkSnapshot } from './work';

type Props = { data: Demo; comparison: Comparison; controller: Api3Controller; page: string; go: (page: string) => void; select: (id: CandidateId, page?: string) => void };
const shortlistLabel = { not_retained: 'Not retained', retained: 'Retained', needs_reconfirmation: 'Reconfirmation needed' };
const decisionLabel: Record<Decision, string> = { confirm: 'Confirm evidence', needs_more_evidence: 'Needs More Evidence', evidence_still_insufficient: 'Evidence Still Insufficient' };
export default function HRConnected({ data, comparison, controller, page, go, select }: Props) {
  const [rubric, setRubric] = useState(false), [retention, setRetention] = useState<'retain' | 'remove' | 'reconfirm' | null>(null);
  const retainedAction = data.shortlist.status === 'needs_reconfirmation' ? 'reconfirm' : 'retain';
  return <>
    {page === 'company' && <><Heading eyebrow="A concrete SME · Synthetic company" title="Hire for the work ahead"><button className="eb-action" onClick={() => setRubric(true)}>View ten assessment standards</button></Heading><section className="eb-panel r5-company"><div><span className="r5-avatar">HC</span><h2>{data.company.name}</h2><p>{data.company.location} · {data.company.products.join(', ')} · Approximately {data.company.approximateHeadcount} people · {data.company.fulfilment} fulfilment.</p><div className="r5-meta"><span>No dedicated hiring team</span><span>Company is the customer</span><span>Synthetic SME context</span></div></div><aside><small>OPEN ROLE</small><h2>{data.job.title}</h2><p>{data.company.hiringManager} reviews evidence. {data.company.budgetApprover} approves the budget. Hiring remains a human decision.</p></aside></section><div className="r5-three">{data.job.successStages.map((text, i) => <section className="eb-panel" key={text}><span className="r5-step">0{i + 1}</span><h2>{['Reconcile the numbers', 'Investigate the change', 'Recommend a testable action'][i]}</h2><p>{text}</p></section>)}</div><StandardsOverview data={data} compare={() => go('comparison')}/></>}
    {page === 'comparison' && <><ReviewDashboard comparison={comparison} select={select}/><ComparisonTable comparison={comparison} select={select} rubric={() => setRubric(true)}/></>}
    {page === 'evidence' && <><Heading eyebrow="Job evidence match · Review the basis" title={`${data.candidate.name} · evidence & marks`}><button className="eb-action" onClick={() => setRubric(true)}>View ten assessment standards</button></Heading><ReportStatus data={data}/><AssessmentPanel data={data} controller={controller}/><div className="eb-actions"><button className="eb-action" onClick={() => go('tasks')}>Explore a targeted task</button><button className="eb-action primary" disabled={data.shortlist.status === 'retained' || controller.busy || !!controller.pending} onClick={() => setRetention(retainedAction)}>{data.shortlist.status === 'needs_reconfirmation' ? 'Reconfirm with current basis' : data.shortlist.status === 'retained' ? 'Already retained' : 'Human retain decision'}</button></div></>}
    {page === 'tasks' && <><Heading eyebrow="Only ask for the missing evidence" title="Targeted task"/>{data.workflow.canSend ? <TaskComposer key={data.task.taskId} data={data} controller={controller}/> : <TaskReview key={data.task.taskId} data={data} controller={controller}/>}</>}
    {page === 'shortlist' && <><Heading eyebrow="Human selection · independent of marks" title="Retained for further comparison"><button className="eb-action" onClick={() => go('comparison')}>View all four candidates</button></Heading><p>Retaining is not hiring. Removing is not rejecting an application. Any of the four candidates can be retained; there is no automatic top-three limit.</p><div className="r5-two">{comparison.candidates.map(row => {
      const record = row.shortlist, selected = row.candidate.id === data.candidate.id;
      return <section className="eb-panel" key={row.candidate.id} data-candidate={row.candidate.id}><div className="eb-heading"><h2>{row.candidate.name}</h2><span className={`r5-state ${record.status === 'needs_reconfirmation' ? 'is-warning' : ''}`}>{shortlistLabel[record.status]}</span></div><p>{record.reason ?? 'No human retain decision yet.'}</p>{record.basis && <details open={record.status === 'needs_reconfirmation'}><summary>Decision basis</summary><p>{stageNames[record.basis.stage]} · {record.basis.assessmentRevision === null ? 'Not assessed' : `Assessment revision ${record.basis.assessmentRevision}`} · {record.basis.rubricVersion}</p><small>{record.basis.evidenceSnapshotId}</small></details>}{record.status === 'needs_reconfirmation' && <p className="eb-feedback">New work or an assessment dependency changed. The original reason and basis remain until you explicitly reconfirm.</p>}<details><summary>Shortlist history · {record.history.length} actions</summary>{record.history.length ? record.history.map(event => <article key={event.revision}><strong>Revision {event.revision} · {event.action}</strong><p>{event.reason}</p><small>{event.operatorLabel} · {new Date(event.at).toLocaleString()}</small><p>{stageNames[event.basis.stage]} · assessment {event.basis.assessmentRevision ?? 'not assessed'} · {event.basis.evidenceSnapshotId}</p></article>) : <p>No saved actions.</p>}</details><div className="eb-actions"><button className="eb-action" onClick={() => select(row.candidate.id, 'evidence')}>Inspect {row.candidate.name} evidence</button>{!selected ? <button className="eb-action primary" onClick={() => select(row.candidate.id, 'shortlist')}>Manage {row.candidate.name} shortlist</button> : <>{record.status !== 'retained' && <button className="eb-action primary" disabled={controller.busy || !!controller.pending} onClick={() => setRetention(record.status === 'needs_reconfirmation' ? 'reconfirm' : 'retain')}>{record.status === 'needs_reconfirmation' ? 'Reconfirm with current basis' : 'Retain candidate'}</button>}{record.status !== 'not_retained' && <button className="eb-action" disabled={controller.busy || !!controller.pending} onClick={() => setRetention('remove')}>Remove from retained</button>}</>}</div></section>;
    })}</div></>}
    {rubric && <Rubric data={data} close={() => setRubric(false)}/>}
    {retention && <RetentionDialog data={data} action={retention} controller={controller} close={() => setRetention(null)}/>}
  </>;
}

function ComparisonTable({ comparison, select, rubric }: { comparison: Comparison; select: Props['select']; rubric: () => void }) {
  const [sort, setSort] = useState<CompareSort>('default'), [limit, setLimit] = useState(false);
  const sorted = sortComparison(comparison.candidates, sort), visible = limit ? sorted.slice(0, 3) : sorted;
  return <><Heading eyebrow={`${comparison.company.name} · ${comparison.job.title}`} title="Compare candidate evidence"><button className="eb-action" onClick={rubric}>View ten assessment standards</button></Heading><div className="r5-three r5-summary"><div><strong>{comparison.candidates.length}</strong><span>synthetic candidate profiles</span></div><div><strong>{comparison.candidates.filter(row => row.assessment?.score.complete).length}/4</strong><span>complete application assessments</span></div><div><strong>{comparison.candidates.filter(row => row.shortlist.status !== 'not_retained').length}</strong><span>human retain choices on the shared service</span></div></div>
    <section className="eb-panel r5-comparison"><div className="r5-table-toolbar"><div><h2>Application evidence comparison</h2><small>Same role · {comparison.rubricVersion} · Application materials only</small></div><label>Sort by<GlideSelect ariaLabel="Compare sort" value={sort} onChange={value => setSort(value as CompareSort)} options={[{value: 'default', label: 'Display order · not a recommendation'}, {value: 'overall', label: 'Overall · complete assessments only'}, ...requirements.map(r => ({value:r, label:`${requirementNames[r]} · complete skill only`}))]}/></label></div><p className="eb-muted">{comparison.sortPolicy} {comparison.limitations}</p>
      <div className="eb-table-scroll"><table className="r5-compare-table"><thead><tr><th>Candidate / evidence</th><th>SQL</th><th>DA</th><th>BPS</th><th>Overall</th><th>Coverage</th><th>Human shortlist</th><th>Actions</th></tr></thead><tbody>{visible.map(row => {
        const scores = row.assessment?.score, value = compareValue(row, sort), tied = value !== null && comparison.candidates.filter(other => compareValue(other, sort) === value).length > 1;
        const question = row.assessment?.items.find(item => item.mark === 'NE') ?? row.assessment?.items.find(item => typeof item.mark === 'number' && item.mark < 3);
        const support = row.assessment?.items.find(item => typeof item.mark === 'number' && item.mark >= 3);
        return <tr key={row.candidate.id} data-candidate={row.candidate.id}><td><button className="r5-person-link" onClick={() => select(row.candidate.id, 'evidence')}><span className="r5-avatar">{row.candidate.name.split(' ').map(n => n[0]).join('')}</span><strong>{row.candidate.name}</strong></button><small>{support ? `${support.criterionId}: ${support.support}` : row.candidate.background}</small><small className="r5-gap">Question: {question?.nextStep ?? 'Review the stated limits and independent authorship.'}</small>{tied && <span className="r5-state">Tied on selected comparison</span>}{sort !== 'default' && value === null && <span className="r5-state">Not ranked · incomplete evidence</span>}</td>{requirements.map(r => { const skill = scores?.skills.find(s => s.requirementId === r); return <td key={r}><div className="r5-skill-cell"><strong>{skill?.percentage != null ? percent(skill.percentage) : !skill || skill.pendingCount ? 'Not assessed' : 'Needs evidence'}</strong>{skill?.percentage != null ? <span className="r5-score-track" aria-hidden="true"><i style={{ width: `${skill.percentage}%` }}/></span> : <small>{!skill || skill.pendingCount ? 'Not assessed' : 'NE · incomplete skill'}</small>}</div></td>; })}<td><strong>{scores?.overallPercentage != null ? percent(scores.overallPercentage) : scores?.status === 'needs_evidence' ? 'Needs evidence' : 'Not assessed'}</strong>{scores?.overallPercentage == null && <small>{scores?.status === 'needs_evidence' ? 'NE present · no overall %' : 'Not fully assessed'}</small>}</td><td><strong>{scores?.coveragePercent == null ? 'Not assessed' : `${scores.criteria.filter(c => typeof c.mark === 'number').length}/10`}</strong><small>{percent(scores?.coveragePercent)} evidence coverage</small><details><summary>Assessed points</summary>{scores?.accruedScore.toFixed(1) ?? '—'}/100 accumulated · not scaled up</details></td><td><span className={`r5-state ${row.shortlist.status === 'needs_reconfirmation' ? 'is-warning' : ''}`}>{shortlistLabel[row.shortlist.status]}</span><small>Application · {annotationLabel(row.assessment?.annotationMode)} · revision {row.assessment?.assessmentRevision ?? '—'}</small><small>Task: {row.task.status.replaceAll('_', ' ')}</small>{row.taskAssessments.length > 0 && <small>Task assessments remain separate from this comparison.</small>}</td><td><div className="r5-row-actions"><button className="eb-action" aria-label={`Open ${row.candidate.name}`} onClick={() => select(row.candidate.id, 'evidence')}>View evidence</button><button className="eb-action" aria-label={`Retain ${row.candidate.name}`} onClick={() => select(row.candidate.id, 'shortlist')}>Human shortlist</button></div></td></tr>;
      })}</tbody></table></div><div className="r5-table-footer"><span>Showing {visible.length} / 4 · everyone remains available</span><button className="eb-action" onClick={() => setLimit(!limit)}>{limit ? 'View all four' : 'Preview three-row view'}</button></div>
    </section><p className="eb-muted">NE means insufficient material, not zero. Missing scores have no rank. Percentages describe evidence against this role’s standards, not hiring probability. Preset annotations use synthetic materials; human calibration remains pending.</p></>;
}

function RetentionDialog({ data, action, controller, close }: { data: Demo; action: 'retain' | 'remove' | 'reconfirm'; controller: Api3Controller; close: () => void }) {
  // Freeze all versions on entry so background updates cannot change the basis of the human decision.
  const [view] = useState(() => structuredClone(data));
  const [stage, setStage] = useState<Stage>(action === 'remove' && view.shortlist.basis ? view.shortlist.basis.stage : latestStage(view));
  const [reason, setReason] = useState(view.shortlist.reason ?? ''), [operator, setOperator] = useState('');
  const context = stageContext(view, stage)!;
  const savedBasis = action === 'remove' ? view.shortlist.basis : null;
  const basis = savedBasis ?? { stage, evidenceSnapshotId: context.evidenceSnapshotId, fingerprint: context.fingerprint, assessmentRevision: context.assessment?.assessmentRevision ?? null, rubricVersion: view.rubricVersion };
  return <Dialog title={`${action === 'remove' ? 'Remove' : action === 'reconfirm' ? 'Reconfirm' : 'Retain'} ${view.candidate.name}`} close={close}><p>Human shortlist action, independent of evidence review and assessment. No applicant is hired, rejected or deleted.</p>{!savedBasis && <label className="eb-field">Decision material stage<GlideSelect ariaLabel="Shortlist basis stage" value={stage} onChange={value => setStage(value as Stage)} options={[{value:'application_review',label:'Application materials'}, ...view.versions.filter(v => v.submission.submissionVersion === view.currentSubmissionVersion).map(v => ({value:`task_v${v.submission.submissionVersion}`,label:`Task V${v.submission.submissionVersion} · current`}))]}/></label>}<div className="r5-formula"><strong>Basis you are choosing</strong><p>{stageNames[basis.stage]} · {basis.assessmentRevision === null ? 'Not assessed' : `Assessment revision ${basis.assessmentRevision}`} · {basis.rubricVersion}</p><small>{basis.evidenceSnapshotId}</small><p>Expected shortlist revision: {view.shortlist.revision}</p>{savedBasis && <p>Removal records the original retained basis, even if that assessment is now historical.</p>}</div><label className="eb-field">Human shortlist reason<textarea aria-label="Human shortlist reason" maxLength={2000} value={reason} onChange={e => setReason(e.target.value)}/></label><label className="eb-field">Operator label<input aria-label="Shortlist operator label" maxLength={120} value={operator} onChange={e => setOperator(e.target.value)}/></label><p className="eb-muted">Demo audit label, not authenticated identity.</p>{controller.error && <p role="alert">{controller.error.message} · Input retained; inspect changed evidence before reopening against a newer basis.</p>}<div className="eb-actions">{controller.pending && <button className="eb-action" disabled={controller.busy} onClick={async () => { if (await controller.retry()) close(); }}>Retry original action</button>}<button className="eb-action primary" disabled={controller.busy || !!controller.pending || !reason.trim() || !operator.trim()} onClick={async () => { if (await controller.write('/shortlist', { ...baseBinding(view), action, reason: reason.trim(), ...basis, expectedShortlistRevision: view.shortlist.revision, operatorLabel: operator.trim() })) close(); }}>{controller.busy ? 'Saving…' : 'Save shortlist decision'}</button><button className="eb-action" onClick={close}>Cancel</button></div></Dialog>;
}

function TaskComposer({ data, controller }: { data: Demo; controller: Api3Controller }) {
  const [view] = useState(() => data);
  const [target, setTarget] = useState<RequirementId>('business-problem-solving');
  const [instructions, setInstructions] = useState(view.taskTemplates['business-problem-solving'].instructions), [reason, setReason] = useState('');
  const template = view.taskTemplates[target];
  return <section className="eb-panel"><h2>Choose the gap, then the task</h2><p>All candidates can receive one SQL, DA or BPS task. Material that already answers the question does not require a task.</p><label className="eb-field">Target skill<GlideSelect ariaLabel="Target skill" value={target} onChange={selected => { const value = selected as RequirementId; setTarget(value); setInstructions(view.taskTemplates[value].instructions); }} options={requirements.map(r => ({value:r, label:requirementNames[r]}))}/></label><h3>{template.title}</h3><label className="eb-field">Evidence gap / task reason<textarea aria-label="Evidence gap / task reason" maxLength={2000} value={reason} onChange={e => setReason(e.target.value)}/></label><label className="eb-field">Candidate instructions<textarea aria-label="Candidate instructions" maxLength={4000} value={instructions} onChange={e => setInstructions(e.target.value)}/></label><p className="eb-muted">Fixed template · {template.timeboxMinutes} minutes suggested · No deadline-based rejection. Target stays fixed after sending. No generated task or email is claimed.</p><details><summary>Task-provided shared resources</summary><ResourceList resources={view.dataset.resources.filter(r => template.resourceIds.includes(r.id))}/></details><button className="eb-action primary" disabled={controller.busy || !!controller.pending || !instructions.trim() || !reason.trim()} onClick={() => void controller.write('/task/send', { ...baseBinding(view), taskId: view.task.taskId, targetRequirementId: target, templateId: template.templateId, instructions, gapReason: reason })}>{controller.busy ? 'Sending…' : 'Send task'}</button></section>;
}

function TaskReview({ data, controller }: { data: Demo; controller: Api3Controller }) {
  const [selected, setSelected] = useState(data.currentSubmissionVersion ?? 1), [decision, setDecision] = useState<Decision | null>(null), [comment, setComment] = useState('');
  const [assessmentEditing, setAssessmentEditing] = useState(false);
  const seenVersion = useRef(data.currentSubmissionVersion);
  useEffect(() => { if (!decision && !assessmentEditing && data.currentSubmissionVersion && data.currentSubmissionVersion !== seenVersion.current) { setSelected(data.currentSubmissionVersion); seenVersion.current = data.currentSubmissionVersion; } }, [data.currentSubmissionVersion, decision, assessmentEditing]);
  const version = data.versions.find(v => v.submission.submissionVersion === selected), current = version?.submission.submissionId === data.submission?.submissionId;
  const [reviewBinding, setReviewBinding] = useState<Record<string, unknown> | null>(null);
  return <><WorkflowStrip status={data.workflow.isTerminal ? 'closed' : data.task.status} version={data.currentSubmissionVersion ?? 1}/><section className="eb-panel"><div className="eb-heading"><h2>{data.task.title}</h2><span className="r5-state">{data.task.status.replaceAll('_', ' ')}</span></div><p><strong>Target:</strong> {data.task.targetRequirementId && requirementNames[data.task.targetRequirementId]} · <strong>Gap:</strong> {data.task.gapReason}</p><details><summary>Sent task brief</summary><p className="eb-preserve">{data.task.instructions}</p></details><small>Fixed target · {data.task.timeboxMinutes} minutes suggested · One V1 and at most one permitted V2</small><details><summary>Task-provided shared resources</summary><ResourceList resources={data.dataset.resources.filter(r => !!data.task.targetRequirementId && data.taskTemplates[data.task.targetRequirementId].resourceIds.includes(r.id))}/></details></section>
    {!version ? <section className="eb-panel"><h2>Waiting for {data.candidate.name}’s work</h2><p>Candidate can read the shared task and submit their own work. Refresh after they submit; no prefilled answer is submitted automatically.</p></section> : <><label className="eb-field">Submission version<GlideSelect ariaLabel="Submission version" value={String(selected)} onChange={value => { setSelected(Number(value) as 1 | 2); setDecision(null); setComment(''); }} options={data.versions.map(v => ({value:String(v.submission.submissionVersion),label:`V${v.submission.submissionVersion}${v.submission.submissionId === data.submission?.submissionId ? ' · current' : ' · history, read only'}`}))}/></label><ReviewNote version={version}/>{data.versions.length === 2 && <VersionComparison before={data.versions[0].submission} after={data.versions[1].submission}/>}
      <TaskEvidence key={version.submission.submissionId} data={data} version={version} controller={controller} current={current}/>
      {current && !version.review && <section className="eb-panel"><h2>Human evidence review · V{selected}</h2><p>Review the work against the task target. Confirmation neither awards full marks nor retains the candidate.</p><div className="eb-actions">{data.workflow.allowedReviewDecisions.map(d => <button className="eb-action" key={d} disabled={controller.busy || !!controller.pending} onClick={() => { setDecision(d); setComment(''); setReviewBinding(submissionBinding(data)); }}>{decisionLabel[d]}</button>)}</div></section>}
      <details className="eb-panel"><summary>Human rubric assessment · V{selected}</summary><AssessmentPanel key={version.submission.submissionId} data={data} controller={controller} initialStage={`task_v${selected}`} onEditingChange={setAssessmentEditing}/></details>
    </>}
    {decision && version && reviewBinding && <Dialog title={`V${selected} · human review`} close={() => setDecision(null)}><p>Public feedback to {data.candidate.name}. Explain the gap; avoid supplying a complete reference answer.</p>{(!current || version.review) && <p role="alert">This version changed or was already reviewed while your form was open. Your comment remains here to copy. Close this form and inspect the current work; the old review is read only.</p>}<label className="eb-field">Public review comment<textarea aria-label="Public review comment" maxLength={2000} value={comment} onChange={e => setComment(e.target.value)}/></label>{controller.error && <p role="alert">{controller.error.message} · Your comment is retained.</p>}{controller.pending && <button className="eb-action" disabled={controller.busy} onClick={async () => { if (await controller.retry()) setDecision(null); }}>Retry original action</button>}<button className="eb-action primary" disabled={controller.busy || !!controller.pending || !comment.trim() || !current || !!version.review} onClick={async () => { if (await controller.write('/review', { ...reviewBinding, decision, comment })) setDecision(null); }}>{controller.busy ? 'Saving…' : 'Save evidence review'}</button></Dialog>}
  </>;
}

function TaskEvidence({ data, version, controller, current }: { data: Demo; version: Version; controller: Api3Controller; current: boolean }) {
  const [citation, setCitation] = useState<Citation | null>(null);
  const source = citation ? analysisSource(version, citation) : null, mark = useRef<HTMLElement>(null);
  const result = version.analysis.result, submission = version.submission;
  const valid = !result || (version.analysis.submissionId === submission.submissionId && version.analysis.contentFingerprint === submission.contentFingerprint && result.submissionId === submission.submissionId && result.contentFingerprint === submission.contentFingerprint);
  useEffect(() => { if (citation) mark.current?.scrollIntoView({ block: 'center' }); }, [citation]);
  return <div className="eb-review-grid"><div>{citation && <section className="eb-panel" aria-label="Selected source quotation"><div className="eb-heading"><h2>V{submission.submissionVersion} · exact source</h2><button className="eb-action" onClick={() => setCitation(null)}>Clear quotation</button></div>{source ? <><small>{source.sourceId} · {source.location}</small><pre data-source-version={submission.submissionId}>{source.text.slice(0, citation.start)}<mark ref={mark}>{source.text.slice(citation.start, citation.end)}</mark>{source.text.slice(citation.end)}</pre></> : <p role="alert">This quotation does not match this submitted version. No different source has been substituted.</p>}</section>}<WorkSnapshot data={data} version={version}/></div><aside><section className="eb-panel"><h2>{data.task.targetRequirementId && requirementNames[data.task.targetRequirementId]} observations</h2><p>Analysis: <strong>{version.analysis.status}</strong> · configured mode: {data.capabilities.analysisMode}</p>{!data.capabilities.analysisAvailable && <p className="eb-feedback">{data.capabilities.analysisUnavailableReason} · Original work and human review remain available.</p>}{version.analysis.errorCode && <p role="status">{version.analysis.errorCode} · Saved work remains available for manual review.</p>}{current && !version.review && data.capabilities.analysisAvailable && version.analysis.status !== 'succeeded' && <button className="eb-action" disabled={controller.busy || !!controller.pending || controller.analysisBusy || !!controller.analysisPending || version.analysis.status === 'running'} onClick={() => void controller.write('/analysis', submissionBinding(data))}>Run evidence analysis</button>}{version.analysis.status === 'running' && <button className="eb-action" onClick={() => void controller.refresh()}>Refresh analysis</button>}<p className="eb-muted">Observed text is not a quality score; not observed is not 0. Analysis never decides a mark, shortlist or hiring outcome. SQL is reviewed statically, not executed.</p></section>
      {!valid && <p role="alert">Analysis binding differs from the selected work. Refresh the shared case.</p>}{valid && result ? <><section className="eb-panel"><strong>{result.mode === 'manual_simulation' ? 'Manual rules simulation · not a model run' : result.mode === 'live' ? 'Server-side model extraction' : 'Saved model result · replay'}</strong><p>{result.model ?? 'Deterministic text rules'} · {result.provenance.generatedAt}</p><small>{result.promptVersion}</small></section><div className="eb-observation-map" aria-label="Observation coverage">{result.observations.map(o => <div key={o.dimension} data-observed={o.status === 'observed'}><strong>{o.dimension}</strong><small>{o.status === 'observed' ? 'Text present' : 'Not observed'}</small></div>)}</div>{result.observations.map(o => <article className="eb-panel" key={o.dimension}><div className="eb-heading"><h3>{o.dimension}</h3><span className="eb-chip">{o.status === 'observed' ? 'Observed text evidence' : 'Not observed'}</span></div><p>{o.statement}</p><p><strong>Scope:</strong> {o.scope}</p><p><strong>Uncertainty:</strong> {o.uncertainty}</p>{o.citations.map((c, i) => <button className="eb-citation" key={i} onClick={() => setCitation(c)}>{c.quote}<small>Locate source ←</small></button>)}</article>)}</> : !result && <section className="eb-panel"><p>No observation result for this version. Review the original work directly.</p></section>}
    </aside></div>;
}

function ReportStatus({ data }: { data: Demo }) {
  const [ref, setRef] = useState<SourceRef | null>(null);
  const context = ref ? ref.evidenceSnapshotId === data.application.evidenceSnapshotId ? stageContext(data, 'application_review') : (() => { const version = data.versions.find(v => v.evidenceSnapshotId === ref.evidenceSnapshotId); return version ? stageContext(data, `task_v${version.submission.submissionVersion}`) : null; })() : null;
  const source = ref && context ? resolveSourceRef(data.candidate.id, context, ref) : null;
  return <details className="eb-panel"><summary>Evidence review status · separate from marks</summary><p>Evidence confirmation is not a rubric score or a hiring decision. Only the task target changes after human review.</p><div className="r5-three">{data.report.requirements.map(r => <section key={r.requirementId}><h3>{r.title} · {r.status}</h3><p>{r.summary}</p><p>{r.uncertainty}</p><small>{r.scope} · {r.mode} · {r.evidenceSnapshotId}</small>{r.sourceRefs.map((quote, i) => <button className="eb-citation" key={i} onClick={() => setRef(quote)}>{quote.quote}<small>Locate report source ←</small></button>)}</section>)}</div>{ref && <Dialog title={`${data.candidate.name} · report source`} close={() => setRef(null)}>{source ? <><small>{source.sourceId} · {source.location} · {ref.evidenceSnapshotId}</small><pre>{source.text.slice(0, ref.start)}<mark>{source.text.slice(ref.start, ref.end)}</mark>{source.text.slice(ref.end)}</pre></> : <p role="alert">This report citation does not match an owned material snapshot.</p>}</Dialog>}</details>;
}
