import { assessmentReport } from './report';
import { SpotlightCard } from '../gold-interactions';
import React, { useState } from 'react';
import type { Demo, Version } from '../api3-types';
import { decisionLabel, download, workMarkdown } from '../api';
import { Dialog, ProcessTimeline } from '../api-ui';
import { sections } from './candidate-draft';

export function ReviewNote({ version }: { version: Version }) {
  return version.review ? <section className="eb-panel eb-review-note"><h3>V{version.submission.submissionVersion} · {decisionLabel(version.review.decision)}</h3><p className="eb-preserve">{version.review.comment}</p><small>{new Date(version.review.reviewedAt).toLocaleString()} · Public human evidence review · only the target skill · no automatic score or hiring decision</small></section> : <p className="eb-muted">V{version.submission.submissionVersion} is awaiting evidence review. No earlier review has been substituted.</p>;
}

export function WorkSnapshot({ data, version }: { data: Demo; version: Version }) {
  const [resourceId, setResourceId] = useState<string | null>(null);
  const s = version.submission, resource = data.dataset.resources.find(r => r.id === resourceId);
  return <><section className="eb-panel" data-submission-id={s.submissionId}><div className="eb-heading"><div><h2>V{s.submissionVersion} · public work snapshot</h2><small>{data.candidate.name} · {new Date(s.submittedAt).toLocaleString()} · immutable server snapshot</small></div><button className="eb-action" onClick={() => download(`${data.candidate.id}-${s.submissionId}-v${s.submissionVersion}-work.md`, `# ${data.candidate.name} · V${s.submissionVersion}\n\nSubmission: ${s.submissionId}\nDataset: ${s.datasetVersion}\nFingerprint: ${s.contentFingerprint}\n\n${workMarkdown(s)}`, 'text/markdown')}>Export V{s.submissionVersion} public work</button></div><details><summary>Snapshot details</summary><small>Snapshot: {version.evidenceSnapshotId} · stored contract {s.schemaVersion}</small></details><button className="eb-action" onClick={() => download(`${data.candidate.id}-v${s.submissionVersion}-assessment-report.md`, assessmentReport(data, `task_v${s.submissionVersion}`), "text/markdown")}>Export V{s.submissionVersion} assessment report</button><h3>Executive summary</h3><p className="eb-preserve">{s.summary}</p>{sections.map(section => <section key={section}><h3>{section}</h3>{s.findings.filter(f => f.section === section).map(f => <SpotlightCard as="article" className="eb-finding" key={f.id}><h4>{f.title}</h4><p className="eb-preserve">{f.detail}</p><small>Self-reported confidence: {f.confidence} · </small>{f.source ? <button className="eb-source-link" onClick={() => setResourceId(f.source)}>Task resource: {data.dataset.resources.find(r => r.id === f.source)?.name ?? f.source}</button> : <small>No source supplied</small>}</SpotlightCard>)}{!s.findings.some(f => f.section === section) && <p className="eb-muted">No cards supplied in this section.</p>}</section>)}<details><summary>Formal source text and locations</summary><p>These sources belong to this specific submission; task resources are shared material, not candidate-authored evidence.</p>{s.sources.map(source => <section key={`${source.sourceId}:${source.location}`}><small>{source.sourceId} · {source.location} · {source.kind}</small><pre>{source.text}</pre></section>)}</details></section><ProcessTimeline events={s.processEvidence}/>{resourceId && <Dialog title={resource?.name ?? 'Source unavailable'} close={() => setResourceId(null)}>{resource ? <><p>Task-provided shared resource · {resource.datasetVersion}</p><pre>{resource.content}</pre></> : <p>This resource is absent from the current dataset. No replacement has been substituted.</p>}</Dialog>}</>;
}
