// Generated by python scripts/frontend-types.py from API 2.0 OpenAPI. Do not hand edit.
export type Envelope = {
"data": {
"schemaVersion": "2.0";
"sessionId": string;
"datasetVersion": string;
"revision": number;
"candidate": {
"id": string;
"name": string;
};
"job": {
"id": string;
"title": string;
"company": string;
"requirements": Array<{
"id": string;
"title": string;
"statement": string;
}>;
};
"application": {
"id": string;
"mode": string;
"sources": Array<{
"id": string;
"name": string;
"kind": string;
"provenance": string;
"content": string;
}>;
"initialReport": Array<{
"requirementId": string;
"status": string;
"displayStatus": string;
"mode": string;
"summary": string;
"uncertainty": string;
"sourceRefs": Array<{
"sourceId": string;
"locator": string;
"quote": string;
}>;
}>;
};
"dataset": {
"version": string;
"provenance": string;
"records": Array<{
"id": string;
"period": string;
"channel": string;
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
}>;
"metrics": {
"previous": {
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
"conversionPct": number;
};
"current": {
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
"conversionPct": number;
};
"change": {
"trafficPct": number;
"ordersPct": number;
"adSpendPct": number;
"conversionPercentagePoints": number;
};
};
"channels": Array<{
"id": string;
"channel": string;
"traffic": number;
"growth": number;
"orders": number;
"conversion": number;
"previous": number;
"revenue": number;
"trafficSharePct": number;
"before": {
"id": string;
"period": string;
"channel": string;
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
};
"current": {
"id": string;
"period": string;
"channel": string;
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
};
}>;
"trafficTrend": Array<{
"period": string;
"label": string;
"sessions": number;
"traffic": number;
"orders": number;
"conversion": number;
}>;
"resources": Array<{
"id": string;
"name": string;
"datasetVersion": string;
"provenance": string;
"mimeType": string;
"description": string;
"columns": Array<string>;
"rows": Array<Array<string>>;
"content": string;
"sizeBytes": number;
"text"?: string;
}>;
};
"task": {
"id": string;
"taskId": string;
"requirementId": string;
"title": string;
"instructions": string;
"timeboxMinutes": number;
"timeboxEnforced": boolean;
"mode": string;
"resourceIds": Array<string>;
"status": "draft" | "sent" | "submitted" | "awaiting_revision" | "reviewed";
"sentAt": string | null;
};
"submission": {
"schemaVersion": "2.0";
"sessionId": string;
"taskId": string;
"datasetVersion": string;
"candidateId": string;
"submissionVersion": 1 | 2;
"previousSubmissionId": string | null;
"previousContentFingerprint": string | null;
"summary": string;
"findings": Array<{
"id": string;
"section": "Key Findings" | "Hypotheses" | "Additional Evidence Needed" | "Recommended Next Steps";
"title": string;
"detail": string;
"source": string;
"confidence": "High" | "Medium" | "Low";
}>;
"processEvidence": Array<{
"id": string;
"at": string;
"title": string;
"detail"?: string;
}>;
"submissionId": string;
"submittedAt": string;
"contentFingerprint": string;
"processEvidenceProvenance": "client_reported";
"sources": Array<{
"sourceId": string;
"location": string;
"text": string;
"kind": "work_sample" | "client_reported_event";
}>;
} | null;
"analysis": {
"status": "not_started" | "running" | "succeeded" | "failed";
"attemptId": string | null;
"submissionId": string | null;
"contentFingerprint": string | null;
"startedAt": string | null;
"finishedAt": string | null;
"errorCode": string | null;
"result": {
"mode": "live" | "manual_simulation" | "replay";
"model": string | null;
"promptVersion": string;
"submissionId": string;
"contentFingerprint": string;
"observations": Array<{
"dimension": "Problem Framing" | "Evidence Navigation" | "Hypothesis Formation" | "Evidence Seeking" | "Decision Making";
"status": "observed" | "not_observed";
"statement": string;
"citations": Array<{
"sourceId": string;
"location": string;
"quote": string;
"start": number;
"end": number;
}>;
"scope": string;
"uncertainty": string;
}>;
"provenance": {
"provider": "openai" | "manual_rules";
"generatedAt": string;
"responseId": string | null;
"processEvidence": "client_reported";
};
} | null;
};
"review": {
"schemaVersion": "2.0";
"sessionId": string;
"taskId": string;
"datasetVersion": string;
"submissionId": string;
"contentFingerprint": string;
"requirementId": string;
"decision": "confirm" | "needs_more_evidence" | "evidence_still_insufficient";
"comment": string;
"reviewId": string;
"reviewedAt": string;
} | null;
"currentSubmissionVersion": 1 | 2 | null;
"versions": Array<{
"submission": {
"schemaVersion": "2.0";
"sessionId": string;
"taskId": string;
"datasetVersion": string;
"candidateId": string;
"submissionVersion": 1 | 2;
"previousSubmissionId": string | null;
"previousContentFingerprint": string | null;
"summary": string;
"findings": Array<{
"id": string;
"section": "Key Findings" | "Hypotheses" | "Additional Evidence Needed" | "Recommended Next Steps";
"title": string;
"detail": string;
"source": string;
"confidence": "High" | "Medium" | "Low";
}>;
"processEvidence": Array<{
"id": string;
"at": string;
"title": string;
"detail"?: string;
}>;
"submissionId": string;
"submittedAt": string;
"contentFingerprint": string;
"processEvidenceProvenance": "client_reported";
"sources": Array<{
"sourceId": string;
"location": string;
"text": string;
"kind": "work_sample" | "client_reported_event";
}>;
};
"analysis": {
"status": "not_started" | "running" | "succeeded" | "failed";
"attemptId": string | null;
"submissionId": string | null;
"contentFingerprint": string | null;
"startedAt": string | null;
"finishedAt": string | null;
"errorCode": string | null;
"result": {
"mode": "live" | "manual_simulation" | "replay";
"model": string | null;
"promptVersion": string;
"submissionId": string;
"contentFingerprint": string;
"observations": Array<{
"dimension": "Problem Framing" | "Evidence Navigation" | "Hypothesis Formation" | "Evidence Seeking" | "Decision Making";
"status": "observed" | "not_observed";
"statement": string;
"citations": Array<{
"sourceId": string;
"location": string;
"quote": string;
"start": number;
"end": number;
}>;
"scope": string;
"uncertainty": string;
}>;
"provenance": {
"provider": "openai" | "manual_rules";
"generatedAt": string;
"responseId": string | null;
"processEvidence": "client_reported";
};
} | null;
};
"review": {
"schemaVersion": "2.0";
"sessionId": string;
"taskId": string;
"datasetVersion": string;
"submissionId": string;
"contentFingerprint": string;
"requirementId": string;
"decision": "confirm" | "needs_more_evidence" | "evidence_still_insufficient";
"comment": string;
"reviewId": string;
"reviewedAt": string;
} | null;
}>;
"workflow": {
"maxSubmissions": 2;
"submissionsUsed": number;
"remainingSubmissions": number;
"canSubmit": boolean;
"canResubmit": boolean;
"nextSubmissionVersion": 1 | 2 | null;
"allowedReviewDecisions": Array<"confirm" | "needs_more_evidence" | "evidence_still_insufficient">;
"isTerminal": boolean;
};
"report": {
"mode": string;
"isHiringDecision": false;
"review": {
"schemaVersion": "2.0";
"sessionId": string;
"taskId": string;
"datasetVersion": string;
"submissionId": string;
"contentFingerprint": string;
"requirementId": string;
"decision": "confirm" | "needs_more_evidence" | "evidence_still_insufficient";
"comment": string;
"reviewId": string;
"reviewedAt": string;
} | null;
"requirements": Array<{
"requirementId": string;
"status": string;
"displayStatus": string;
"mode": string;
"summary": string;
"uncertainty": string;
"sourceRefs": Array<{
"sourceId": string;
"locator": string;
"quote": string;
}>;
"title": string;
"displayLabel": string;
"review": {
"schemaVersion": "2.0";
"sessionId": string;
"taskId": string;
"datasetVersion": string;
"submissionId": string;
"contentFingerprint": string;
"requirementId": string;
"decision": "confirm" | "needs_more_evidence" | "evidence_still_insufficient";
"comment": string;
"reviewId": string;
"reviewedAt": string;
} | null;
"submissionSourceRefs": Array<{
"submissionId": string;
"contentFingerprint": string;
"sourceId": string;
"location": string;
}>;
}>;
};
};
"meta": {
"replayed": boolean;
};
};
export type Demo = Envelope['data'];
export type Submission = NonNullable<Demo['submission']>;
export type Finding = Submission['findings'][number];
export type ProcessEvent = Submission['processEvidence'][number];
export type Version = Demo['versions'][number];
export type Citation = NonNullable<Demo['analysis']['result']>['observations'][number]['citations'][number];
export type Resource = Demo['dataset']['resources'][number];
export type Decision = NonNullable<Demo['review']>['decision'];
