// Generated by python3 scripts/frontend-types-v4.py from API4 OpenAPI. Do not hand edit.
export type Envelope = {
"data": {
"schemaVersion": "4.0";
"sessionId": string;
"revision": number;
"datasetVersion": string;
"fixtureVersion": string;
"jdVersion": string;
"rubricVersion": string;
"company": {
"id": string;
"name": string;
"provenance": "user_supplied_demo_jd";
"location": string;
"businessDescription": string;
"profileScope": string;
};
"job": {
"id": string;
"title": string;
"company": string;
"requirements": Array<{
"id": string;
"title": string;
"statement": string;
}>;
"successStages": Array<string>;
"location": string;
"employmentType": string;
"experienceLevel": string;
"team": string;
"collaboratingTeams": Array<string>;
"supportedByExperiencedAnalysts": true;
"jd": {
"version": string;
"sourceId": string;
"filePath": string;
"sha256": string;
"pages": number;
"scope": string;
"source": {
"sourceId": string;
"location": string;
"text": string;
"fingerprint": string;
"sha256": string;
"downloadUrl": string;
};
"requirements": Array<{
"id": string;
"category": "essential" | "desirable" | "responsibility";
"statement": string;
"page": number;
"start": number;
"end": number;
"quote": string;
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
}>;
};
};
"rubric": {
"version": string;
"jobId": string;
"provenance": string;
"calibrationStatus": string;
"label": string;
"scope": string;
"requirements": Array<{
"id": "sql" | "data-analysis" | "business-problem-solving";
"title": string;
"maxScore": number;
"statement": string;
}>;
"marks": Array<{
"mark": number | "NE";
"meaning": string;
}>;
"criteria": Array<{
"id": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"title": string;
"observableSupport": string;
"maxScore": 10;
"anchors": {
"0": string;
"2": string;
"4": string;
};
}>;
"rules": {
"maxScore": 100;
"criterionContribution": string;
"displayDecimalPlaces": number;
"neIsZero": false;
"autoPassThreshold": null;
"rounding": string;
};
};
"assessmentComplete": boolean;
"gapSuggestions": Array<{
"gapId": string;
"stage": "application_review" | "task_v1" | "task_v2";
"assessmentRevision": number;
"evidenceSnapshotId": string;
"fingerprint": string;
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE";
"severity": "observed_problem" | "missing_evidence" | "material_gap" | "minor_gap";
"priority": number;
"priorityReason": string;
"summary": string;
"rationale": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
"requiresHumanConfirmation": true;
"suggestedFirstAction": string;
}>;
"candidate": {
"id": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"name": string;
"background": string;
};
"application": {
"id": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"evidenceSnapshotId": string;
"fingerprint": string;
"fixtureVersion": string;
"provenance": "synthetic";
"materialVersion": 1;
"scope": string;
"sources": Array<{
"sourceId": string;
"location": string;
"text": string;
"kind": "application" | "work_sample";
"provenance"?: {
"origin": "user_supplied_fictional_cv" | "synthetic_demo_work_sample";
"filePath": string;
"sha256": string;
"pageNumbers": Array<number>;
"disclosure": string;
"downloadUrl"?: string;
"redaction"?: {
"removedFields": Array<string>;
"originalSha256": string;
};
};
}>;
"jdAlignment": Array<{
"jdRequirementId": string;
"statuses": Array<"not_reviewed" | "claimed_in_cv" | "work_sample_evidence" | "further_evidence_needed">;
"summary": string;
"remainingUnknowns": string;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"baseline": {
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"evidenceSnapshotId": string;
"fingerprint": string;
"fixtureVersion": string;
"rubricVersion": string;
"stage": "application_review";
"assessmentRevision": 1;
"annotationMode": "ai_authored";
"label": string;
"status": "reviewed";
"assessmentComplete": boolean;
"provenance": {
"sampleType": "synthetic";
"standardDesign": string;
"actualAnnotation": string;
"actualReview": string;
"humanCalibration": "pending";
"externalExpertValidation": false;
"note": string;
};
"items": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"score": {
"status": "complete" | "needs_evidence" | "pending";
"assessmentComplete": boolean;
"complete": boolean;
"coveragePercent": number | null;
"accruedScore": number;
"overallScore": number | null;
"overallPercentage": number | null;
"criteria": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE" | null;
"status": "assessed" | "needs_evidence" | "pending";
"contribution": number | null;
}>;
"skills": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
"maxScore": number;
"assessmentComplete": boolean;
"complete": boolean;
"evaluatedCount": number;
"neCount": number;
"pendingCount": number;
"accruedScore": number;
"score": number | null;
"percentage": number | null;
}>;
};
};
"initialReport": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"status": "supported" | "uncertain";
"displayStatus": string;
"mode": "preset";
"summary": string;
"uncertainty": string;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
};
"dataset": {
"version": string;
"provenance": string;
"records": Array<{
"id": string;
"period": string;
"channel": string;
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
}>;
"metrics": {
"previous": {
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
"conversionPct": number;
};
"current": {
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
"conversionPct": number;
};
"change": {
"trafficPct": number;
"ordersPct": number;
"adSpendPct": number;
"conversionPercentagePoints": number;
};
};
"channels": Array<{
"id": string;
"channel": string;
"traffic": number;
"growth": number;
"orders": number;
"conversion": number;
"previous": number;
"revenue": number;
"trafficSharePct": number;
"before": {
"id": string;
"period": string;
"channel": string;
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
};
"current": {
"id": string;
"period": string;
"channel": string;
"sessions": number;
"orders": number;
"adSpendCents": number;
"revenueCents": number;
};
}>;
"trafficTrend": Array<{
"period": string;
"label": string;
"sessions": number;
"traffic": number;
"orders": number;
"conversion": number;
}>;
"resources": Array<{
"id": string;
"name": string;
"datasetVersion": string;
"provenance": string;
"mimeType": string;
"description": string;
"columns": Array<string>;
"rows": Array<Array<string>>;
"content": string;
"sizeBytes": number;
"text"?: string;
}>;
};
"task": {
"taskId": string;
"status": "draft" | "sent" | "submitted" | "awaiting_revision" | "reviewed";
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving" | null;
"templateId": string | null;
"title": string;
"instructions": string;
"gapReason": string;
"sentAt": string | null;
"timeboxMinutes": 20;
};
"taskTemplates": {
"sql": {
"templateId": string;
"title": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"instructions": string;
"timeboxMinutes": 20;
"timeboxEnforced": false;
"datasetVersion": string;
"resourceIds": Array<string>;
"observationDimensions": Array<string>;
"mode": "preset";
};
"data-analysis": {
"templateId": string;
"title": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"instructions": string;
"timeboxMinutes": 20;
"timeboxEnforced": false;
"datasetVersion": string;
"resourceIds": Array<string>;
"observationDimensions": Array<string>;
"mode": "preset";
};
"business-problem-solving": {
"templateId": string;
"title": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"instructions": string;
"timeboxMinutes": 20;
"timeboxEnforced": false;
"datasetVersion": string;
"resourceIds": Array<string>;
"observationDimensions": Array<string>;
"mode": "preset";
};
};
"versions": Array<{
"submission": {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"submissionVersion": 1 | 2;
"previousSubmissionId": string | null;
"previousContentFingerprint": string | null;
"summary": string;
"findings": Array<{
"id": string;
"section": "Key Findings" | "Hypotheses" | "Additional Evidence Needed" | "Recommended Next Steps";
"title": string;
"detail": string;
"source": string;
"confidence": "High" | "Medium" | "Low";
}>;
"processEvidence": Array<{
"id": string;
"at": string;
"title": string;
"detail"?: string;
}>;
"submissionId": string;
"submittedAt": string;
"contentFingerprint": string;
"processEvidenceProvenance": "client_reported";
"sources": Array<{
"sourceId": string;
"location": string;
"text": string;
"kind": "work_sample" | "client_reported_event";
}>;
};
"evidenceSnapshotId": string;
"analysis": {
"status": "not_started" | "running" | "succeeded" | "failed";
"attemptId": string | null;
"submissionId": string | null;
"contentFingerprint": string | null;
"startedAt": string | null;
"finishedAt": string | null;
"errorCode": string | null;
"result": {
"mode": "live" | "manual_simulation" | "replay";
"model": string | null;
"promptVersion": string;
"submissionId": string;
"contentFingerprint": string;
"observations": Array<{
"dimension": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "Problem Framing" | "Evidence Navigation" | "Hypothesis Formation" | "Evidence Seeking" | "Decision Making";
"status": "observed" | "not_observed";
"statement": string;
"citations": Array<{
"sourceId": string;
"location": string;
"quote": string;
"start": number;
"end": number;
}>;
"scope": string;
"uncertainty": string;
}>;
"provenance": {
"provider": "openai" | "manual_rules";
"generatedAt": string;
"responseId": string | null;
"processEvidence": "client_reported";
};
} | null;
};
"review": {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"submissionId": string;
"contentFingerprint": string;
"decision": "confirm" | "needs_more_evidence" | "evidence_still_insufficient";
"comment": string;
"reviewId": string;
"reviewedAt": string;
} | null;
}>;
"submission": {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"submissionVersion": 1 | 2;
"previousSubmissionId": string | null;
"previousContentFingerprint": string | null;
"summary": string;
"findings": Array<{
"id": string;
"section": "Key Findings" | "Hypotheses" | "Additional Evidence Needed" | "Recommended Next Steps";
"title": string;
"detail": string;
"source": string;
"confidence": "High" | "Medium" | "Low";
}>;
"processEvidence": Array<{
"id": string;
"at": string;
"title": string;
"detail"?: string;
}>;
"submissionId": string;
"submittedAt": string;
"contentFingerprint": string;
"processEvidenceProvenance": "client_reported";
"sources": Array<{
"sourceId": string;
"location": string;
"text": string;
"kind": "work_sample" | "client_reported_event";
}>;
} | null;
"analysis": {
"status": "not_started" | "running" | "succeeded" | "failed";
"attemptId": string | null;
"submissionId": string | null;
"contentFingerprint": string | null;
"startedAt": string | null;
"finishedAt": string | null;
"errorCode": string | null;
"result": {
"mode": "live" | "manual_simulation" | "replay";
"model": string | null;
"promptVersion": string;
"submissionId": string;
"contentFingerprint": string;
"observations": Array<{
"dimension": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "Problem Framing" | "Evidence Navigation" | "Hypothesis Formation" | "Evidence Seeking" | "Decision Making";
"status": "observed" | "not_observed";
"statement": string;
"citations": Array<{
"sourceId": string;
"location": string;
"quote": string;
"start": number;
"end": number;
}>;
"scope": string;
"uncertainty": string;
}>;
"provenance": {
"provider": "openai" | "manual_rules";
"generatedAt": string;
"responseId": string | null;
"processEvidence": "client_reported";
};
} | null;
};
"review": {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"submissionId": string;
"contentFingerprint": string;
"decision": "confirm" | "needs_more_evidence" | "evidence_still_insufficient";
"comment": string;
"reviewId": string;
"reviewedAt": string;
} | null;
"currentSubmissionVersion": 1 | 2 | null;
"workflow": {
"maxSubmissions": 2;
"submissionsUsed": number;
"remainingSubmissions": number;
"canSubmit": boolean;
"canResubmit": boolean;
"nextSubmissionVersion": 1 | 2 | null;
"allowedReviewDecisions": Array<"confirm" | "needs_more_evidence" | "evidence_still_insufficient">;
"isTerminal": boolean;
"canSend": boolean;
};
"capabilities": {
"contract": "4.0";
"analysisMode": "disabled" | "manual_simulation" | "live";
"analysisAvailable": boolean;
"analysisUnavailableReason": "AI_DISABLED" | "AI_NOT_CONFIGURED" | null;
"upload": false;
"authentication": false;
"authenticationScope": string;
"writeAccess": {
"enforcement": "deployment_defined";
"status": "unknown";
"loginPath": string;
};
"analysisModeLabel": string;
"sqlExecution": false;
};
"assessment": {
"application_review": {
"assessmentId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"rubricVersion": string;
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"submissionId": string | null;
"contentFingerprint": string | null;
"assessmentRevision": number;
"status": "reviewed";
"annotationMode": "ai_authored" | "human";
"operatorLabel": string;
"createdAt": string;
"items": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"reuseApplication": {
"assessmentRevision": number;
"evidenceSnapshotId": string;
"fingerprint": string;
} | null;
"reusedItems": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"score": {
"status": "complete" | "needs_evidence" | "pending";
"assessmentComplete": boolean;
"complete": boolean;
"coveragePercent": number | null;
"accruedScore": number;
"overallScore": number | null;
"overallPercentage": number | null;
"criteria": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE" | null;
"status": "assessed" | "needs_evidence" | "pending";
"contribution": number | null;
}>;
"skills": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
"maxScore": number;
"assessmentComplete": boolean;
"complete": boolean;
"evaluatedCount": number;
"neCount": number;
"pendingCount": number;
"accruedScore": number;
"score": number | null;
"percentage": number | null;
}>;
};
} | null;
"task_v1": {
"assessmentId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"rubricVersion": string;
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"submissionId": string | null;
"contentFingerprint": string | null;
"assessmentRevision": number;
"status": "reviewed";
"annotationMode": "ai_authored" | "human";
"operatorLabel": string;
"createdAt": string;
"items": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"reuseApplication": {
"assessmentRevision": number;
"evidenceSnapshotId": string;
"fingerprint": string;
} | null;
"reusedItems": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"score": {
"status": "complete" | "needs_evidence" | "pending";
"assessmentComplete": boolean;
"complete": boolean;
"coveragePercent": number | null;
"accruedScore": number;
"overallScore": number | null;
"overallPercentage": number | null;
"criteria": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE" | null;
"status": "assessed" | "needs_evidence" | "pending";
"contribution": number | null;
}>;
"skills": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
"maxScore": number;
"assessmentComplete": boolean;
"complete": boolean;
"evaluatedCount": number;
"neCount": number;
"pendingCount": number;
"accruedScore": number;
"score": number | null;
"percentage": number | null;
}>;
};
} | null;
"task_v2": {
"assessmentId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"rubricVersion": string;
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"submissionId": string | null;
"contentFingerprint": string | null;
"assessmentRevision": number;
"status": "reviewed";
"annotationMode": "ai_authored" | "human";
"operatorLabel": string;
"createdAt": string;
"items": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"reuseApplication": {
"assessmentRevision": number;
"evidenceSnapshotId": string;
"fingerprint": string;
} | null;
"reusedItems": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"score": {
"status": "complete" | "needs_evidence" | "pending";
"assessmentComplete": boolean;
"complete": boolean;
"coveragePercent": number | null;
"accruedScore": number;
"overallScore": number | null;
"overallPercentage": number | null;
"criteria": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE" | null;
"status": "assessed" | "needs_evidence" | "pending";
"contribution": number | null;
}>;
"skills": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
"maxScore": number;
"assessmentComplete": boolean;
"complete": boolean;
"evaluatedCount": number;
"neCount": number;
"pendingCount": number;
"accruedScore": number;
"score": number | null;
"percentage": number | null;
}>;
};
} | null;
"history": Array<{
"assessmentId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"rubricVersion": string;
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"submissionId": string | null;
"contentFingerprint": string | null;
"assessmentRevision": number;
"status": "reviewed";
"annotationMode": "ai_authored" | "human";
"operatorLabel": string;
"createdAt": string;
"items": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"reuseApplication": {
"assessmentRevision": number;
"evidenceSnapshotId": string;
"fingerprint": string;
} | null;
"reusedItems": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"score": {
"status": "complete" | "needs_evidence" | "pending";
"assessmentComplete": boolean;
"complete": boolean;
"coveragePercent": number | null;
"accruedScore": number;
"overallScore": number | null;
"overallPercentage": number | null;
"criteria": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE" | null;
"status": "assessed" | "needs_evidence" | "pending";
"contribution": number | null;
}>;
"skills": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
"maxScore": number;
"assessmentComplete": boolean;
"complete": boolean;
"evaluatedCount": number;
"neCount": number;
"pendingCount": number;
"accruedScore": number;
"score": number | null;
"percentage": number | null;
}>;
};
}>;
};
"shortlist": {
"revision": number;
"status": "not_retained" | "retained" | "needs_reconfirmation";
"reason": string | null;
"basis": {
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"assessmentRevision": number | null;
"rubricVersion": string;
} | null;
"history": Array<{
"revision": number;
"action": "retain" | "remove" | "reconfirm";
"reason": string;
"operatorLabel": string;
"at": string;
"materialRevision": number;
"basis": {
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"assessmentRevision": number | null;
"rubricVersion": string;
};
}>;
};
"report": {
"isHiringDecision": false;
"requirements": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"title": string;
"evidenceSnapshotId": string;
"fingerprint": string;
"status": "supported" | "uncertain" | "verified";
"mode": "preset" | "human_reviewed";
"summary": string;
"uncertainty": string;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
"review": {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"submissionId": string;
"contentFingerprint": string;
"decision": "confirm" | "needs_more_evidence" | "evidence_still_insufficient";
"comment": string;
"reviewId": string;
"reviewedAt": string;
} | null;
"scope": string;
}>;
};
};
"meta": {
"replayed": boolean;
};
};
export type ComparisonEnvelope = {
"data": {
"schemaVersion": "4.0";
"sessionId": string;
"revision": number;
"datasetVersion": string;
"fixtureVersion": string;
"jdVersion": string;
"rubricVersion": string;
"company": {
"id": string;
"name": string;
"provenance": "user_supplied_demo_jd";
"location": string;
"businessDescription": string;
"profileScope": string;
};
"job": {
"id": string;
"title": string;
"company": string;
"requirements": Array<{
"id": string;
"title": string;
"statement": string;
}>;
"successStages": Array<string>;
"location": string;
"employmentType": string;
"experienceLevel": string;
"team": string;
"collaboratingTeams": Array<string>;
"supportedByExperiencedAnalysts": true;
"jd": {
"version": string;
"sourceId": string;
"filePath": string;
"sha256": string;
"pages": number;
"scope": string;
"source": {
"sourceId": string;
"location": string;
"text": string;
"fingerprint": string;
"sha256": string;
"downloadUrl": string;
};
"requirements": Array<{
"id": string;
"category": "essential" | "desirable" | "responsibility";
"statement": string;
"page": number;
"start": number;
"end": number;
"quote": string;
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
}>;
};
};
"rubric": {
"version": string;
"jobId": string;
"provenance": string;
"calibrationStatus": string;
"label": string;
"scope": string;
"requirements": Array<{
"id": "sql" | "data-analysis" | "business-problem-solving";
"title": string;
"maxScore": number;
"statement": string;
}>;
"marks": Array<{
"mark": number | "NE";
"meaning": string;
}>;
"criteria": Array<{
"id": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"title": string;
"observableSupport": string;
"maxScore": 10;
"anchors": {
"0": string;
"2": string;
"4": string;
};
}>;
"rules": {
"maxScore": 100;
"criterionContribution": string;
"displayDecimalPlaces": number;
"neIsZero": false;
"autoPassThreshold": null;
"rounding": string;
};
};
"stage": "application_review";
"applicationsReviewed": number;
"candidatesWithCompleteCoreEvidence": number;
"sortPolicy": string;
"limitations": string;
"candidates": Array<{
"candidate": {
"id": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"name": string;
"background": string;
};
"application": {
"id": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"evidenceSnapshotId": string;
"fingerprint": string;
"fixtureVersion": string;
"provenance": "synthetic";
"materialVersion": 1;
"scope": string;
"sources": Array<{
"sourceId": string;
"location": string;
"text": string;
"kind": "application" | "work_sample";
"provenance"?: {
"origin": "user_supplied_fictional_cv" | "synthetic_demo_work_sample";
"filePath": string;
"sha256": string;
"pageNumbers": Array<number>;
"disclosure": string;
"downloadUrl"?: string;
"redaction"?: {
"removedFields": Array<string>;
"originalSha256": string;
};
};
}>;
"jdAlignment": Array<{
"jdRequirementId": string;
"statuses": Array<"not_reviewed" | "claimed_in_cv" | "work_sample_evidence" | "further_evidence_needed">;
"summary": string;
"remainingUnknowns": string;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"baseline": {
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"evidenceSnapshotId": string;
"fingerprint": string;
"fixtureVersion": string;
"rubricVersion": string;
"stage": "application_review";
"assessmentRevision": 1;
"annotationMode": "ai_authored";
"label": string;
"status": "reviewed";
"assessmentComplete": boolean;
"provenance": {
"sampleType": "synthetic";
"standardDesign": string;
"actualAnnotation": string;
"actualReview": string;
"humanCalibration": "pending";
"externalExpertValidation": false;
"note": string;
};
"items": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"score": {
"status": "complete" | "needs_evidence" | "pending";
"assessmentComplete": boolean;
"complete": boolean;
"coveragePercent": number | null;
"accruedScore": number;
"overallScore": number | null;
"overallPercentage": number | null;
"criteria": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE" | null;
"status": "assessed" | "needs_evidence" | "pending";
"contribution": number | null;
}>;
"skills": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
"maxScore": number;
"assessmentComplete": boolean;
"complete": boolean;
"evaluatedCount": number;
"neCount": number;
"pendingCount": number;
"accruedScore": number;
"score": number | null;
"percentage": number | null;
}>;
};
};
"initialReport": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"status": "supported" | "uncertain";
"displayStatus": string;
"mode": "preset";
"summary": string;
"uncertainty": string;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
};
"assessment": {
"assessmentId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"rubricVersion": string;
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"submissionId": string | null;
"contentFingerprint": string | null;
"assessmentRevision": number;
"status": "reviewed";
"annotationMode": "ai_authored" | "human";
"operatorLabel": string;
"createdAt": string;
"items": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"reuseApplication": {
"assessmentRevision": number;
"evidenceSnapshotId": string;
"fingerprint": string;
} | null;
"reusedItems": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"score": {
"status": "complete" | "needs_evidence" | "pending";
"assessmentComplete": boolean;
"complete": boolean;
"coveragePercent": number | null;
"accruedScore": number;
"overallScore": number | null;
"overallPercentage": number | null;
"criteria": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE" | null;
"status": "assessed" | "needs_evidence" | "pending";
"contribution": number | null;
}>;
"skills": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
"maxScore": number;
"assessmentComplete": boolean;
"complete": boolean;
"evaluatedCount": number;
"neCount": number;
"pendingCount": number;
"accruedScore": number;
"score": number | null;
"percentage": number | null;
}>;
};
} | null;
"assessmentComplete": boolean;
"gapSuggestions": Array<{
"gapId": string;
"stage": "application_review" | "task_v1" | "task_v2";
"assessmentRevision": number;
"evidenceSnapshotId": string;
"fingerprint": string;
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE";
"severity": "observed_problem" | "missing_evidence" | "material_gap" | "minor_gap";
"priority": number;
"priorityReason": string;
"summary": string;
"rationale": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
"requiresHumanConfirmation": true;
"suggestedFirstAction": string;
}>;
"task": {
"taskId": string;
"status": "draft" | "sent" | "submitted" | "awaiting_revision" | "reviewed";
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving" | null;
"templateId": string | null;
"title": string;
"instructions": string;
"gapReason": string;
"sentAt": string | null;
"timeboxMinutes": 20;
};
"taskAssessments": Array<{
"assessmentId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": string;
"rubricVersion": string;
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"submissionId": string | null;
"contentFingerprint": string | null;
"assessmentRevision": number;
"status": "reviewed";
"annotationMode": "ai_authored" | "human";
"operatorLabel": string;
"createdAt": string;
"items": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"reuseApplication": {
"assessmentRevision": number;
"evidenceSnapshotId": string;
"fingerprint": string;
} | null;
"reusedItems": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"score": {
"status": "complete" | "needs_evidence" | "pending";
"assessmentComplete": boolean;
"complete": boolean;
"coveragePercent": number | null;
"accruedScore": number;
"overallScore": number | null;
"overallPercentage": number | null;
"criteria": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"mark": number | "NE" | null;
"status": "assessed" | "needs_evidence" | "pending";
"contribution": number | null;
}>;
"skills": Array<{
"requirementId": "sql" | "data-analysis" | "business-problem-solving";
"criterionIds": Array<"S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4">;
"maxScore": number;
"assessmentComplete": boolean;
"complete": boolean;
"evaluatedCount": number;
"neCount": number;
"pendingCount": number;
"accruedScore": number;
"score": number | null;
"percentage": number | null;
}>;
};
}>;
"shortlist": {
"revision": number;
"status": "not_retained" | "retained" | "needs_reconfirmation";
"reason": string | null;
"basis": {
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"assessmentRevision": number | null;
"rubricVersion": string;
} | null;
"history": Array<{
"revision": number;
"action": "retain" | "remove" | "reconfirm";
"reason": string;
"operatorLabel": string;
"at": string;
"materialRevision": number;
"basis": {
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"assessmentRevision": number | null;
"rubricVersion": string;
};
}>;
};
}>;
};
"meta": {
"replayed": boolean;
};
};
export type SendRequest = {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"templateId": string;
"instructions": string;
"gapReason": string;
};
export type SubmitRequest = {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"submissionVersion": 1 | 2;
"previousSubmissionId": string | null;
"previousContentFingerprint": string | null;
"summary": string;
"findings": Array<{
"id": string;
"section": "Key Findings" | "Hypotheses" | "Additional Evidence Needed" | "Recommended Next Steps";
"title": string;
"detail": string;
"source": string;
"confidence": "High" | "Medium" | "Low";
}>;
"processEvidence": Array<{
"id": string;
"at": string;
"title": string;
"detail"?: string;
}>;
};
export type AnalyzeRequest = {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"submissionId": string;
"contentFingerprint": string;
};
export type ReviewRequest = {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"targetRequirementId": "sql" | "data-analysis" | "business-problem-solving";
"submissionId": string;
"contentFingerprint": string;
"decision": "confirm" | "needs_more_evidence" | "evidence_still_insufficient";
"comment": string;
};
export type AssessmentRequest = {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"submissionId": string | null;
"contentFingerprint": string | null;
"rubricVersion": string;
"expectedAssessmentRevision": number;
"items": Array<{
"criterionId": "S1" | "S2" | "S3" | "D1" | "D2" | "D3" | "B1" | "B2" | "B3" | "B4";
"mark": number | "NE";
"rationale": string;
"support": string;
"gaps": string;
"uncertainty": string;
"nextStep": string;
"checkedSourceIds": Array<string>;
"sourceRefs": Array<{
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"evidenceSnapshotId": string;
"fingerprint": string;
"sourceId": string;
"location": string;
"start": number;
"end": number;
"quote": string;
}>;
}>;
"reuseApplication": {
"assessmentRevision": number;
"evidenceSnapshotId": string;
"fingerprint": string;
} | null;
"operatorLabel": string;
};
export type ShortlistRequest = {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"action": "retain" | "remove" | "reconfirm";
"reason": string;
"stage": "application_review" | "task_v1" | "task_v2";
"evidenceSnapshotId": string;
"fingerprint": string;
"assessmentRevision": number | null;
"rubricVersion": string;
"expectedShortlistRevision": number;
"operatorLabel": string;
};
export type ResetRequest = {
"schemaVersion": "4.0";
"sessionId": string;
};
export type RestartRequest = {
"schemaVersion": "4.0";
"sessionId": string;
"candidateId": "amy-chen" | "ann-li" | "david-liu" | "jamie-parker";
"jobId": "junior-data-analyst";
"datasetVersion": string;
"taskId": string;
"expectedRevision": number;
"checkpoint": "before_task" | "ready_for_v1";
};
export type Demo = Envelope['data'];
export type Comparison = ComparisonEnvelope['data'];
export type CandidateId = Demo['candidate']['id'];
export type RequirementId = SendRequest['targetRequirementId'];
export type Stage = AssessmentRequest['stage'];
export type Submission = NonNullable<Demo['submission']>;
export type Version = Demo['versions'][number];
export type Finding = Submission['findings'][number];
export type ProcessEvent = Submission['processEvidence'][number];
export type Source = Submission['sources'][number];
export type Citation = NonNullable<Demo['analysis']['result']>['observations'][number]['citations'][number];
export type Resource = Demo['dataset']['resources'][number];
export type Decision = ReviewRequest['decision'];
export type AssessmentRecord = NonNullable<Demo['assessment']['application_review']>;
export type AssessmentItem = AssessmentRequest['items'][number];
export type SourceRef = AssessmentItem['sourceRefs'][number];
export type Score = AssessmentRecord['score'];
export type Shortlist = Demo['shortlist'];
