import { GlideSelect } from './glide-select';
import React, { useState } from 'react';
import type { Demo, Finding } from './api-types';
import { Dialog } from './api-ui';

export function CardEditor({ finding, resources, editable, close, save, remove }: { finding: Finding; resources: Demo['dataset']['resources']; editable: boolean; close: () => void; save: (f: Finding) => void; remove: () => void }) {
  const [form, setForm] = useState(finding);
  return <Dialog title={finding.section} close={close}><form onSubmit={e => { e.preventDefault(); if (editable && form.title.trim()) save(form); }}><label className="eb-field" htmlFor="api-card-title">Observation or idea</label><input id="api-card-title" maxLength={300} required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })}/><label className="eb-field" htmlFor="api-card-detail">Reasoning & supporting evidence</label><textarea id="api-card-detail" maxLength={4000} value={form.detail} onChange={e => setForm({ ...form, detail: e.target.value })}/><div className="eb-form-row"><label className="eb-field">Evidence source<GlideSelect ariaLabel="Evidence source" value={form.source} onChange={value => setForm({ ...form, source: value })} options={[{value:'',label:'Not supplied'}, ...resources.map(r => ({value:r.id,label:r.name}))]}/></label><label className="eb-field">Self-reported confidence<GlideSelect ariaLabel="Self-reported confidence" value={form.confidence} onChange={value => setForm({ ...form, confidence: value as Finding['confidence'] })} options={['High','Medium','Low'].map(value => ({value,label:value}))}/></label></div><div className="eb-actions"><button className="eb-action primary" disabled={!editable || !form.title.trim()} type="submit">Save card</button><button className="eb-action danger" type="button" disabled={!editable} onClick={remove}>Delete card</button><button className="eb-action" type="button" onClick={close}>Cancel</button></div></form></Dialog>;
}
