"""Generate independent browser API4 types from the frozen OpenAPI; no runtime dependency."""
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
doc = json.loads((root / 'docs/backend/r6/openapi.json').read_text(encoding='utf-8'))

def ts(schema):
    if '$ref' in schema:
        target = doc
        for key in schema['$ref'].split('/')[1:]:
            target = target[key]
        return ts(target)
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(value) for value in schema['enum'])
    for union in ['anyOf', 'oneOf']:
        if union in schema:
            return ' | '.join(ts(value) for value in schema[union])
    kind = schema.get('type')
    if kind == 'object':
        return '{\n' + '\n'.join(json.dumps(key) + ('' if key in schema.get('required', []) else '?') + ': ' + ts(value) + ';' for key, value in schema.get('properties', {}).items()) + '\n}'
    if kind == 'array':
        return 'Array<' + ts(schema['items']) + '>'
    return {'string': 'string', 'integer': 'number', 'number': 'number', 'boolean': 'boolean', 'null': 'null'}.get(kind, 'unknown')

output = '// Generated by python3 scripts/frontend-types-v4.py from API4 OpenAPI. Do not hand edit.\n'
for name, path in [('Envelope', '/api/demo'), ('ComparisonEnvelope', '/api/demo/comparison')]:
    schema = doc['paths'][path]['get']['responses']['200']['content']['application/json']['schema']
    output += f'export type {name} = {ts(schema)};\n'
for name, path in [('Send', '/task/send'), ('Submit', '/submission'), ('Analyze', '/analysis'), ('Review', '/review'), ('Assessment', '/assessment'), ('Shortlist', '/shortlist'), ('Reset', '/reset')]:
    schema = doc['paths']['/api/demo' + path]['post']['requestBody']['content']['application/json']['schema']
    output += f'export type {name}Request = {ts(schema)};\n'
output += '''export type Demo = Envelope['data'];
export type Comparison = ComparisonEnvelope['data'];
export type CandidateId = Demo['candidate']['id'];
export type RequirementId = SendRequest['targetRequirementId'];
export type Stage = AssessmentRequest['stage'];
export type Submission = NonNullable<Demo['submission']>;
export type Version = Demo['versions'][number];
export type Finding = Submission['findings'][number];
export type ProcessEvent = Submission['processEvidence'][number];
export type Source = Submission['sources'][number];
export type Citation = NonNullable<Demo['analysis']['result']>['observations'][number]['citations'][number];
export type Resource = Demo['dataset']['resources'][number];
export type Decision = ReviewRequest['decision'];
export type AssessmentRecord = NonNullable<Demo['assessment']['application_review']>;
export type AssessmentItem = AssessmentRequest['items'][number];
export type SourceRef = AssessmentItem['sourceRefs'][number];
export type Score = AssessmentRecord['score'];
export type Shortlist = Demo['shortlist'];
'''
target = root / 'app/shared/api4-types.ts'
if '--check' in sys.argv:
    if not target.exists() or target.read_text(encoding='utf-8') != output:
        raise SystemExit('API4 browser types differ from the frozen OpenAPI. Regenerate them.')
    print('API4 browser types match the frozen OpenAPI')
else:
    target.write_text(output, encoding='utf-8')
    print('Generated independent API4 browser types')
