"""Generate browser-only TypeScript from the committed OpenAPI, with no runtime dependency."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
doc = json.loads((root / 'docs/backend/openapi.json').read_text(encoding='utf-8'))

def ts(s):
    if '$ref' in s:
        target = doc
        for key in s['$ref'].split('/')[1:]:
            target = target[key]
        return ts(target)
    if 'const' in s:
        return json.dumps(s['const'])
    if 'enum' in s:
        return ' | '.join(json.dumps(x) for x in s['enum'])
    for union in ['anyOf', 'oneOf']:
        if union in s:
            return ' | '.join(ts(x) for x in s[union])
    kind = s.get('type')
    if kind == 'object':
        return '{\n' + '\n'.join(json.dumps(k) + ('' if k in s.get('required', []) else '?') + ': ' + ts(v) + ';' for k, v in s.get('properties', {}).items()) + '\n}'
    if kind == 'array':
        return 'Array<' + ts(s['items']) + '>'
    return {'string':'string', 'integer':'number', 'number':'number', 'boolean':'boolean', 'null':'null'}.get(kind, 'unknown')

schema = doc['paths']['/api/demo']['get']['responses']['200']['content']['application/json']['schema']
output = '// Generated by python scripts/frontend-types.py from API 2.0 OpenAPI. Do not hand edit.\nexport type Envelope = ' + ts(schema) + ';\n'
output += '''export type Demo = Envelope['data'];
export type Submission = NonNullable<Demo['submission']>;
export type Finding = Submission['findings'][number];
export type ProcessEvent = Submission['processEvidence'][number];
export type Version = Demo['versions'][number];
export type Citation = NonNullable<Demo['analysis']['result']>['observations'][number]['citations'][number];
export type Resource = Demo['dataset']['resources'][number];
export type Decision = NonNullable<Demo['review']>['decision'];
'''
(root / 'app/shared/api-types.ts').write_text(output, encoding='utf-8')
print('Generated browser contract types from OpenAPI')
